"""The row schedule under row sharding is ONE schedule on every rank: the free device bytes it derives from are agreed across ranks
(opt_core.mem.rowpair.dist.agreed_free_bytes: min over ranks) before trimul's RA / RB are chosen. (a) At world size 1 / without a group
the selection is 0.4.1's, value for value (recorded fixtures below were generated by 0.4.1's ``default_rows_a`` / ``default_rows_b``); (b) two gloo
ranks that see UNEQUAL free bytes (mocked) choose the same RA / RB, complete both contractions and match the dense statement."""
import json
import os

import pytest

try:
    import torch  # noqa: F401
    HAVE_TORCH = True
except Exception:                                             # noqa: BLE001
    HAVE_TORCH = False

needs_torch = pytest.mark.skipif(not HAVE_TORCH, reason="torch not importable")

# (N, C, elt, Rmax, budget_bytes, RA, RB) — opt_core 0.4.1 default_rows_a / default_rows_b with an explicit budget
GOLDEN_EXPLICIT = [(384, 32, 2, 128, None, 128, 128), (384, 32, 2, 128, 12884901888, 128, 128), (384, 32, 2, 256, 2147483648, 256, 256), (384, 32, 2, 768, 314572800, 768, 768), (384, 32, 2, 1478, 10485760, 384, 128), (384, 32, 4, 128, None, 128, 128), (384, 32, 4, 128, 12884901888, 128, 128), (384, 32, 4, 256, 2147483648, 256, 256), (384, 32, 4, 768, 314572800, 768, 768), (384, 32, 4, 1478, 10485760, 128, 128), (384, 128, 2, 128, None, 128, 128), (384, 128, 2, 128, 12884901888, 128, 128), (384, 128, 2, 256, 2147483648, 256, 256), (384, 128, 2, 768, 314572800, 768, 768), (384, 128, 2, 1478, 10485760, 128, 128), (384, 128, 4, 128, None, 128, 128), (384, 128, 4, 128, 12884901888, 128, 128), (384, 128, 4, 256, 2147483648, 256, 256), (384, 128, 4, 768, 314572800, 768, 768), (384, 128, 4, 1478, 10485760, 128, 128), (992, 32, 2, 128, None, 128, 128), (992, 32, 2, 128, 12884901888, 128, 128), (992, 32, 2, 256, 2147483648, 256, 256), (992, 32, 2, 768, 314572800, 768, 768), (992, 32, 2, 1478, 10485760, 128, 128), (992, 32, 4, 128, None, 128, 128), (992, 32, 4, 128, 12884901888, 128, 128), (992, 32, 4, 256, 2147483648, 256, 256), (992, 32, 4, 768, 314572800, 768, 768), (992, 32, 4, 1478, 10485760, 128, 128), (992, 128, 2, 128, None, 128, 128), (992, 128, 2, 128, 12884901888, 128, 128), (992, 128, 2, 256, 2147483648, 256, 256), (992, 128, 2, 768, 314572800, 768, 512), (992, 128, 2, 1478, 10485760, 128, 128), (992, 128, 4, 128, None, 128, 128), (992, 128, 4, 128, 12884901888, 128, 128), (992, 128, 4, 256, 2147483648, 256, 256), (992, 128, 4, 768, 314572800, 512, 256), (992, 128, 4, 1478, 10485760, 128, 128), (1536, 32, 2, 128, None, 128, 128), (1536, 32, 2, 128, 12884901888, 128, 128), (1536, 32, 2, 256, 2147483648, 256, 256), (1536, 32, 2, 768, 314572800, 768, 768), (1536, 32, 2, 1478, 10485760, 128, 128), (1536, 32, 4, 128, None, 128, 128), (1536, 32, 4, 128, 12884901888, 128, 128), (1536, 32, 4, 256, 2147483648, 256, 256), (1536, 32, 4, 768, 314572800, 768, 768), (1536, 32, 4, 1478, 10485760, 128, 128), (1536, 128, 2, 128, None, 128, 128), (1536, 128, 2, 128, 12884901888, 128, 128), (1536, 128, 2, 256, 2147483648, 256, 256), (1536, 128, 2, 768, 314572800, 768, 384), (1536, 128, 2, 1478, 10485760, 128, 128), (1536, 128, 4, 128, None, 128, 128), (1536, 128, 4, 128, 12884901888, 128, 128), (1536, 128, 4, 256, 2147483648, 256, 256), (1536, 128, 4, 768, 314572800, 384, 128), (1536, 128, 4, 1478, 10485760, 128, 128), (2956, 32, 2, 128, None, 128, 128), (2956, 32, 2, 128, 12884901888, 128, 128), (2956, 32, 2, 256, 2147483648, 256, 256), (2956, 32, 2, 768, 314572800, 768, 768), (2956, 32, 2, 1478, 10485760, 128, 128), (2956, 32, 4, 128, None, 128, 128), (2956, 32, 4, 128, 12884901888, 128, 128), (2956, 32, 4, 256, 2147483648, 256, 256), (2956, 32, 4, 768, 314572800, 768, 384), (2956, 32, 4, 1478, 10485760, 128, 128), (2956, 128, 2, 128, None, 128, 128), (2956, 128, 2, 128, 12884901888, 128, 128), (2956, 128, 2, 256, 2147483648, 256, 256), (2956, 128, 2, 768, 314572800, 384, 128), (2956, 128, 2, 1478, 10485760, 128, 128), (2956, 128, 4, 128, None, 128, 128), (2956, 128, 4, 128, 12884901888, 128, 128), (2956, 128, 4, 256, 2147483648, 256, 256), (2956, 128, 4, 768, 314572800, 128, 128), (2956, 128, 4, 1478, 10485760, 128, 128)]
# (free_bytes, N, C, elt, Rmax, RA, RB) — opt_core 0.4.1 with the device's free bytes mocked (None = no CUDA)
GOLDEN_DEVICE = [(None, 2956, 128, 2, 1478, 1478, 1478), (None, 2956, 128, 2, 768, 768, 768), (None, 1536, 64, 4, 768, 768, 768), (None, 992, 128, 2, 512, 512, 512), (3221225472, 2956, 128, 2, 1478, 1152, 384), (3221225472, 2956, 128, 2, 768, 768, 384), (3221225472, 1536, 64, 4, 768, 768, 768), (3221225472, 992, 128, 2, 512, 512, 512), (21474836480, 2956, 128, 2, 1478, 1478, 1478), (21474836480, 2956, 128, 2, 768, 768, 768), (21474836480, 1536, 64, 4, 768, 768, 768), (21474836480, 992, 128, 2, 512, 512, 512), (75161927680, 2956, 128, 2, 1478, 1478, 1478), (75161927680, 2956, 128, 2, 768, 768, 768), (75161927680, 1536, 64, 4, 768, 768, 768), (75161927680, 992, 128, 2, 512, 512, 512)]


def test_p1_row_selection_is_0_4_1s(monkeypatch):
    import opt_core.mem.budget as budget_mod
    from opt_core.mem.rowpair import trimul as T
    monkeypatch.delenv("ROWPAIR_TRIMUL_ROWS_A", raising=False)
    monkeypatch.delenv("ROWPAIR_TRIMUL_ROWS_B", raising=False)
    for N, C, elt, Rmax, budget, RA, RB in GOLDEN_EXPLICIT:
        assert (T.default_rows_a(N, C, elt, Rmax, budget), T.default_rows_b(N, C, elt, Rmax, budget)) == (RA, RB), (N, C, elt, Rmax, budget)
    for free, N, C, elt, Rmax, RA, RB in GOLDEN_DEVICE:
        monkeypatch.setattr(budget_mod, "device_free_bytes", lambda device=None, _f=free: _f)
        assert (T.default_rows_a(N, C, elt, Rmax), T.default_rows_b(N, C, elt, Rmax)) == (RA, RB), (free, N, C, elt, Rmax)


@needs_torch                                                   # dist's is_dist() reads torch.distributed
def test_agreed_free_bytes_without_a_group_is_this_ranks_reading(monkeypatch):
    import opt_core.mem.budget as budget_mod
    from opt_core.mem.rowpair.dist import agreed_free_bytes
    monkeypatch.setattr(budget_mod, "device_free_bytes", lambda device=None: 123456789)
    assert agreed_free_bytes() == 123456789
    monkeypatch.setattr(budget_mod, "device_free_bytes", lambda device=None: None)
    assert agreed_free_bytes() is None


def _entry_unequal_free_bytes(N: int, C: int, B: int):
    """Rank 0 sees 64 GiB free, rank 1 sees exactly enough for RA = 128 rows: un-agreed, the ring pass counts would differ (1 vs 2) and
    the ranks would meet in different collectives; agreed, both derive RA / RB from rank 1's bytes."""
    import torch
    import opt_core.mem.budget as budget_mod
    from opt_core.mem.rowpair import dist as D
    from opt_core.mem.rowpair import trimul as T
    from opt_core.mem.rowpair.shard import shard_rows, unshard_rows
    from tests.test_rowpair_logic import _cmp, _ok, _seeded, _tol
    P, r = D.world()
    lay = D.Layout.checked(N, P, r, B)
    elt = 8
    os.environ.pop("ROWPAIR_TRIMUL_ROWS_A", None); os.environ.pop("ROWPAIR_TRIMUL_ROWS_B", None)
    small = int(3 * 2 ** 20 / T.ABUF_FRAC)                             # ABUF share = 3 MiB -> RA = 128 at N*C*elt = 16 KiB per row
    frees = {0: 64 * 2 ** 30, 1: small}
    budget_mod.device_free_bytes = lambda device=None: frees[r]
    want = (T.default_rows_a(N, C, elt, lay.Rmax, int(small * T.ABUF_FRAC)), T.default_rows_b(N, C, elt, lay.Rmax, int(small * T.BBUF_FRAC)))
    alone = (T.default_rows_a(N, C, elt, lay.Rmax, int(frees[r] * T.ABUF_FRAC)), T.default_rows_b(N, C, elt, lay.Rmax, int(frees[r] * T.BBUF_FRAC)))
    a, b = _seeded(N, C, 3), _seeded(N, C, 4)
    res = {"P": P, "rank": r, "Rmax": lay.Rmax, "want": want, "alone": alone, "agreed_free": D.agreed_free_bytes(), "checks": {}, "metrics": {}, "got": {}}
    res["checks"]["free_is_rank1s_everywhere"] = res["agreed_free"] == small
    res["checks"]["ranks_would_disagree_alone"] = True if r == 1 else alone != want
    tol = _tol(torch.float64)
    with torch.no_grad():
        for outgoing in (True, False):
            tag = "outgoing" if outgoing else "incoming"
            dense = T.trimul_dense(a, b, outgoing)
            fn = T.trimul_outgoing if outgoing else T.trimul_incoming
            out, st = fn(shard_rows(a, lay).contiguous(), shard_rows(b, lay).contiguous(), lay)      # RA / RB from the agreed bytes
            res["got"][tag] = (st.RA, st.RB, st.tiles_source)
            res["checks"][tag + "_rows_are_rank1s"] = (st.RA, st.RB) == want and st.tiles_source == "budget"
            res["metrics"][tag] = _cmp(unshard_rows(out, lay), dense)
            res["checks"][tag + "_within_tol"] = _ok(res["metrics"][tag], tol)
    res["ok"] = all(res["checks"].values())
    import torch.distributed as tdist
    allres = [None] * P
    tdist.all_gather_object(allres, res)
    return {"P": P, "ranks": allres, "ok": all(x["ok"] for x in allres),
            "one_schedule": len({tuple(x["got"]["outgoing"][:2]) for x in allres} | {tuple(x["got"]["incoming"][:2]) for x in allres}) == 1}


@needs_torch
def test_mp_ranks_with_unequal_free_bytes_run_one_schedule_and_complete():
    from opt_core.mem.rowpair import launch
    os.environ["ROWPAIR_TEST_DEVICE"] = "cpu"
    res = launch.run_sharded(2, _entry_unequal_free_bytes, 512, 4, 128, mode="big", backend="gloo", cpu_ok=True, nccl_timeout_s=120, run_timeout_s=600)
    print("RESULT " + json.dumps(res, sort_keys=True, default=str))
    assert len(res["ranks"]) == 2 and res["one_schedule"], res
    bad = {x["rank"]: [k for k, v in x["checks"].items() if not v] for x in res["ranks"] if not x["ok"]}
    assert not bad, (bad, [(x["want"], x["alone"], x["got"], x["agreed_free"]) for x in res["ranks"]])
