[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atlasfold"
version = "1.0.0"
description = "Protein language model-based protein folding and co-folding"
authors = [
  { name = "SeonghwanSeo", email = "shwan0106@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["protein", "protein-language-model", "protein-folding", "cofolding"]
dependencies = [
  "numpy",
  "torch",
  "huggingface_hub",
]

[project.urls]
Homepage = "https://github.com/SeonghwanSeo/atlasfold"
Documentation = "https://github.com/SeonghwanSeo/atlasfold#readme"
Repository = "https://github.com/SeonghwanSeo/atlasfold"
Issues = "https://github.com/SeonghwanSeo/atlasfold/issues"

[project.scripts]
atlasfold = "atlasfold.cli:main"

[project.optional-dependencies]
fold = [
  "scipy",
  "einops",
  "gemmi",
  "omegaconf",
  "numba", # for SASA computation
]
cuequiv = [
  "cuequivariance_torch>=0.6.0",
  "cuequivariance_ops_cu12>=0.6.0",
  "cuequivariance_ops_torch_cu12>=0.6.0",
]
train = [
  "msgpack",
  "lightning", # for training loop
  "wandb", # for experiment tracking
  "lmdb", # for training dataset storage
  "pandas",
  "zstandard"
]
