"""Imported by atlasfold_opt_autoload.pth at interpreter start (text generated by opt/_build_backend.py). Cheap and stdlib-only: when
ATLASFOLD_OPT names a kit mode, a meta-path finder activates that mode the first time the atlasfold model family is imported; 'off'/unset
= nothing. An unknown word prints the NOT ACTIVE line and exits 3 at the trigger (never a silent stock run under a kit word)."""
import os
import sys

ENV, TAG = "ATLASFOLD_OPT", "atlasfold-opt"
TRIGGERS = ("atlasfold.model", "atlasfold.runner", "atlasfold.runner_multimer", "atlasfold.pretrained")
from .modes import MODE_NAMES as KNOWN                   # the one literal lives in modes.py
_word = (os.environ.get(ENV) or "").strip()


class _Finder:
    fired = False

    def find_spec(self, fullname, path=None, target=None):
        if self.fired or not any(fullname == t or fullname.startswith(t + ".") for t in TRIGGERS):
            return None
        _Finder.fired = True
        try:
            sys.meta_path.remove(self)
        except ValueError:
            pass
        if _word not in KNOWN:
            sys.stderr.write(f"[{TAG}] NOT ACTIVE: reason=unknown_mode:{_word} ({ENV}; known: {','.join(KNOWN)})\n"); sys.stderr.flush()
            raise SystemExit(3)
        import atlasfold_opt
        det = os.environ.get("AFO_DET")
        atlasfold_opt.enable(_word, trigger=fullname, det=int(det) if det else None,
                             allow_partial=os.environ.get("AFO_ALLOW_PARTIAL") == "1")
        return None


if _word and _word != "off" and not any(isinstance(f, _Finder) for f in sys.meta_path):
    sys.meta_path.insert(0, _Finder())
