"""Lazy autoload, installed at interpreter start by `chai1_opt_autoload.pth` (the shared core's autoload guard around `import
chai1_opt._autoload`, generated by `opt/_build_backend.py`: an import failure under CHAI1_OPT=exact|fast|big is `NOT ACTIVE`, exit 3).

With CHAI1_OPT=exact|fast|big in the environment, a meta-path finder waits for the first import of the trigger module and, right after
that module's own body has executed, calls `chai1_opt.enable(mode, strict=True)`; when the mode cannot be activated (pins, no GPU,
kit missing, weights missing, no in-process form) the core prints its NOT ACTIVE line and the process exits 3 — stock never runs
silently under CHAI1_OPT. Until then nothing else is imported (no torch, no upstream); with CHAI1_OPT unset or "off" no finder is
installed at all.

The trigger is the upstream model module `chai_lab.chai1` (the module that owns `load_exported` and `run_inference`); the levers
are the kit's own W1/W5 statements executed in this process (stack.py), which is why the hook fires after the module body and
before any fold — the only window the late-activation rule allows. The finder fires once and removes itself. `chai1-opt pred` (the
driver route) carries no CHAI1_OPT: the driver's `--levels` list is the switch there. The deterministic recipe on
this route follows the kit's own switch, `CHAI_DETERMINISTIC=1` (det.level_from_env): the same variable the kit driver reads.

`MODES` here is the kit-mode list of modes.KIT_MODE_NAMES, spelled again because this module must import nothing at interpreter
start (the pair is locked by the package tests).
"""
import os
import sys

ENV = "CHAI1_OPT"
TRIGGERS = ("chai_lab.chai1",)
MODES = ("exact", "fast", "big")
EXIT_NOT_ACTIVE = 3                                     # report.EXIT_NOT_ACTIVE, restated: this module imports nothing at interpreter start
DECLARED_ENV = ("CHAI1_OPT", "CHAI1_OPT_HOME", "CHAI1_OPT_KIT", "CHAI1_OPT_EAGER", "CHAI1_OPT_DSTEP", "CHAI1_OPT_ERRATA02", "CHAI1_OPT_ESM_MEMO_SCOPE", "CHAI1_OPT_STRICT_STACK",
                "CHAI1_OPT_ALLOW_PARTIAL", "CHAI1_OPT_AOTI_HOST_ISA")   # stack.DECLARED_ENV, restated (locked)
DECLARED_BIG_ENV = ("CHAI1_BIG_MSA_CHUNK_MIN_N", "CHAI1_BIG_NOGRAPH_MIN_N", "CHAI1_BIG_TRUNK_CHUNK_MIN_N", "CHAI1_BIG_OPM_CHUNK_MIN_N", "CHAI1_BIG_HOIST2_MAX_N")   # big.GATE_WORDS, restated (locked): the two size gates; no other CHAI1_BIG_* word exists
BIG_PREFIX = "CHAI1_BIG_"


def undeclared(environ) -> list:
    """``CHAI1_OPT*`` and ``CHAI1_BIG_*`` names in the environment this package does not declare (a mistyped switch, or a switch for a
    memory lever — a mode's lever set is fixed — would otherwise be ignored in silence)."""
    return sorted(k for k in environ if (k.startswith(DECLARED_ENV[0]) and k not in DECLARED_ENV) or (k.startswith(BIG_PREFIX) and k not in DECLARED_BIG_ENV))


class Finder:
    def __init__(self, mode):
        self.mode = mode
        self.fired = None

    def find_spec(self, fullname, path=None, target=None):
        if fullname not in TRIGGERS or self.fired:
            return None
        try:
            sys.meta_path.remove(self)                    # let the real finders resolve the spec
            import importlib.util
            spec = importlib.util.find_spec(fullname)
        finally:
            if self not in sys.meta_path and not self.fired:
                sys.meta_path.insert(0, self)
        if spec is None or spec.loader is None:
            return None
        loader = spec.loader
        if getattr(loader, "_chai1_opt_hooked", False):      # a find_spec probe already hooked this loader: the real import reuses it
            return spec
        orig_exec = loader.exec_module

        def exec_module(module):
            orig_exec(module)
            if not self.fired:                               # once: a reload of the trigger module does not re-fire
                self._fire(module.__name__)
        loader.exec_module = exec_module
        loader._chai1_opt_hooked = True
        return spec

    def _fire(self, trigger):
        self.fired = trigger
        try:
            sys.meta_path.remove(self)
        except ValueError:
            pass
        try:
            from chai1_opt import _core
            _core.entry_gate()                                # statement one: the pin gate — an absent, stale or older core is one NOT ACTIVE line, exit 3, before any opt_core import
            import chai1_opt
            from chai1_opt import det as _det
        except ImportError as e:                              # the package itself cannot be imported: named, exit 3 — never a traceback, never stock in silence
            sys.stderr.write(f"[chai1-opt] NOT ACTIVE: reason=core_missing:{getattr(e, 'name', None) or e} ({e})\n"); sys.stderr.flush()
            sys.exit(EXIT_NOT_ACTIVE)
        try:
            lv = _det.level_from_env()
            allow_partial = chai1_opt.stack.allow_partial_from_env()  # CHAI1_OPT_ALLOW_PARTIAL=1: this route's opt-out (validated by name); pred / the driver take --allow-partial instead
        except ValueError as e:
            sys.stderr.write(f"[chai1-opt] NOT ACTIVE: {e}\n"); sys.stderr.flush()
            sys.exit(EXIT_NOT_ACTIVE)
        try:
            # a mode is the whole of its lever set: a lever the run's own switches turned off makes the activation PARTIAL, refused by
            # name here (exit 3) exactly as on the command line — unless CHAI1_OPT_ALLOW_PARTIAL=1 (this route's word; the command line's is
            # --allow-partial), when it is RECORDED (the ACTIVE line's PARTIAL field, one NOTE line, the report) and the process runs on the
            # levers that did apply. A refused activation stops the process here (exit 3) rather than running stock silently.
            chai1_opt.enable(self.mode, strict=True, trigger=trigger, det=lv, allow_partial=allow_partial)
        except chai1_opt.ActivationError:
            # the core has printed `[chai1-opt] NOT ACTIVE: <reason>` (a missing shared core is one such reason: stack.gates)
            sys.exit(EXIT_NOT_ACTIVE)
        except ImportError as e:                              # an import the activation needs failed past the gates: named, exit 3
            sys.stderr.write(f"[chai1-opt] NOT ACTIVE: reason=core_missing:{getattr(e, 'name', None) or e} ({e})\n"); sys.stderr.flush()
            sys.exit(EXIT_NOT_ACTIVE)


def install(environ=None):
    """Install the finder for CHAI1_OPT (idempotent). Returns the finder, or None when nothing is to be done."""
    environ = os.environ if environ is None else environ
    bad = undeclared(environ)
    if bad:
        sys.stderr.write(f"[chai1-opt] NOT ACTIVE: undeclared variable(s) {', '.join(bad)} (this package reads {', '.join(DECLARED_ENV + DECLARED_BIG_ENV)})\n"); sys.stderr.flush()
        sys.exit(EXIT_NOT_ACTIVE)
    mode = (environ.get(ENV) or "").strip().lower()
    if not mode or mode == "off":
        return None
    if mode not in MODES:
        sys.stderr.write(f"[chai1-opt] NOT ACTIVE: unknown {ENV}={mode!r} (expected {'|'.join(MODES)}|off)\n"); sys.stderr.flush()
        sys.exit(EXIT_NOT_ACTIVE)                        # never print-and-return: stock would run silently under the variable
    for f in sys.meta_path:
        if isinstance(f, Finder):
            return f
    f = Finder(mode)
    sys.meta_path.insert(0, f)
    return f


try:
    install()
except SystemExit as _e:                                # from the .pth context site.py would turn SystemExit into a start-up error (exit 1):
    sys.stderr.flush(); os._exit(_e.code if isinstance(_e.code, int) else EXIT_NOT_ACTIVE)   # the interpreter exits EXIT_NOT_ACTIVE itself
