# source this: FlashPairformer v0 environment for the STOCK `protenix pred` CLI (Protenix 2.0.0, production config). ARM=E (exact, default) or ARM=T (Tier-2).
export FPF_HOME="${FPF_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
_fpf_arm="${ARM:-E}"
_fpf_add=$FPF_HOME/levers_addon/PTXV2_LEVERS_ADDON_v1                                     # v0.3 hygiene: temporaries are _fpf_-prefixed and unset at the end; ARM and DEADSKIP are read, never exported
export LAYERNORM_TYPE=${LAYERNORM_TYPE:-fast_layernorm}
export PYTHONPATH=$FPF_HOME/src:$FPF_HOME/third_party:$_fpf_add${PYTHONPATH:+:$PYTHONPATH}:$FPF_HOME/third_party/blockfuse_addon     # src FIRST: its sitecustomize applies the levers and chain-loads the levers add-on shim, and it carries the kit's graph machinery (infopt_graphs, HAZARD44-guarded; dit_hoist) — the kit's copy is the one every import resolves to; then the vendored third_party packages, the add-on, the caller's own PYTHONPATH, the blockfuse add-on
export CUEQ_TRITON_CACHE_DIR=$_fpf_add/cueq_cache PTX_TEMPL_DEDUPE=1                            # levers add-on: L1 kit-generated cuEq TriMul autotune cache (pure lookup; exact) + L2 template distinct-eval (exact)
export PTX_T1_TRANS=fused PTX_NOMASK=1 PTX_BLK=2 PTX_PWA_ZCACHE=1 PTX_BLK_CHUNKED=${PTX_BLK_CHUNKED:-1}                          # ARM E: BLK2 block path (Fusion prologue v3 + cuEq + epilogue v4 + transition v2.2 fn_residual), exact
export PTX_TRANSITION="${PTX_TRANSITION:-$([ "$_fpf_arm" = "T" ] && echo fast || echo exact)}"                     # levers transition_core_exact (ARM E: word exact) | transition_core (ARM T: word fast; a big mode pre-sets big): every Transition call + the block statement's in-block pair transition through opt_core.kernels.transition by the mode's TIER WORD (src/ptx_transition_core.py); a call the provider hands back runs T1's forward by name
unset PTX_BLK_ATT FPF_OPS PTX_TRIMUL
if [ "$_fpf_arm" = "T" ]; then                                                                   # ARM T: + K2B flash tri-attention (raw kernel in the block core) + partner TriMul v1 (triton contraction, c_z==256 guard)
  [ "$PTX_BLK_CHUNKED" = "1" ] && export PTX_BLK_CHUNKED=k2b                                   # v0.3.1 ARM T: chunked core = K2B over all rows (Tier-2; L3b r2r 6/6 @1493); set PTX_BLK_CHUNKED=mirror to keep the exact chunked core under T
  export PTX_BLK_ATT=k2b PTX_T_MIN_TOKENS=${PTX_T_MIN_TOKENS:-300}   # v0.3: ONE size gate (default 300): below it the block path is the exact E path (attention); protenix_opt 0.3.51: the TriMul has no kit crossover — the shared core's cells decide per call (PTX_TRIMUL=tier below)
  case "${PTX_T_ATT:-k2b}" in           # ARM T above-gate tri-attention: fast | big = THE TIER WORD handed to the shared core's provider opt_core.kernels.triattn (lever triattn_native, src/ptx_native_core.py: no row preference, no kit floor, no alias words; the kit README rows of cc 9.0 and cc 8.0 pre-export PTX_T_ATT=fast, big exports PTX_T_ATT=big) | k2b (the K2B Triton kernel by its row word: the default a card the provider has no cell for keeps); the size gate below PTX_T_MIN_TOKENS composes around either unchanged
    k2b) : ;;
    fast|big) export PTX_BLK_ATT=ptx_native_core:attn PTX_BLK_ATT_PROVIDER_MIN_TOKENS=0 ;;   # lever triattn_native: src/ptx_native_core.py hands PTX_T_ATT (the mode's tier word) to opt_core.kernels.triattn in the provider slot at every size the statement hands it (min 0: the provider's cells own the size split); a row that refuses a call by name is served by the row the provider names instead, counted
    *) echo "[FPF env.sh] unknown PTX_T_ATT=${PTX_T_ATT}: fast | big | k2b" >&2; return 2 2>/dev/null || exit 2 ;;
  esac
  export FPF_SMALLN=1 FPF_SMALLN_TRIMUL_EXACT_BELOW=$PTX_T_MIN_TOKENS FPF_SMALLN_K2B_MIN_TOKENS=$PTX_T_MIN_TOKENS   # router = third_party/fpf_smalln: the ARM T size gate BY NUMBER (attention: K2B / the provider slot -> the exact statement below it; TriMul: the exact tier below it, the kit mode's tier at/above)
  export PTX_TRIMUL=tier FPF_SMALLN_TRIMUL_EXACT_FN=ptx_trimul_routes:trimul_exact_c256 FPF_SMALLN_TRIMUL_FAST_FN=ptx_trimul_routes:trimul_c256   # protenix_opt 0.3.51 (lever trimul_core, TOLERANCE): the pair-stack TriMul (c_z 256) = the shared core's ONE provider by TIER word (src/ptx_trimul_routes.py over opt_core.kernels.trimul): below the gate by_word(weights_of, 'exact'), at/above by_word(weights_of, fast | big after PROTENIX_OPT) — the fastest measured row of the call's cell on this card; the kit carries no TriMul kernel and pins no row
  export FPF_OPS="trimul_out=fpf_smalln:trimul_c256,trimul_in=fpf_smalln:trimul_c256"
fi
export PTX_KEEP_POOL=1        # v0.6.2 lever keep_pool (exact class, allocator policy, both arms): stock's empty_cache() calls inside the model forward (confidence head) are no-ops; kit releases and the per-item runner release pass through
export PTX_SUMMARY_HOST=1     # v0.6.2 lever summary_hostidx (exact-bitwise, both arms): summary-confidence chain / chain-pair bookkeeping from one host copy of the id rows; identical GPU value ops, ~2500 -> ~10 stream syncs per item
if [ "${DEADSKIP:-1}" != "0" ]; then export PTX_DEADSKIP=$FPF_HOME/src/deadskip_manifest.json; else unset PTX_DEADSKIP; fi   # v0.1: ON by default (tested byte-identical e2e incl. confidence JSON; DEADSKIP=0 to disable)
export PTX_LEVER_REPORT=${PTX_LEVER_REPORT:-${XDG_CACHE_HOME:-$HOME/.cache}/protenix_v2_opt/fpf_lever_report.jsonl}   # the levers' end-of-run report (JSON lines, appended and read back): a file under the user's own cache directory unless the caller names one (the package's pred verb names one in the run's records) — never a fixed name in the shared /tmp; the directory is made private (0700) by the Python side before anything is appended

#  PTX_BLK_CHUNKED=1|mirror|unchunked|k2b|0 : (default 1 under ARM=E, k2b under ARM=T) chunk-aware BLK2 tri-attention core for N_token > 1024 (stock passes chunk_size 512/256): EXACT per-row-chunk cuEq + in-place epilogue (L2b CLI DET 6/6 @1493, L4 op/full-block 24/24+12/12); 0 = v0.3 behaviour (stock block above 1024)
#  INFOPT_FASTLN_PREBUILT=<dir> : stream-correct fast-LN prebuilt for YOUR torch (a pre-set value is honoured; when unset env.sh auto-selects third_party/fastln_prebuilt (torch 2.7.1+cu126) or third_party/fastln_prebuilt_cu130 (torch 2.13.0+cu130) by the installed torch version; any other torch -> unset). On torch != 2.7.1 without it the LN is source-rebuilt per process (~100 s nvcc; outputs identical). IMG_B ships /opt/fastln_prebuilt.
#  PTX_BLK_ATT=<module>:<attr> : (ARM=T only) generic Tier-2 tri-attention provider fn(q5,k5,v5,bias4,mask=None,scale=) in the cuEq layout, served at N >= PTX_BLK_ATT_PROVIDER_MIN_TOKENS (default 512; K2B below, cuEq if K2B absent); printed; fpf_smalln's <300 exact gate still wraps it
#  PTX_LAZY_INIT=1|recheck : (default-off) skip the dead random init of the 464 M parameters during model CONSTRUCTION (13 init fns no-op'd, restored after; checkpoint load strict=True
#                         overwrites everything) — src/ptx_lazy_init: shortens model construction and process start; steady-state s/pred unchanged;
#                         'recheck' constructs twice and prints 'RECHECK ... N/N tensors sha256-identical -> IDENTICAL' (run once per image/checkpoint). EXACT by construction.
#  PTX_MK_PF=F1|F1E|F1S|F1,F3 : (default-off) MK-PF fused LN-in-registers tri-att prologue (F1 start/end/padded) and transition (F3, cc 10.0 only) — opt_core kernels/fpf_mkpf; cells keyed (cc|triton):
#                         10.0|3.7 F1 both + F3 = EXACT (welford arith, FMA 111 load-bearing); 9.0|3.7 F1 both = EXACT; 9.0|3.3 (pinned stack) F1 END = TIER-2 two-pass, OPT-IN only, honours PTX_T_MIN_TOKENS; welford is
#                         unavailable on triton 3.3.1 (compile >420 s/variant, MK-PF HAZARD 1). Never set FPF_MKPF_ALLOW_TRITON in an exact arm. Set AFTER sourcing env.sh, together with PTX_GLUE_V2=1.
#  PTX_TRIMUL=exact|tier : (exported BY env.sh: exact under ARM E, tier under ARM T) the pair-stack TriMul (c_z 256) through the shared core's ONE provider by TIER word (src/ptx_trimul_routes.py; levers trimul_core_exact / trimul_core); MODEL_OPT_LEVERS_OFF=trimul_core[_exact] removes the word (the stock forward serves)
#  FPF_OPS_EXTRA=<op>=<module>:<attr>[,...] : extra registry ops merged AFTER the arm's FPF_OPS (env.sh unsets/replaces a pre-set FPF_OPS; use this instead). ops: outer_product_mean, msa_pair_weighted_avg, transition, triatt_start/end, trimul_out/in
#  PTX_BLK_PADDED=8 / PTX_BLK_PADDED_ASSERT=1 : (ARM=T) padded-layout provider core (zeroed shared per-P buffers) / debug isfinite+zero check of K/V pad slices before every provider call
#  PTX_SM100F_GUARD=0|1 : (ARM=E) exactness guard for cu13 cuEquivariance on cc 10.x: default auto (stock bool mask passed at N%8==0 when exposed; printed); 0 = never (UNSAFE on cu13+B200), 1 = force
#  PTX_K2B_MAXNREG=N  : (ARM=T) override the K2B ptxas register cap (default: the K2B package's K2B_CELLS.json via its loader, cc-keyed; entry printed)
#  PTX_T_MAX_TOKENS=N : (ARM=T only, default 0 = off) above N tokens both Tier-2 kernels (K2B, triton TriMul) route to the exact E sub-paths; without it a one-time '[FPF] ARM=T: N=... above op-tested max 1775 — UNVERIFIED-AT-N' line is printed
# ---- more levers. DEFAULT-ON: PTX_TRIMUL=exact (ARM=E), PTX_BLK_GRAPH (both arms), FPF_SMALLN routing (ARM=T). DEFAULT-OFF: PTX_V02_TMPL, PTX_V02_MSABLK ----
#  PTX_BLK_GRAPH=1    : fpf_stackgraph layer G (CUDA-graph replay of the 48-block stack for N_token <= PTX_BLK_GRAPH_MAXTOK=448 [host-bound class; no gain above ~250 tok];
#                       live graphs within the PTX_BLK_GRAPH_MEM_GB budget (beyond it a signature runs eager, counted); needs third_party/fastln_prebuilt; EXACT. A signature is armed after its capture replays equal
#                       to the eager call it was captured from; a signature whose replay differs runs eager for the rest of the process (counted).
#  PTX_V02_MSABLK=1   : MSA-module pair stack on the block path (fp32 master z; EXACT by construction)         PTX_V02_TMPL=1 : template c=64 stack transposes removed
#  PTX_T_MIN_TOKENS=N : ARM=T size gate = fpf_smalln's attention threshold (K2B / the provider slot off below N tokens -> the exact statement there; Tier-2 kernels at/above); the TriMul is the core's tier row at every N > 100
if [ "$_fpf_arm" = "E" ]; then         # lever trimul_core_exact (EXACT): the pair-stack TriMul (c_z 256) = the shared core's ONE provider by the TIER word exact — opt_core.kernels.trimul by_word(weights_of, 'exact'): native_exact where its bytes are vouched on this stack, the row the table names elsewhere (tx_sm90a_exact / tmk3_exact / the library op BY NAME beyond the vouched envelope); bitwise == --mode off by the table's class record; src/ptx_trimul_routes.py; no kit TriMul kernel
  export PTX_TRIMUL=exact FPF_OPS="trimul_out=ptx_trimul_routes:trimul_out,trimul_in=ptx_trimul_routes:trimul_in"
fi
if [ "${PTX_BLK_GRAPH:-1}" != "0" ]; then export PTX_BLK_GRAPH=1; else unset PTX_BLK_GRAPH; fi
# memory-budgeted trunk-graph cache is the DEFAULT (PTX_BLK_GRAPH_MEM_GB to set the budget; PTX_BLK_GRAPH_MAX=<number> restores a fixed live-graph count)
export PTX_BLK_GRAPH_MAX=${PTX_BLK_GRAPH_MAX:-auto}
# sampler levers (CUDA-graphed diffusion loop + step-invariant hoist; EXACT) in the CLI path, DEFAULT ON up to 995 tok (eager sampler above);
# also on under PTX_DET=1 (the detref scatter is stateless and CUDA-graph-safe). PTX_SAMPLER_GRAPH=0 disables; modules from src/ (infopt_graphs, dit_hoist).
export PTX_SAMPLER_GRAPH=${PTX_SAMPLER_GRAPH:-1} PTX_SAMPLER_HOIST=${PTX_SAMPLER_HOIST:-1} PTX_SAMPLER_GRAPH_MAXTOK=${PTX_SAMPLER_GRAPH_MAXTOK:-995} PTX_SAMPLER_PREP=${PTX_SAMPLER_PREP:-1} PTX_SAMPLER_REACH=${PTX_SAMPLER_REACH:-1}   # v0.6.2 lever sampler_prep: the graphed sampler's host path (pinned rotation upload, shape key + value check, one warm-up, poison self-test once per process, static-buffer release + pool chaining, vectorised step scalars) — EXACT-BY-CONSTRUCTION, rides the sampler graph
[ "$PTX_SAMPLER_GRAPH" = "0" ] && unset PTX_SAMPLER_GRAPH PTX_SAMPLER_HOIST PTX_SAMPLER_PREP PTX_SAMPLER_REACH
[ "${PTX_SAMPLER_PREP:-0}" = "1" ] || unset PTX_SAMPLER_REACH                                              # lever sampler_reach rides sampler_prep (the same module): never set without it
# SAFE POLICY for the graphed-sampler cache (HAZARD #44): replaying a sampler graph after other sampler captures
# happened in between faults (illegal memory access) when a (N_token, N_atom) signature RECURS; so the cache holds ONE entry:
# a shape change tears the old graph down and captures fresh, so an older graph is never replayed and a recurrence re-captures (correct; constant-shape
# queues unaffected). Read at install by the kit worker (infopt_graphs) AND by fpf_clisampler. Override only for diagnosis.
export INFOPT_GRAPHS_MAX_ENTRIES=${INFOPT_GRAPHS_MAX_ENTRIES:-1}
# HAZARD #44 guard inside infopt_graphs: INFOPT_GRAPHS_EMPTY_CACHE_GUARD=${INFOPT_GRAPHS_EMPTY_CACHE_GUARD:-1} (empty_cache deferred while >= 2 sampler graphs live;
# ceiling INFOPT_GRAPHS_DEFER_MAX_RESERVED_GB, default 0.60 x device memory -> evict to one graph, then release). With max_entries=1 (default) the guard never defers.
export INFOPT_GRAPHS_EMPTY_CACHE_GUARD=${INFOPT_GRAPHS_EMPTY_CACHE_GUARD:-1}
# compute capability 8.0 — the block statement's GLUE_V2 kernels (prologue_v4 / epilogue_v3) and MK-PF F1 take their 8.0|3.7 cells from the
# SHARED CORE packages' own tables (opt_core kernels/fpf_glue_v2/GLUE_CELLS.json, kernels/fpf_mkpf/MKPF_CELLS.json entry sm80_t37);
# nothing is exported here for them — a caller's own
# FPF_GLUE_CELLS_JSON / FPF_MKPF_CELLS_JSON (the core packages' documented hooks) still wins.
# stream-correct fast-LN PREBUILT auto-select by torch version when the user did not set INFOPT_FASTLN_PREBUILT (infrastructure, not a lever; the loader re-check
# torch version + so-sha + bitwise + side-stream + graph replay in every process and refuses otherwise -> stackgraph source-rebuilds, outputs identical):
if [ -z "${INFOPT_FASTLN_PREBUILT:-}" ]; then
  # probe in an ISOLATED interpreter (-I: no PYTHONPATH/sitecustomize, no user site; metadata only, no torch import), then pick the prebuilt dir whose
  # manifest.json "torch" equals the probed version (self-describing; adding a prebuilt for another torch = dropping a directory in third_party/).
  _fpf_tv=$( (python -I -c "import importlib.metadata as m; print(m.version('torch'))" 2>/dev/null || python3 -I -c "import importlib.metadata as m; print(m.version('torch'))" 2>/dev/null || true) | tail -1 | tr -d "[:space:]")
  for _fpf_pd in "$FPF_HOME"/third_party/fastln_prebuilt*/; do
    [ -f "$_fpf_pd/manifest.json" ] || continue
    _fpf_mt=$(python -I -c "import json,sys; print(json.load(open(sys.argv[1]))['torch'])" "$_fpf_pd/manifest.json" 2>/dev/null | tr -d "[:space:]")
    if [ -n "$_fpf_tv" ] && [ "$_fpf_mt" = "$_fpf_tv" ]; then export INFOPT_FASTLN_PREBUILT="${_fpf_pd%/}"; break; fi
  done
fi
# the template embedder's c = 64 pair stack (2 blocks per distinct template per recycle; TriMul c_z = c_hidden = 64, triangle attention 2 heads x 32)
# through the shared core's providers (src/ptx_c64_routes.py). Lever templ_trimul_tmk3: PTX_TEMPL_TRIMUL=tmk3, both arms — opt_core.kernels.trimul's exact row for the
# call's cell under ARM E (word tmk3 -> tmk3_exact: bitwise == the stock op) and opt_core.kernels.trimul_esm_shapes under ARM T (word esm, lever templ_trimul_esm:
# that provider's line re-tiled for (64, 64), tolerance class, tmk3_exact its by-name fallback); N <= 100 and cells without a row keep the arm's forward by name. Lever templ_triatt_core: PTX_TEMPL_TRIATT=core,
# ARM T only, at N_token >= PTX_T_MIN_TOKENS (the one size gate above: below it these calls keep the library op like the block core keeps the exact path) —
# opt_core.kernels.triattn tier 'fast' (core = the sealed package triattn_native else the prebuilt sm_90a row on cc 9.0, k2b on 8.0; native | sm90a | k2b pin that one row);
# ARM E keeps triattn_exact on these calls. The module rides the registry's trimul ops: its two entries FOLLOW the arm's own (the registry binds the later entry of an op)
# and hand every c = 256 call to the arm's provider named before them, unchanged; FPF_OPS_EXTRA still merges last. PTX_TEMPL_TRIMUL=0|off / PTX_TEMPL_TRIATT=0|off leave
# that lever out (the switch unset).
if [ "$_fpf_arm" = "T" ]; then _c64_tm=esm; else _c64_tm=tmk3; fi            # ARM T: the shared core's trimul_esm_shapes line re-tiled for (64, 64) (tolerance; tmk3_exact its by-name fallback); ARM E: the exact row tmk3_exact
case "${PTX_TEMPL_TRIMUL:-$_c64_tm}" in 0|off) unset PTX_TEMPL_TRIMUL ;; tmk3|esm) export PTX_TEMPL_TRIMUL="${PTX_TEMPL_TRIMUL:-$_c64_tm}" ;; *) echo "[FPF env.sh] unknown PTX_TEMPL_TRIMUL=${PTX_TEMPL_TRIMUL}: tmk3 | esm | 0 -> $_c64_tm" >&2; export PTX_TEMPL_TRIMUL=$_c64_tm ;; esac; unset _c64_tm
if [ "$_fpf_arm" = "T" ]; then case "${PTX_TEMPL_TRIATT:-core}" in 0|off) unset PTX_TEMPL_TRIATT ;; core|native|sm90a|k2b) export PTX_TEMPL_TRIATT="${PTX_TEMPL_TRIATT:-core}" ;; *) echo "[FPF env.sh] PTX_TEMPL_TRIATT=${PTX_TEMPL_TRIATT}: unknown word (core | native | sm90a | k2b | 0) -> core" >&2; export PTX_TEMPL_TRIATT=core ;; esac; else unset PTX_TEMPL_TRIATT; fi   # a word left from an ARM T sourcing never reaches ARM E
if [ -n "${PTX_TEMPL_TRIMUL:-}${PTX_TEMPL_TRIATT:-}" ]; then export FPF_OPS="${FPF_OPS:+$FPF_OPS,}trimul_out=ptx_c64_routes:trimul_out,trimul_in=ptx_c64_routes:trimul_in"; fi
if [ -n "${FPF_OPS_EXTRA:-}" ]; then export FPF_OPS="${FPF_OPS:+$FPF_OPS,}${FPF_OPS_EXTRA}"; fi   # v0.5-dev: registry ops from other tracks (e.g. FPF_OPS_EXTRA=outer_product_mean=<mod>:<fn>,msa_pair_weighted_avg=<mod>:<fn>) MERGE after the arm's own trimul entries; a duplicate op name = last one wins (fpf registry); exactness is the provider's claim
_fpf_tm=cueq+L1; case "${FPF_OPS:-}" in *ptx_trimul_routes*) _fpf_tm="core:${PTX_TRIMUL:-?}";; *fpf_smalln*) _fpf_tm="core:${PTX_TRIMUL:-?}(smalln_att_gate<${PTX_T_MIN_TOKENS:-0})";; esac   # protenix_opt 0.3.51: the pair-stack TriMul word (opt_core.kernels.trimul by tier word; the row is the provider's per cell, printed on [ptx_trimul_routes] FIRST / LEVER lines)
# ---- XL token policy (default ON; PTX_FPF_XL=0 switches the XL degradations off). All degradations are exact stock statements keyed on N_token:
#      PTX_FPF_CHUNK_TOK (auto: lean stock-chunked tri-attention above the per-device threshold, rule 4.0+45.0*(N/1981)^2 GB <= 0.85*card), PTX_XL_PAD8_MAX_TOK (auto: PAD8 off above it),
#      PTX_BLK_GRAPH_MEM_GB (auto: trunk-graph private pools <= 30 % of device memory; above budget a length runs eager, logged; reconciled with PTX_BLK_GRAPH_MAX=auto in one admission function),
#      allocator PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True unless already set or PTX_FPF_XL_ALLOC=0 (allocator policy only — no numeric effect). Ledger: '[FPF] XLMEM ...' at exit + report()["xl"].
if [ "${PTX_FPF_XL:-1}" != "0" ]; then
  export PTX_FPF_XL=1 PTX_FPF_CHUNK_TOK=${PTX_FPF_CHUNK_TOK:-auto} PTX_XL_PAD8_MAX_TOK=${PTX_XL_PAD8_MAX_TOK:-auto} PTX_BLK_GRAPH_MEM_GB=${PTX_BLK_GRAPH_MEM_GB:-auto}
  export PTX_FPF_CHUNK_MODE=${PTX_FPF_CHUNK_MODE:-prologue} PTX_BLOCKFUSE_XL=${PTX_BLOCKFUSE_XL:-1}   # v0.6.1: lean mode = per-chunk prologue (XL v3.1) + BlockFuse bias_ln statement (EXACT welford F1 cells only; refuses elsewhere -> bundle statement); both inert at N_token <= PTX_FPF_CHUNK_TOK
  if [ -z "${PYTORCH_CUDA_ALLOC_CONF:-}" ] && [ "${PTX_FPF_XL_ALLOC:-1}" != "0" ]; then export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True; fi
else unset PTX_FPF_XL; fi
echo "KIT_SPEC kit=FLASHPAIRFORMER_v0.6.3 arm=$_fpf_arm levers: BLK2 T1=$PTX_T1_TRANS transition=$PTX_TRANSITION NM=$PTX_NOMASK PWAZ=$PTX_PWA_ZCACHE att=${PTX_BLK_ATT:-cueq} keep_pool=${PTX_KEEP_POOL:-0} summary_host=${PTX_SUMMARY_HOST:-0} trimul=$_fpf_tm graph=${PTX_BLK_GRAPH:-0} graph_max=${PTX_BLK_GRAPH_MAX:-8} graph_mem=${PTX_BLK_GRAPH_MEM_GB:-unset} xl=$( [ -n "${PTX_FPF_XL:-}" ] && echo "on(chunk=$PTX_FPF_CHUNK_TOK,mode=${PTX_FPF_CHUNK_MODE:-stock},blockfuse=${PTX_BLOCKFUSE_XL:-0},pad8max=$PTX_XL_PAD8_MAX_TOK,alloc=${PYTORCH_CUDA_ALLOC_CONF:-default})" || echo off ) sampler_cache=${INFOPT_GRAPHS_MAX_ENTRIES:-8}(guard=${INFOPT_GRAPHS_EMPTY_CACHE_GUARD:-1}) sampler=$( [ -n "${PTX_SAMPLER_GRAPH:-}" ] && echo "graph${PTX_SAMPLER_HOIST:++hoist}<=${PTX_SAMPLER_GRAPH_MAXTOK:-all}tok(refused-under-PTX_DET)" || echo stock ) mkpf=${PTX_MK_PF:-off} trimul_exact_nmax=${FPF_TRIMUL_EXACT_NMAX:-1536} torch=${_fpf_tv:-n/a} fastln_prebuilt=${INFOPT_FASTLN_PREBUILT:-unset} glue2=${PTX_GLUE_V2:-0} pad8=${PTX_E_PAD8:-0} chunked=${PTX_BLK_CHUNKED:-0} tmpl_strided=${PTX_V02_TMPL:-0} t_min_tokens=${PTX_T_MIN_TOKENS:-0} deadskip=${PTX_DEADSKIP:+on}${PTX_DEADSKIP:-off} graph_max=${PTX_BLK_GRAPH_MAX:-8} graph_mem_gb=${PTX_BLK_GRAPH_MEM_GB:-auto25%} sampler_graph=${PTX_SAMPLER_GRAPH:-0} sampler_hoist=${PTX_SAMPLER_HOIST:-0} | all levers: blk=${PTX_BLK:-} chunked=${PTX_BLK_CHUNKED:-} padded=${PTX_BLK_PADDED:-0} pad8=${PTX_E_PAD8:-0}(min=${PTX_E_PAD8_MIN_TOKENS:-}) glue_v2=${PTX_GLUE_V2:-0} deadskip=$( [ -n "${PTX_DEADSKIP:-}" ] && echo on || echo off ) msablk=${PTX_V02_MSABLK:-0} tmpl=${PTX_V02_TMPL:-0} tmpl_dedupe=${PTX_TEMPL_DEDUPE:-0} fpf_ops=${FPF_OPS:-} smalln=${FPF_SMALLN:-0} t_trimul=${PTX_T_TRIMUL:-} tmin=${PTX_T_MIN_TOKENS:-} tmax=${PTX_T_MAX_TOKENS:-} trimul_exact_nmax=${FPF_TRIMUL_EXACT_NMAX:-} lazy_init=${PTX_LAZY_INIT:-0} sampler_hoist=${PTX_SAMPLER_HOIST:-0} sampler_maxtok=${PTX_SAMPLER_GRAPH_MAXTOK:-} graphs_cache=${INFOPT_GRAPHS_MAX_ENTRIES:-} ec_guard=${INFOPT_GRAPHS_EMPTY_CACHE_GUARD:-} sm100f_guard=${PTX_SM100F_GUARD:-} det=${PTX_DET:-0} ln=${LAYERNORM_TYPE:-} prebuilt=$( [ -n \"${INFOPT_FASTLN_PREBUILT:-}\" ] && basename \"$INFOPT_FASTLN_PREBUILT\" || echo none ) alloc=${PYTORCH_CUDA_ALLOC_CONF:-default}"
unset _fpf_add _fpf_arm _fpf_tm _fpf_cc _fpf_tv _fpf_pd _fpf_mt
