"""The autoload hook-live gate (RF-6, D77/D77.2): on the ENV route — ``ESMFOLD2_OPT=<mode>`` set to a mode other than ``off`` and no
``--mode`` on the command line (the stock CLI under the variable) — run.sh refuses by name unless the kit's hook is LIVE in a fresh
interpreter: ``python -c`` (the route's own form: PYTHONPATH and the user site as the route sees them, the kit's variables stripped) reports ``esmfold2_opt._autoload`` in ``sys.modules`` at start, the EFFECT of the site-processed
``esmfold2_opt_autoload.pth`` (opt/_build_backend.py ships it at the wheel root). With the package merely importable (PYTHONPATH, no
install) the env route would run STOCK silently. The refusal line names the DIAGNOSTIC from a file search over the interpreter's site
directories and sys.path: present in a site directory but not processed / present beside a non-site path (a .pth is executed only from a
site directory) / a stale copy (content differs from the shipped text, opt/esmfold2_opt_autoload.pth) / absent from the searched sites. The ``--mode`` route is not
gated: run.sh passes the mode to the package, which activates in-process by construction (its ACTIVE line is the evidence).
"""
import os
import site
import subprocess
import sys
import sysconfig

PTH_NAME = "esmfold2_opt_autoload.pth"       # the one file beside opt/pyproject.toml (tests/test_startup.py PTH; opt/_build_backend.py ships it at the wheel root)
PTH_SOURCE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), PTH_NAME)   # the shipped text: generated by opt/_build_backend.py (the guarded `import esmfold2_opt._autoload`), never hand-written


def pth_text() -> str:
    """The shipped .pth text (the tree's own file beside opt/pyproject.toml), stripped — what a live site copy must equal."""
    with open(PTH_SOURCE, encoding="utf-8") as fh:
        return fh.read().strip()


HOOK_MODULE = "esmfold2_opt._autoload"
EXIT_NOT_ACTIVE = 3                          # report.EXIT_NOT_ACTIVE (import-free here: this module runs before anything else of the kit)
PROBE = f"import sys; sys.exit(0 if {HOOK_MODULE!r} in sys.modules else 1)"


def site_dirs():
    """The directories this interpreter processes .pth files from (site.py: the venv / system site-packages, the user site)."""
    out = []
    for d in list(site.getsitepackages() if hasattr(site, "getsitepackages") else []) + [site.getusersitepackages() if hasattr(site, "getusersitepackages") else None, sysconfig.get_paths().get("purelib")]:
        if d and d not in out:
            out.append(d)
    return out


def hook_live(python: str = sys.executable) -> bool:
    """Whether a FRESH interpreter of the route's own form (``python -c``: PYTHONPATH and the user site as the route's interpreter sees
    them — a user-site install, ``pip install --user`` / PYTHONUSERBASE, is processed when the user site is enabled) holds the hook module
    at start — the .pth's effect; a copy on PYTHONPATH still reads not-processed (site.py executes no .pth outside a site directory).
    The kit's own variables are stripped from the probe's environment: the probe asks whether the hook is there, not what it would select."""
    env = {k: v for k, v in os.environ.items() if not k.startswith("ESMFOLD2_")}
    r = subprocess.run([python, "-c", PROBE], env=env, capture_output=True, text=True)
    return r.returncode == 0


def diagnose() -> str:
    """Why the hook is not live, from a file search: the .pth in a site directory (present but not processed: a stale copy / a -S start),
    beside a non-site sys.path entry (never processed there), or absent."""
    sites = site_dirs()
    user_site = site.getusersitepackages() if hasattr(site, "getusersitepackages") else None
    for d in sites:
        p = os.path.join(d, PTH_NAME)
        if os.path.isfile(p):
            content = open(p, encoding="utf-8", errors="replace").read().strip()
            if content != pth_text():
                return f"a stale copy at {p} (content {content[:60]!r}, expected the text of {PTH_SOURCE})"
            if d == user_site and not site.ENABLE_USER_SITE:
                return f"{PTH_NAME} is present in the user site {d} but the user site is disabled for this interpreter (a venv without system site-packages, PYTHONNOUSERSITE, or -s): not processed"
            return f"{PTH_NAME} is present in the site directory {d} but not processed at interpreter start (a site-less start, or another interpreter's site)"
    for d in sys.path:
        p = os.path.join(d or os.getcwd(), PTH_NAME)
        if os.path.isfile(p):
            return f"{PTH_NAME} is present at {p} but not processed: a .pth is executed only from a site directory (PYTHONPATH is not one)"
    return f"{PTH_NAME} is absent from the searched sites {sites}"


def refusal_line(interpreter: str, opt_dir: str) -> str:
    return (f"[esmfold2-opt] NOT ACTIVE: the autoload hook {HOOK_MODULE} is not live at the start of {interpreter} ({sys.prefix}) — the env route "
            f"(ESMFOLD2_OPT=<mode> under the stock CLI) would run STOCK silently; diagnostic: {diagnose()}; install the kit into this interpreter: pip install -e {opt_dir}")


def main(argv=None) -> int:
    if hook_live():
        return 0
    opt_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.stderr.write(refusal_line(sys.executable, opt_dir) + "\n"); sys.stderr.flush()
    return EXIT_NOT_ACTIVE


if __name__ == "__main__":
    raise SystemExit(main())
