"""ptx_addon_levers.py — the levers add-on: EXACT execution levers for Protenix v2 (2.0.0 @ 2475421) inference.

Import this module (or put the accompanying sitecustomize.py on PYTHONPATH) BEFORE protenix builds its model. Every lever is env-gated and
defaults to stock bytes:

  PTX_TEMPL_DEDUPE=1      Template-embedder dummy-template dedupe. With use_template=False, the featurizer emits 4 IDENTICAL
                          dummy templates and TemplateEmbedder.forward runs its 2-block Pairformer once per template per recycle (4 × 10 per
                          prediction). single_template_forward is computed once and accumulated num_templates times in the stock order
                          u = (((0 + t) + t) + t) + t, which is bitwise identical to the stock loop whenever single_template_forward is
                          run-to-run deterministic in-process (checked per process on the first call: mode PTX_TEMPL_DEDUPE=recheck computes
                          both and compares torch.equal; stats in LEVER_STATS). Identity of the template slices is checked on device once per
                          feature dict (all template_* features equal across the template axis); otherwise the stock path runs.
  CUEQ_TRITON_CACHE_DIR   (no code — cuequivariance_ops reads it) the kit's TriMul autotune cache cueq_cache/ (its README.md):
                          fused_sigmoid_gated_dual_gemm_forward_kernel_wrapper.<cc>.json, generated by running the library's own autotuner
                          on our cards for the large-M trimul GEMM keys where the tile choice matters (N=512/K=256 and N=256/K=256
                          Pairformer/MSA/confidence at M = 262,144 / 40,448 …; kit-generated data, no NVIDIA SDK data); keys not in the
                          table (incl. the template embedder's N=128/K=64 and N=64/K=64) run the kernel's built-in default tiles. With
                          CUEQ_TRITON_TUNING unset the cache is a pure lookup: same Triton kernel, different BLOCK tiles → identical
                          arithmetic per output element (K-reduction order inside one program is sequential over BLOCK_K chunks; tested
                          bitwise per size in trunklever_compare.json).
  PTX_LEVER_LOG=path      append one JSON line with LEVER_STATS at interpreter exit.

D59b: nothing here keys on a process-global numerics mode; the dedupe decision is per feature dict, the cuEq cache is per (M-bucket,N,K,dtype).
"""
import atexit
import sys, json, os
import torch

LEVER_STATS = {"templ_dedupe": {"mode": os.environ.get("PTX_TEMPL_DEDUPE", "0"), "calls": 0, "deduped": 0, "stock_path": 0,
                                "verify_ok": 0, "verify_fail": 0, "verify_maxabs": []},
               "cueq_cache_dir": os.environ.get("CUEQ_TRITON_CACHE_DIR"), "cueq_tuning": os.environ.get("CUEQ_TRITON_TUNING")}

_TEMPLATE_KEYS = ("template_aatype", "template_distogram", "template_pseudo_beta_mask", "template_unit_vector", "template_backbone_frame_mask")


def _template_groups(feat):
    """Map each template index to the index of the FIRST template whose template_* features are all bitwise identical to it.
    Returns a list rep[t] (rep[t] <= t). Computed once per feature dict (device compare), cached in the dict."""
    c = feat.get("_ptx_templ_groups")
    if c is not None:
        return c
    n = int(feat["template_aatype"].shape[0])
    rep = list(range(n))
    for t in range(1, n):
        for r in range(t):
            if rep[r] != r:
                continue
            same = True
            for k in _TEMPLATE_KEYS:
                x = feat.get(k)
                if x is None or not bool(torch.equal(x[t], x[r])):
                    same = False
                    break
            if same:
                rep[t] = r
                break
    feat["_ptx_templ_groups"] = rep
    return rep


def install_template_dedupe(mode):
    import protenix.model.modules.pairformer as PF
    stock_forward = PF.TemplateEmbedder.forward
    ST = LEVER_STATS["templ_dedupe"]

    def forward(self, input_feature_dict, z, pair_mask=None, triangle_attention="torch", triangle_multiplicative="torch",
                inplace_safe=False, chunk_size=None):
        ST["calls"] += 1
        if "template_aatype" not in input_feature_dict or self.n_blocks < 1:
            return 0
        num_templates = input_feature_dict["template_aatype"].shape[0]
        rep = _template_groups(input_feature_dict)
        if num_templates <= 1 or len(set(rep)) == num_templates:
            ST["stock_path"] += 1
            return stock_forward(self, input_feature_dict, z, pair_mask=pair_mask, triangle_attention=triangle_attention,
                                 triangle_multiplicative=triangle_multiplicative, inplace_safe=inplace_safe, chunk_size=chunk_size)
        # --- stock preamble, verbatim semantics (pairformer.py TemplateEmbedder.forward @ 2475421) ---
        asym_id = input_feature_dict["asym_id"]
        multichain_mask = (asym_id[:, None] == asym_id[None, :]).to(z.dtype)
        num_residues = z.shape[0]
        query_num_channels = z.shape[-1]
        if pair_mask is None:
            pair_mask = z.new_ones(z.shape[:-1])
        z = self.layernorm_z(z)
        kw = dict(input_feature_dict=input_feature_dict, z=z, pair_mask=pair_mask, multichain_mask=multichain_mask,
                  triangle_attention=triangle_attention, triangle_multiplicative=triangle_multiplicative,
                  inplace_safe=inplace_safe, chunk_size=chunk_size)
        distinct = {}
        u = 0
        for template_id in range(num_templates):      # same accumulation order and operands as stock; each DISTINCT template evaluated once
            r = rep[template_id]
            if r not in distinct:
                distinct[r] = self.single_template_forward(template_id=r, **kw)
            u = u + distinct[r]
        ST["n_distinct"] = ST.get("n_distinct", 0) + len(distinct); ST["n_templates"] = ST.get("n_templates", 0) + num_templates
        if mode == "recheck":
            u_ref = 0
            for template_id in range(num_templates):
                u_ref = u_ref + self.single_template_forward(template_id=template_id, **kw)
            if torch.equal(u, u_ref):
                ST["verify_ok"] += 1
            else:
                ST["verify_fail"] += 1
                ST["verify_maxabs"].append(float((u.float() - u_ref.float()).abs().max()))
                u = u_ref
        ST["deduped"] += 1
        u = u / (1e-7 + num_templates)
        u = self.linear_no_bias_u(self.relu(u))
        assert u.shape == (num_residues, num_residues, query_num_channels)
        return u

    PF.TemplateEmbedder.forward = forward
    PF.TemplateEmbedder._ptx_stock_forward = stock_forward
    LEVER_STATS["templ_dedupe"]["applied"] = True
    print(f"[ptx_addon_levers] APPLIED template_distinct_eval mode={mode}", file=sys.stderr, flush=True)


def _dump():
    p = os.environ.get("PTX_LEVER_LOG")
    if p:
        try:
            with open(p, "a") as f:
                f.write(json.dumps({"pid": os.getpid(), **LEVER_STATS}) + "\n")
        except Exception:
            pass


_MODE = os.environ.get("PTX_TEMPL_DEDUPE", "0")
if _MODE in ("1", "recheck"):
    install_template_dedupe(_MODE)
atexit.register(_dump)
