"""Lazy autoload, installed at interpreter start by `rfdiffusion1_opt_autoload.pth` (its guarded `import rfdiffusion1_opt._autoload` line, generated by opt/_build_backend.py).

With a kit mode in the environment (RFDIFFUSION1_OPT=exact), the core's meta-path finder (opt_core.autoload) waits for the first import of the
upstream package `rfdiffusion` and, right after its body has executed, calls `rfdiffusion1_opt.enable(<mode>, strict=True,
trigger="rfdiffusion")`. A kit mode of this model is a driver line (the resident process and the graph wrapping live in the driver's
control flow, opt/forward/fast_inference/drivers/rfd_bench.py) and cannot
attach to upstream's one process per invocation — so the package refuses by name: ONE line naming that fact (`[rfdiffusion1-opt] NOT ACTIVE: <FACT>`,
stack.refuse_at_trigger), then ActivationError, on which the finder ends the process with exit 3 before anything of upstream's runs under the mode's
name. `rfdiffusion1-opt design --mode <mode>` is the kit line's route; `RFDIFFUSION1_OPT=off` (or unset) is the stock line's. A value that is not a declared mode word is refused at interpreter start with the core's line and exit 3
(`on_unknown="exit_now"`). Until the trigger nothing else is imported (no torch, no upstream; this module imports the core only when the variable
names a selection, and only past the core pin gate: `install()` runs `_core_gate.gate` first, so an absent, older / newer or edited core is
`[rfdiffusion1-opt] NOT ACTIVE: reason=core_missing:opt_core | core_mismatch: …` and exit 3 at interpreter start, never a raw ImportError); with
RFDIFFUSION1_OPT unset or "off" no finder is installed, no gate runs, and the stock line is untouched. The package's own processes (`design`, the
stock caller) never carry RFDIFFUSION1_OPT into a child that imports `rfdiffusion`: the driver runs under the mode's own environment row and the
stock caller strips the variable (stock/PINS.json must_be_absent_prefixes).
"""
import os
import sys

ENV = "RFDIFFUSION1_OPT"
EXIT_NOT_ACTIVE = 3                                   # report.EXIT_NOT_ACTIVE, repeated here: this module imports nothing of the package at interpreter start (test_cli_outputs_stock locks the two equal)
TAG = "rfdiffusion1-opt"                              # report.TAG, repeated for the same reason (test_cli_outputs_stock locks the two equal)
TRIGGERS = ("rfdiffusion",)
MODES = ("exact", "fast", "off")
FACT = ("mode={mode} cannot serve upstream's own command line (this process imported {trigger} under {env}={mode}): the levers live in the "
        "resident driver's control flow (opt/forward/fast_inference/drivers/rfd_bench.py), not in upstream's one process per invocation — "
        "refused by name (exit 3), nothing ran; the kit line is `rfdiffusion1-opt design --mode {mode} <the same overrides>`, the stock line is {env}=off")


def spec():
    """This kit's AutoloadSpec (the core imported here, never at module level)."""
    from opt_core.autoload import AutoloadSpec
    return AutoloadSpec(env=ENV, package="rfdiffusion1_opt", tag=TAG, triggers=TRIGGERS, modes=MODES, exit_not_active=EXIT_NOT_ACTIVE, on_unknown="exit_now")


def install(environ=None):
    """Install the core's finder for RFDIFFUSION1_OPT (idempotent) past the core pin gate. Returns the finder, or None when nothing is to be
    done (unset / off: no gate, no import)."""
    environ = os.environ if environ is None else environ
    if (environ.get(ENV) or "").strip().lower() in ("", "off"):
        return None
    from ._core_gate import gate
    try:
        gate(__file__, tag=TAG)                       # the core pin gate: before any opt_core import; its NOT ACTIVE line is written and flushed by the gate
    except SystemExit as x:                           # the .pth-time exit is os._exit: site.py runs a .pth line under `except Exception`, where sys.exit would surface as an interpreter start-up failure (status 1) instead of exit 3
        sys.stderr.flush()
        os._exit(x.code if isinstance(x.code, int) else EXIT_NOT_ACTIVE)
    from opt_core.autoload import install as core_install     # the core the gate located, its MANIFEST matching the pin
    return core_install(spec(), environ=environ)


FINDER = install()
