"""The one lever registry: what each lever is, its numerics class, its switch and the kit files it lives in (every path relative to
``opt/forward/``) — descriptive only, the package applies no lever itself (each is applied by its own owner: the base kit's ``FAST=``
row, the Pallas add-on's ``apply_levers()``, FlashPairformer's own import, or ``big_launch.py`` for the memory levers). ``strategy`` is
the lever's shared id in the release tree's cross-engine matrix (``F<family>.<name>``; ``LOCAL.`` = engine-specific; ``None`` =
unassigned) — the same idea on another engine carries the same id, but this tree's implementation stays its own (JAX only)."""
from __future__ import annotations

LEVERS = {
    # the base kit's fast-inference levers (patch 01 = patches/patched_files/run_alphafold.py)
    "L1": {"impl": "host", "name": "featurisation prefetch in worker processes", "kind": "datapath", "numerics": "bitwise", "strategy": "F6.item_ordering_prefetch",
           "switch": "--featurisation_workers / --featurisation_prefetch (the FAST= row of fast_inference/rows.sh)",
           "touches": ["fast_inference/patches/patched_files/run_alphafold.py"], "source": "fast_inference/patches/01_run_alphafold_fast_inference.diff"},
    "WRITER": {"impl": "host", "name": "output writer thread: each fold job's result extraction and output writing behind the next job's inference", "kind": "datapath", "numerics": "bitwise", "strategy": "F6.output_overlap",
               "switch": "--output_writer (the FAST= row of fast_inference/rows.sh)",
               "touches": ["fast_inference/patches/patched_files/run_alphafold.py"], "source": "fast_inference/patches/01_run_alphafold_fast_inference.diff"},
    "FIX1": {"impl": "host", "name": "one-shot tokamax autotune attempt", "kind": "cold-start", "numerics": "none (cold start only)", "strategy": "F3.xla_flags_compile",
             "switch": "none: on whenever run_alphafold_fast.py runs", "touches": ["fast_inference/patches/patched_files/run_alphafold.py"],
             "source": "fast_inference/patches/01_run_alphafold_fast_inference.diff"},
    # the Pallas add-on's Tier-1 kernel levers (installed by apply_levers() through levers_launch.py)
    "GLUT": {"impl": "pallas_triton", "name": "TriangleMultiplication fused transposed+masked GLU Pallas-Triton kernel (L-GLUT)", "kind": "kernel", "numerics": "bitwise", "strategy": None,
             "switch": "AF3P_GLU_T (modes.PALLAS_LEVERS)", "touches": ["pallas_addon/patches/af3_pallas_levers.py"], "kernel": "opt_core.kernels.pallas_glut",
             "source": "pallas_addon/patches/af3_pallas_levers.py (make_patched_trimul_class)"},
    "ATTNCFG": {"impl": "tokamax_config", "name": "pair-attention flash-attention tile pin (L-ATTNCFG)", "kind": "kernel", "numerics": "bitwise (block_k=64, num_warps 4)", "strategy": None,
                "switch": "AF3P_ATTN_CFG (block_q,block_k,warps,stages; modes.PALLAS_LEVERS)", "touches": ["pallas_addon/patches/af3_pallas_levers.py"],
                "source": "pallas_addon/patches/af3_pallas_levers.py (apply_levers)"},
    # the FlashPairformer add-on (flashpairformer/README.md; installed at `import af3_flashpairformer` through its own launcher)
    "FPF_TRIMUL": {"impl": "pallas_triton", "name": "fused Pallas TriangleMultiplication (FlashTriangleMultiplication)", "kind": "kernel", "numerics": "not bitwise (bf16 re-association)", "strategy": "F2.fpf_trimul_fast",
                   "switch": "AF3_FLASHPAIRFORMER (trimul or both)", "touches": ["flashpairformer/af3_flashpairformer/patch.py"], "kernel": "opt_core.kernels.fpf_pallas.trimul_pallas",
                   "source": "flashpairformer/README.md"},
    "FPF_TRIATT": {"impl": "pallas_triton", "name": "fused Pallas triangle attention (FlashGridSelfAttention)", "kind": "kernel", "numerics": "not bitwise (bf16 re-association)", "strategy": "F1.flash_triatt",
                    "switch": "AF3_FLASHPAIRFORMER (triatt or both)", "touches": ["flashpairformer/af3_flashpairformer/patch.py"], "kernel": "opt_core.kernels.fpf_pallas.triattn_pallas",
                    "source": "flashpairformer/README.md"},
    "DATTN": {"impl": "opt_core.kernels.pallas", "name": "dense attention with pair bias (the pairformer's single attention and the diffusion transformer's self-attention) served by the shared core's JAX-family provider opt_core.kernels.pallas (serve.attention, kinds af3_single / af3_dit) named by the mode's TIER word — fast on the fast line, big in the memory mode — the provider's measured winner of each call's cell (PALLAS_CELLS.json; on this stack tokamax's Triton flash attention from the 800-token bucket up and for the diffusion kind throughout, tokamax's XLA path at the single kind's 400-token bucket); which arm served is printed, never assumed (the lever's census line `DATTN word= served= rows= aside= uncovered=`, quoted on its LEVER line and read by the kernels gate)",
              "kind": "kernel", "numerics": "not bitwise (flash re-association; stock forms the logits from f32 q.k)", "strategy": "F5.flash_attn_dense",
              "switch": "AF3_JAX_DATTN=1|big (set by the mode table for a composition that names DATTN: 1 = the tier word fast on the fast line, big in the memory mode (both regions) at n_gpu 1 — modes.tier_word_env; any other value is handed to the provider verbatim as its word, an A/B affordance; opt/af3_jax_opt/inprocess/dattn.py loaded into the model process by fpf_launch.py)",
              "touches": [], "site": "opt/af3_jax_opt/inprocess/dattn.py", "kernel": "opt_core.kernels.pallas (serve.attention; kinds af3_dit | af3_single; rows tokamax[@triton|@xla|@cudnn] | cudnn | xla by the provider's cells)"},
    "TRIATT_XLA": {"impl": "cuda+triton_aot", "name": "triangle attention's core (GridSelfAttention: the trunk, MSA and template stacks, the confidence pairformer) served by the shared core's JAX-family provider opt_core.kernels.pallas (serve.attention, kind tri | tmpl) by the MODE'S TIER WORD — fast under --mode fast, big under --mode big (both regions and under --n_gpu P): the provider's measured cell per head count / head dim / size / compute capability / jax line names the row (its bridge row triattn_xla = opt_core.kernels.triattn_xla's pre-compiled cuda_sm90a / triattn_native / k2b_aot kernels where they measured ahead of the Pallas cores on that card, launched in the tensors' own layout; the Pallas rows rowshared / cd_triatt / pallas_attn / fpf_core, the library rows and the stock statement in the cell's order elsewhere); the kit names no row, no card and no size; inside the FlashPairformer fused block where it serves and in the module's own attention elsewhere; a call the provider does not serve steps aside by name to the kernel that call site had; a row the provider cannot engage steps aside by name to the cell's next row",
                   "kind": "kernel", "numerics": "not bitwise vs FPF_TRIATT / stock: bf16 flash kernels (fp32 online softmax and bias, another accumulation order), max-abs ~0.008 vs fp32 at 1,216 tokens = the Pallas kernel's class; deterministic", "strategy": "F1.flash_triatt",
                   "switch": "AF3_JAX_TRIATT_XLA=<provider word> (set by the mode table for a composition that names TRIATT_XLA: 1 = fast under fast, big under big — modes.TIER_WORD; a row / arm word names exactly that row for comparisons; opt/af3_jax_opt/inprocess/triatt_xla.py loaded into the model process by fpf_launch.py before the add-on's import)",
                   "touches": [], "kernel": "opt_core.kernels.pallas (serve.attention kind tri | tmpl; bridge row opt_core.kernels.triattn_xla)", "site": "opt/af3_jax_opt/inprocess/triatt_xla.py"},   # binds in af3_flashpairformer/patch.py (fused_with_core) and in the module itself
    "TTR": {"impl": "pallas_triton", "name": "fused pair transition: LayerNorm + SwiGLU + output projection of modules.TransitionBlock in ONE Pallas kernel (the [N, N, 4C] intermediate never reaches HBM) — modules.TransitionBlock rebound",
            "kind": "kernel", "numerics": "not bitwise (the output projection accumulates in f32 tile by tile)", "strategy": "LOCAL.fused_transition",
            "switch": "AF3_JAX_TTR=1 (set by the mode table for a composition that names TTR; opt/af3_jax_opt/inprocess/ttr.py loaded into the model process by fpf_launch.py)",
            "touches": [], "site": "opt/af3_jax_opt/inprocess/ttr.py", "kernel": "opt_core.kernels.fpf_pallas.transition_pallas"},
    "SAMPLER_BF16": {"impl": "jax", "name": "the diffusion sampler's transformer-block GEMMs (DiT q/k/v/gate/output projections, SwiGLU transition, AdaLN and adaptive-zero conditioning projections; the atom transformer encoder/decoder likewise) on bf16 tensor-core operands — f32 residual streams, f32 LayerNorm / softmax statistics and every precision='highest' projection kept, the pair / single conditioning paths (unconditioned transitions) stock f32; diffusion_transformer.adaptive_layernorm / adaptive_zero_init rebound inside diffusion_head.sample's scope (the memory mode's chunked sampler enters the same scope)",
                     "kind": "precision", "numerics": "not bitwise (bf16 operands in the sampler GEMMs; softmax/LN stats, pair-cond and highest-precision sites stay f32)", "strategy": "F4.autocast_policy",
                     "switch": "AF3_JAX_SAMPLER_BF16=1 (set by the mode table for a composition that names SAMPLER_BF16; opt/af3_jax_opt/inprocess/sampler_bf16.py loaded into the model process by fpf_launch.py)",
                     "touches": [], "site": "opt/af3_jax_opt/inprocess/sampler_bf16.py"},
    "ATOM_ATTN": {"impl": "pallas", "name": "the diffusion sampler's atom cross-attention core (AtomCrossAttEncoder/Decoder, 32-query x 128-key windows, 4 heads x 32) through the kit's fused windowed-attention Pallas kernel (Triton backend): f32 logits + stock mask term + pair logits, softmax, P.V in one program per (sample, subset); all-padding query subsets skipped; diffusion_transformer.cross_attention rebound",
                  "kind": "kernel", "numerics": "not bitwise (summation order of the two window products and exp inside the fused kernel; weights and output rounded to the activation dtype as stock; max |delta| vs an f32 reference of stock's own order, bench_atom_attn.py)", "strategy": "F5.gather_attn",
                  "switch": "AF3_JAX_ATOM_ATTN=1 (set by the mode table for a composition that names ATOM_ATTN; opt/af3_jax_opt/inprocess/atom_attn.py loaded into the model process by fpf_launch.py)",
                  "touches": [], "site": "opt/af3_jax_opt/inprocess/atom_attn.py", "kernel": "opt/af3_jax_opt/inprocess/af3_jax_atom_attn_pallas.py (kit-namespaced, core-destined)"},
    "TRIMUL_CD": {"impl": "pallas_triton", "name": "the pair stack's TriangleMultiplication (trunk pairformer, MSA stack, template stack c=64, confidence pairformer; outgoing and incoming) served whole by the shared core's JAX-family provider opt_core.kernels.pallas (serve.triangle_multiplication, form af3) by the MODE'S TIER WORD — fast under --mode fast, big under --mode big (region fast; the reach region's site is TRIMUL_CHUNK's): the provider's measured cell per channel width / equation / size / compute capability / jax line names the row (native_xla | cd_trimul | fpf_trimul | … | the stock statement xla); the kit names no row, no card and no size; a form with no measured cell on the card is served by the provider's declared fallback, printed by the provider as UNCOVERED_CELL and counted as tcd_uncovered=; inside the FlashPairformer fused class where it is installed (the add-on's own block is the provider's row fpf_trimul) and as the module elsewhere; a call the provider does not serve steps aside by name to the arithmetic that call site had",
                  "kind": "kernel", "numerics": "not bitwise (bf16 re-association: fp32 LayerNorm statistics in registers, fewer bf16 rounding points; the provider's cells measure each row's max |d| vs fp32, cd_trimul's equal to FPF_TRIMUL's)", "strategy": "F2.trimul",
                  "switch": "AF3_JAX_TRIMUL_CD=<provider word> (set by the mode table for a composition that names TRIMUL_CD: 1 = fast under fast, big under big in region fast — modes.TIER_WORD; a row / arm word names exactly that row instead, e.g. cd_trimul or fpf_trimul@w4, for comparisons; SERVED tcd_word= says which, tcd_rows= what served; opt/af3_jax_opt/inprocess/trimul_cd.py loaded into the model process by fpf_launch.py before the add-on's import; the memory mode's reach region does not name it: TRIMUL_CHUNK owns the site)",
                  "touches": [], "site": "opt/af3_jax_opt/inprocess/trimul_cd.py", "kernel": "opt_core.kernels.pallas (serve.triangle_multiplication form af3; rows native_xla | cd_trimul | fpf_trimul[@w4|@hi] | xla)",
                  "patches": "alphafold3.model.network.modules.TriangleMultiplication (subclass CdTriangleMultiplication; af3_flashpairformer.patch.FlashTriangleMultiplication inherits trimul_cd_row from it)"},   # binds in af3_flashpairformer/patch.py (FlashTriangleMultiplication.__call__) and in the module itself; 'touches' names no add-on file of its own
    "LNP": {"impl": "pallas_triton", "name": "the model's standalone LayerNorms (haiku_modules.LayerNorm, rebound to a same-name subclass: every hm.LayerNorm site outside the fused pair blocks) served by the shared core's JAX-family provider opt_core.kernels.pallas (serve.layer_norm, named by the provider's TIER word of the mode — fast under fast, big under big: per call the measured winner of the call's cell, row cd_trimul's sibling cd_ln = the carried Pallas row-LayerNorm kernel where its cell measured it ahead, the XLA statement (row xla) elsewhere) at the units whose cells name cd_ln ahead on at least one card: pair ([N, N, 128]: the pairformer's single-attention pair-logits norm, the MSA stack's pair norm, the recycling and template query-embedding norms, the confidence head's pair norms), tmpl ([N, N, 64] template pair activations), msa ([S, N, 64]: outer-product-mean input norm, pair-weighted-averaging act norm); kept on the stock class BY RULE and counted (routed=): adaptive LayerNorms without scale/offset (diffusion / atom transformers, conditioning norms), single (C = 384) and diffusion-transformer (C = 768) norms (no provider row, their cells name the XLA statement), non-last-axis norms, non-square row blocks; --mode exact does not name it (the stock LayerNorm by name: no LayerNorm row is byte-vouched on this stack); off by its switch under --n_gpu P > 1 (the row-sharded recipe owns the pair stack per row block)",
            "kind": "kernel", "numerics": "not bitwise (row cd_ln: f32 statistics in registers, two-pass variance, another summation order; row xla: the provider's statement of the stock formula) — tolerance class, inside fast's identity form", "strategy": "F5.row_layernorm",
            "switch": "AF3_JAX_LNP=<word> (set by the mode table for a composition that names LNP: 1 = the provider tier word fast under --mode fast, big under --mode big (modes.TIER_WORD_SWITCHES); a row word cd_ln | xla names one row instead; opt/af3_jax_opt/inprocess/lnp.py loaded into the model process by fpf_launch.py before the add-on's import; MODEL_OPT_LEVERS_OFF=LNP removes the switch, MODEL_OPT_LEVERS_OFF=pallas:cd_ln makes the provider refuse the row by name)",
            "touches": [], "site": "opt/af3_jax_opt/inprocess/lnp.py", "kernel": "opt_core.kernels.pallas (serve.layer_norm; rows cd_ln | xla)",
            "patches": "alphafold3.model.components.haiku_modules.LayerNorm (same-name subclass installed on the module)"},
    "HOIST_LOGITS": {"impl": "jax", "name": "the hoist's 24 per-block pair logits indexed in place by the diffusion-transformer blocks (layer index as the layer_stacks' per-layer input; one dynamic_index_in_dim of the [24,16,N,N] view per block) instead of f32 logits re-sliced through two nested layer_stack per-layer inputs at every step — the super-block operand copies leave the program, the block slice and the attention core's bias reads halve",
                     "kind": "datapath", "numerics": "byte-identical to fast without it at 448 and 1,216 tokens (the released f32-resident form: value-identical indexing); fast-class because it refines FPF_HOIST; a bf16-resident variant is kept in the module as a non-default (tolerance class)", "strategy": "LOCAL.af3_jax.hoist_logits",
                     "switch": "AF3_JAX_HOIST_LOGITS=1 (set by the mode table for a composition that names HOIST_LOGITS; opt/af3_jax_opt/inprocess/hoist_logits.py loaded into the model process by fpf_launch.py after the add-on import; steps aside by name when FPF_HOIST is ablated or held)",
                     "touches": [], "site": "opt/af3_jax_opt/inprocess/hoist_logits.py"},
    "COND_SHARE": {"impl": "jax", "name": "the diffusion sampler's per-step conditioning computed once per denoising step and shared by the step's samples: diffusion_head.sample with the previous noise level carried as the scan's (unbatched) input instead of in the per-sample vmap carry, so t_hat and everything derived from it alone — the noise embedding, the single-conditioning LayerNorm + projection + transitions on [N, 384], and per block the adaptive-LayerNorm and adaptive-zero conditioning projections (24 blocks x 2) — is traced once per step at M = N instead of once per sample at M = 5N",
                   "kind": "schedule", "numerics": "not bitwise vs fast (the conditioning GEMMs run at M = N instead of 5N: other cuBLAS kernels, ulp-level differences the 200-step sampler carries into an equally-sampled trajectory — FPF_HOIST's class); inside stock's seed-to-seed band with the lever ablated as control", "strategy": "LOCAL.af3_jax.cond_share",
                   "switch": "AF3_JAX_COND_SHARE=1 (set by the mode table for fast and big's region fast; installed FIRST among the tree levers: it replaces diffusion_head.sample, the others wrap it)",
                   "touches": [], "site": "opt/af3_jax_opt/inprocess/cond_share.py"},
    "ATOM_COND_HOIST": {"impl": "jax", "name": "the atom cross-attention encoder's step-invariant conditioning — per-atom single conditioning in queries / keys layout and masks, the atom-pair conditioning (row/col + trunk-pair gather + reference offset / distance / validity embeddings + the 3-layer pair MLP) and both atom transformers' per-block pair logits — computed ONCE per sample call outside the 200-step loop (a diffusion_head.sample wrapper running DiffusionHead in a precompute mode of its own __call__, parameters unchanged) and handed to the rebound atom encoder / decoder as layer-stack inputs; rides on FPF_HOIST's step (steps aside by name without it)",
                   "kind": "schedule", "numerics": "byte-identical to fast without it at 448, 832 and 1,216 tokens (same ops per element; XLA compiles the hoisted lines into the same fusions at these sizes); fast-class because it rides on FPF_HOIST, which is not bitwise vs stock", "strategy": "LOCAL.af3_jax.atom_cond_hoist",
                   "switch": "AF3_JAX_ATOM_COND_HOIST=1 (set by the mode table for fast and big's region fast; installed before the FlashPairformer add-on's import so HoistDiffusionHead derives from its DiffusionHead)",
                   "touches": [], "site": "opt/af3_jax_opt/inprocess/atom_cond_hoist.py"},
    "FPF_HOIST": {"impl": "jax", "name": "diffusion-conditioning hoist: the step-invariant pair conditioning computed once per sample call", "kind": "schedule", "strategy": "LOCAL.step_invariant_hoist",
                  "numerics": "not bitwise: under the deterministic recipe the hoist alone on the exact base is byte-identical to stock at bucket 64 but not at 400 / 1200 tokens (XLA compiles the hoisted conditioning outside the sampler's scan into different fusions; inside the seed-spread band, the add-on's README)", "switch": "AF3_DIFFUSION_HOIST (the add-on's hoist switch)",
                  "touches": ["flashpairformer/af3_flashpairformer/diffusion_hoist.py"], "source": "flashpairformer/README.md"},
    # the memory levers of mode big (opt/af3_jax_opt/big_levers.py, registered in opt_core.mem.registry under their lower-case names; applied in the
    # model process by big_launch.py through opt_core.mem.apply — all of them, at their registered settings; under --n_gpu P > 1 the three ROWPAIR supersedes are off;
    # evidence = the launcher's ACTIVE line before the script + its census line at exit). kind schedule: every
    # one re-schedules a computation of the compiled graph (chunks / shards / a smaller batch), so executables are indexed under them (det.py).
    "SAMPLES_PER_PASS": {"impl": "jax", "name": "the vmapped diffusion sampler run k samples per pass (k = 1), stock draws kept (the same per-sample keys and the one initial-noise draw, sliced per chunk) Not composed on the one-GPU line since 0.3.26: 0.00 GiB at 2,048 and 4,096 padded tokens for +45 % time (measured, allocator peak with preallocation off); composed on the row-sharded line (--n_gpu P) as before; re-enable on one GPU by one line of the mode table if a measurement above 5,120 shows a benefit.",
                         "kind": "schedule", "numerics": "measured (stock draw order; a smaller batch may change XLA's fusion / kernel choice)", "strategy": "F7.chunked_eval",
                         "switch": "--mode big", "touches": [],
                         "site": "opt/af3_jax_opt/big_levers.py", "patches": "alphafold3.model.network.diffusion_head.sample (rebound)"},
    "TRANSITION_SHARD": {"impl": "jax", "name": "GlobalConfig.pair_transition_shard_spec = ((None, rows),): the pair transitions in row shards at every size (rows = 256)",
                         "kind": "schedule", "numerics": "measured (a per-position MLP; per-shard kernels may differ under XLA)", "strategy": "F7.chunked_eval",
                         "switch": "--mode big", "touches": [],
                         "site": "opt/af3_jax_opt/big_levers.py", "patches": "alphafold3.model.model.Model.__init__ (wrapped: the config knob set through opt_core.mem.jax_mem.set_config_path)"},
    "COND_SHARD": {"impl": "jax", "name": "the diffusion head's pair conditioning (concat with the relative encoding, norm, projection, two transitions) in row shards through the fork's mapping.sharded_apply (rows = 256)",
                   "kind": "schedule", "numerics": "measured (position-wise ops in row shards; no reduction is split)", "strategy": "F7.chunked_eval",
                   "switch": "--mode big: off under --n_gpu P > 1, superseded by ROWPAIR", "touches": [],
                   "site": "opt/af3_jax_opt/big_levers.py", "patches": "alphafold3.model.network.diffusion_head.DiffusionHead._conditioning (rebound); flashpairformer/af3_flashpairformer/diffusion_hoist.py _pair_conditioning too when that module is loaded"},
    "LOGITS_SHARD": {"impl": "jax", "name": "the diffusion transformer block's pair path (per-block LayerNorm + pair-logits projection) in row shards through the fork's mapping.sharded_apply (rows = 256) Not composed since 0.3.26: 0.00 GiB at 2,048 and 4,096 padded tokens for +4.6 % time (measured); re-enable by one line of the mode table if a measurement above 5,120 shows a benefit.",
                     "kind": "schedule", "numerics": "measured (position-wise ops in row shards; no reduction is split)", "strategy": "F7.chunked_eval",
                     "switch": "--mode big: off under --n_gpu P > 1, superseded by ROWPAIR; refuses by name when another install owns the Transformer class", "touches": [],
                     "site": "opt/af3_jax_opt/big_levers.py", "patches": "alphafold3.model.network.diffusion_transformer.Transformer (subclass installed on the module)"},
    "TRIMUL_CHUNK": {"impl": "jax", "name": "the trunk's TriangleMultiplication in row blocks of the output (rows = 512): the contracted half of the gated projection once for the plane, the other half + einsum + norm + output projection + gate per block",
                     "kind": "schedule", "numerics": "measured (the same contraction per (i, j); per-block GEMM tiling)", "strategy": "F7.chunked_eval",
                     "switch": "--mode big: off under --n_gpu P > 1, superseded by ROWPAIR; composes on exact's GLUT subclass; refuses by name when another install owns the class", "touches": [],
                     "site": "opt/af3_jax_opt/big_levers.py", "patches": "alphafold3.model.network.modules.TriangleMultiplication (subclass installed on the module; composes on pallas_addon/patches/af3_pallas_levers.py make_patched_trimul_class when GLUT is on)"},
    # the memory mode's resource axis (--n_gpu P > 1): the row-sharded pair stack — the shared core's AlphaFold-3 Haiku recipe driven by the tree's adapter
    "ROWPAIR": {"impl": "opt_core.mem.rowpair_jax", "name": "row-sharded pair stack over P GPUs (trunk, recycle carry, template embedder, MSA pair reads, confidence/distogram heads, "
                "diffusion pair conditioning): each device holds a row block [N/P, N, C]; collectives complete every contraction per device (no partial sums)",
                "kind": "schedule", "numerics": "not bitwise (per-device tiling of complete contractions; fast-class)", "strategy": "F7.tensor_parallel",
                "switch": "--n_gpu P with --mode big (modes.with_n_gpu; the launcher's `--n_gpu P`; opt/af3_jax_opt/inprocess/rowpair.py in the model process → opt_core.mem.rowpair_jax.alphafold3.install)",
                "touches": [], "site": "opt/af3_jax_opt/inprocess/rowpair.py"},
}

# the run-time levers per mode live in modes.KIT_MODES (the one mode table) (available, not default); every id there is a
# key of LEVERS. "impl" = the mechanism (host | xla | pallas_triton | tokamax_config | tokamax | jax); the site = touches[0] (levers of the carried
# add-ons) or "site" (the tree's own) — the impl= / site= keys of the LEVER line ("patches" = the model site a memory lever rebinds, prose); origin= is kit for all of them (report.lever_lines).
