"""The lever registry: every lever the modes (modes.py) name, described from the kit files that implement it (file:line under boltz2/opt/).

A lever is one runtime optimization with its own switch, applied by the kit's own code inside the worker process. This registry describes;
it never applies. ``switch`` is the environment name the kit reads, ``value`` the setting the mode rows use, ``kit_gate`` the kit's own
run-time fallback (what makes the lever inert on a box — reported as ``levers_fallback`` from the worker log).
"""
from __future__ import annotations

from typing import Dict

TRUNK = "forward/trunk_levers"
DIT = "forward/dit_hoist"
ADAPTER = "boltz2_opt"   # the kit package: levers installed by its engine adapters (boltz2_opt/big.py: the memory levers on opt_core.mem; boltz2_opt/trimul.py: the fused TriMul on opt_core.trimul), attached by name in the worker process, never staged

LEVERS: Dict[str, dict] = {
    # --- engine adapter boltz2_opt/exactln.py over the shared core's carried exactln package (opt_core.kernels.ln row exactln, word `core`; word `on` refused by name) (torch.nn.functional.layer_norm replaced process-wide after the worker's model import; attached by worker_launch --attach exactln) [EXACTLN track] ---
    "exactln": {"kit": ADAPTER, "file": f"{ADAPTER}/exactln.py", "lines": "1-40", "switch": "BOLTZ_EXACTLN", "value": "core", "tier": 1,
                "what": "every CUDA LayerNorm call of >= 2**20 elements whose ATen dispatch is the vectorized kernel (the pair track's [N,N,128] LayerNorms of every Pairformer stack, incl. the ending node's transposed input read strided, the MSA / template modules' C=64 ones) runs the carried bit-for-bit replica of ATen's layer_norm forward (opt_core kernels.ln exactln/exactln_fwd.cu: the online Welford update, the (32,4)-CTA shuffle combine tree, IEEE rcp/div, non-FTZ rsqrtf, fused affine of torch 2.12.0's sm_90 binary) one warp per row instead of one CTA per row, the pair-track adapters' LayerNorm->bf16 cast fused into its store (exactln.ln_to_bf16); smaller calls, CUDA-graph capture of an uncompiled shape and autograd take torch's kernel by census word",
                "kit_gate": "exactln_report: applied / census.served / fallback by declared word (below_min_numel, capturing_uncompiled, grad, cpu, copied_input) and the fail-closed gate; refuses by name at apply on torch != 2.12.0 (torch_version) or a compute capability outside exactln.PROVEN_CC (cc_unproven:sm_<cc>; 9.0 and 8.0 are proven); within the proven cards the first call of each width class is bit-compared against torch's kernel before the class is served (selftest; bitcmp_mismatch:<class> / bitcmp_refused:<class> hand the class back by name); cc / cc_proven on its line"},
    "exactln_resid": {"kit": ADAPTER, "file": f"{ADAPTER}/exactln.py", "lines": "resid_fuser", "switch": "BOLTZ_EXACTLN_RESID", "value": "on", "tier": 1,
                      "what": "the pair residual add `z = z + f(z)` fused with the NEXT block's LayerNorm in one pass over the pair tensor (opt_core kernels.ln exactln/exactln_fwd.cu exactln_resid_fwd: one FADD.RN per element = torch's promote-add, then the ATen LayerNorm replica on the in-register sums stored as the consumer's cast); needs exactln and a hook in the trunk levers' residual statement (boltz_trunk_levers.RESID_FUSER) this tree does not carry yet — an AVAILABLE word, in no mode row (the adapter refuses by name without the hook)",
                      "kit_gate": "exactln_report: applied names exactln_resid (state=on; requires exactln: word_absent / requires_exactln otherwise), census resid:<class>@<site> served words + resid_ln_taken (the parked LayerNorm the next block took) / declared words resid_below_min_numel (z under 2**26 elements: the caller adds), resid_probe_unused|resid_probe_dtype (a site learning its consumer's dtype, <= 2 each), resid_site_off, bitcmp_refused:resid:* (a class whose first-call bit-compare failed: stock statements for the process); sites = boltz_trunk_levers._fused (tri_att_start, tri_att_end [transposed], transition_z, proj_z)"},
    # --- trunk add-on: boltz_trunk_levers.py (class-level monkeypatches of the Pairformer / MSA trunk; read once at apply()) ---
    "resid": {"kit": TRUNK, "file": f"{TRUNK}/boltz_trunk_levers.py", "lines": "10-12,33", "switch": "BOLTZ_LEVERS", "value": "resid", "tier": 1,
              "what": "eval-mode residual `z + dropout_mask*f(z)` with the mask == 1.0 becomes `z + f(z)` (the torch.rand draw is kept so the CUDA RNG stream is unchanged)"},
    "mask2": {"kit": TRUNK, "file": f"{TRUNK}/boltz_trunk_levers.py", "lines": "13-19,33", "switch": "BOLTZ_LEVERS", "value": "mask2", "tier": 1,
              "what": "the same trivial-mask elimination in AttentionPairBias (Pairformer sequence attention, fp32 `attn + (1-mask)*-inf`)"},
    "flash_triattn": {"kit": TRUNK, "file": f"{TRUNK}/boltz_flash_triattn_patch.py", "lines": "231-270", "switch": "BOLTZ_TRIATTN", "value": "flash (+ BOLTZ_TRIATTN_MIN_TOKENS=300)", "tier": 2,
                      "what": "flash (fused, online-softmax) triangle attention kernel (flash_triattn.py) in place of the torch triangle attention above the token gate; not bitwise",
                      "kit_gate": "active only at N ≥ BOLTZ_TRIATTN_MIN_TOKENS (:247); Triton JIT per box (BOLTZ_TRIATTN_WARM pre-compiles, :262)"},
    # --- the CUDA-graph sampler and the DiT hoist: dit_hoist/src/boltz_graph_patch.py, boltz_dit_hoist.py (staged; inserted into the worker by make_worker_variant.py) ---
    "graph_sampler": {"kit": DIT, "file": f"{DIT}/src/boltz_graph_patch.py", "lines": "391-411", "switch": "BOLTZ_GRAPH_DIFFUSION", "value": "graph", "tier": 1,
                      "what": "CUDA-graph capture of the diffusion denoiser step: one capture per (atom, token) shape, 199 replays per 200-step sample (n_replay == 199, sampler_mode == graph per row)",
                      "kit_gate": "falls back to the stock step on capture failure (capture_stock_fallbacks per row); private memory pool per captured shape"},
    "graph_trunk": {"kit": "forward/graph", "file": "forward/graph/boltz_graph_trunk.py", "lines": "1-60", "switch": "BOLTZ_GRAPH_TRUNK", "value": "pf,pfnoseq,templ,sovl (+ BOLTZ_GRAPH_TRUNK_MAX_TOKENS=300; unit msa by word)", "tier": 1,
                    "what": "CUDA-graph capture/replay of the trunk modules per (module, item shape): PairformerModule (trunk 64 blocks + confidence 8), PairformerNoSeqModule (template pair stack), MSAModule (unit msa) — first call of a shape eager (warm), second captured, later calls and later items of the shape replayed (same-shape cross-item reuse, R2: captured / replayed / evicted / capture_s on the LEVER line); the template module's distogram boundaries hoisted (the stock CPU linspace evaluated once, no per-call host sync: unit templ); sovl = the s-track overlap unit; attached by boltz2_opt.graph (worker_launch --attach graph) [GRAPH track]",
                    "kit_gate": "eager by name outside [BOLTZ_GRAPH_TRUNK_MIN_TOKENS, BOLTZ_GRAPH_TRUNK_MAX_TOKENS] and on non-CUDA / training / grad calls (graph_report.census eager:<word>); a capture failure is counted (eager:dead:<Exc>) and the gate refuses"},
    "dit_hoist": {"kit": DIT, "file": f"{DIT}/src/boltz_dit_hoist.py", "lines": "629-680", "switch": "BOLTZ_DIT_HOIST", "value": "2", "tier": 1,
                  "what": "step-invariant work of the diffusion transformer (conditioning, AdaLN scale/shift, atom-encoder tensors) computed once per sample and served from a cache inside the CUDA-graph loop (level 2 = outermost, over the graph patch)",
                  "kit_gate": "the hoist wrapper counts cache builds / refreshes / capture_stock_fallbacks per sample() (STATS['last']); cache per input (hoist_cache_mb per row)"},
    # --- the sampler roll-out: forward/sampler/src/bz_sampler*.py, installed by the engine adapter boltz2_opt/sampler.py (AtomDiffusion.sample, class-level); attached by worker_launch --attach sampler [SAMPLER track] ---
    "rollout": {"kit": ADAPTER, "file": f"{ADAPTER}/sampler.py", "lines": "-", "switch": "BOLTZ_SAMPLER_ROLLOUT", "value": "graph", "tier": 1, "words": ("BOLTZ_SAMPLER_MAX_TOKENS",),   # words: the memory row's token ceiling leaves with the lever
                "what": "the diffusion sampler as a boundary-graph roll-out (forward/sampler/src/bz_sampler.py) in place of the per-step graph patch (graph_sampler): schedule read once, every random tensor pre-drawn in stock order, ONE CUDA graph per step boundary (alignment tail + Euler update of step k + augmentation / noise / DiffusionModule / alignment head of step k+1) captured per sample() and replayed S-1 times, SVD/det eager between replays, weighted_rigid_align's guard prints without per-step host syncs, in-graph Euler with host-folded fp32 scalars (the reciprocal recipe probed against torch's own division at install, refused by name if neither reproduces it); bitwise = stock; the DiT hoist's level-2 cache is read inside the captured boundary",
                "kit_gate": "sampler_report: calls / samples / replays / captures, scope words by name (steering), capture_failed, div_recipe; fail-closed gate; refuses by name beside BOLTZ_GRAPH_DIFFUSION (both own AtomDiffusion.sample); leaves the row with the hoist under --use_potentials"},
    "align_jacobi64": {"kit": ADAPTER, "file": f"{ADAPTER}/sampler.py", "lines": "-", "switch": "BOLTZ_SAMPLER_ALIGN", "value": "jacobi64", "tier": 2,
                       "what": "the rigid alignment's 3x3 SVD + det by ONE sync-free in-graph kernel (fp64 one-sided Jacobi; no host sync left in the sampling loop: S-1 back-to-back replays); Tier 2 (R agrees with cuSOLVER's fp32 gesvd to ~1e-6; a change outside the network, its own word) — an AVAILABLE word, in no mode row",
                       "kit_gate": "sampler_report: kabsch=<word> on the rollout lever line; needs the roll-out"},
    "align_aligncap": {"kit": ADAPTER, "file": f"{ADAPTER}/sampler.py", "lines": "-", "switch": "BOLTZ_SAMPLER_ALIGN", "value": "aligncap", "tier": 1,
                       "what": "the bitwise cusolverDnSgesvd seam (opt/forward/waste/aligncap.py) for the roll-out: the per-step 3x3 SVD eager BETWEEN graph replays straight into static buffers (no clone / devInfo host read / copies), det + F + R inside the graph; Tier 1 exact — an AVAILABLE word, in no mode row",
                       "kit_gate": "sampler_report: kabsch=aligncap on the rollout lever line; needs the roll-out"},
    "dit_fused": {"kit": ADAPTER, "file": f"{ADAPTER}/sampler.py", "lines": "-", "switch": "BOLTZ_SAMPLER_DIT", "value": "bf16", "tier": 2,
                  "what": "PRECISION lever: the fused bf16 token-transformer step of the diffusion module (forward/sampler/src/bz_sampler_dit.py) — inside the roll-out's captured boundary (exact / fast) or served from the stock eager sampler loop (big: per-sample() pair-bias pack, packed weights built and dropped per sample(), weights=sample): packed bf16 projections, flash attention with pair bias, fused AdaLN / gates / SwiGLU where stock runs the 24 DiT layers in fp32 ('highest'); Tier 2 — the fast row's token transformer (the exact row's is dit_par / dit_mask on the stock fp32 GEMMs)",
                  "kit_gate": "sampler_report: dit words, per-call census (calls / served / scope, weights builds); serves under the roll-out or the eager loop (a per-sample() pack)"},
    # --- the DITEXACT token-transformer schedule: forward/ditexact/src/dx_token.py, installed by the engine adapter boltz2_opt/ditexact.py (DiffusionModule.__init__ wrapped, the schedule the instance forward of every token transformer built); attached by worker_launch --attach ditexact; reads the DiT hoist's level-2 cache [DITEXACT track] ---
    "dit_par": {"kit": ADAPTER, "file": f"{ADAPTER}/ditexact.py", "lines": "-", "switch": "BOLTZ_DIT_EXACT", "value": "par (a word of the comma list)", "tier": 1,
                "what": "the diffusion token transformer's 24 layers re-scheduled inside the captured denoiser step (opt/forward/ditexact/src/dx_token.py, the instance forward of DiffusionModule.token_transformer): each layer's s-conditioned path (2 LayerNorms, 6 fp32 GEMMs, 4 sigmoids that read only s) issued one layer ahead on a side stream, k|v|g beside q, a_to_b beside swish_gate, joined by events; the same ATen / cuBLAS calls on the same operands (same descriptors, same per-(handle, stream) workspace size), only the launch stream differs — bitwise; the side streams are built at the first eager call (refused by name under capture); source constants n_spath / prefetch on the LEVER line",
                "kit_gate": "ditexact_report: installed / calls / calls_par / prev_by (declared: no_hoist_cache — a denoiser call without the hoist's level-2 cache takes the class forward) / capturing_calls and the fail-closed gate; leaves the row with the hoist (--use_potentials)"},
    "dit_mask": {"kit": ADAPTER, "file": f"{ADAPTER}/ditexact.py", "lines": "-", "switch": "BOLTZ_DIT_EXACT", "value": "mask (a word of the comma list)", "tier": 1,
                 "what": "the token transformer's additive attention mask `attn + (1 - mask)*-inf` (inf = 1e6, finite) skipped when the hoist's cached term is -0.0 in every element (token_pad_mask all ones, checked once per prediction outside capture): x + (-0.0) == x bit for bit; a mask with a zero keeps the stock add",
                 "kit_gate": "ditexact_report: mask_skipped / mask_applied per denoiser call and the fail-closed gate"},
    "dit_sba": {"kit": ADAPTER, "file": f"{ADAPTER}/ditexact.py", "lines": "-", "switch": "BOLTZ_DIT_EXACT", "value": "sba (a word of the comma list)", "tier": 1,
                "what": "the token transformer's `attn / head_dim**0.5 + pair_bias [+ mask term]` (two or three elementwise kernels, each a full pass over the fp32 [B*m,16,N,N] scores) as one in-place Triton pass with ATen's own roundings: x * fp32(1/s) (ATen divides by a CPU scalar through its fp32 reciprocal), then + bias, then + mask, FMA contraction off — bitwise (sha256-identical at multiplicity 1 and --diffusion_samples 5); refuses by name per call (no_triton / cpu / dtype / layout) and the torch statements serve",
                "kit_gate": "ditexact_report: sba_fused / sba_torch_by per call and the fail-closed gate (a refused call is named and the gate refuses)"},
    "dit_smx": {"kit": ADAPTER, "file": f"{ADAPTER}/ditexact.py", "lines": "-", "switch": "BOLTZ_DIT_EXACT", "value": "smx (a word of the comma list)", "tier": 1,
                "what": "the token transformer's `softmax(attn / head_dim**0.5 + pair_bias [+ mask term], -1)` as one in-place NVRTC-compiled CUDA kernel: the dit_sba arithmetic then a line-by-line replica of ATen's softmax_warp_forward (one warp per row, lane-strided elements, sequential + xor-butterfly max and sum, expf, e / sum) for 128 < N <= 2048 — bitwise; BIT-COMPARED AT RUN TIME per (N, masked) class at the first eager encounter (torch's statements vs the kernel on the same scores, torch.equal): a class that does not compare equal is refused by name and the torch statements serve it",
                "kit_gate": "ditexact_report: smx_fused / smx_bitcmp / smx_declined_by and the fail-closed gate (a declined or unequal class is named and the gate refuses)"},
    "dit_glue": {"kit": ADAPTER, "file": f"{ADAPTER}/ditexact.py", "lines": "-", "switch": "BOLTZ_DIT_EXACT", "value": "glue (a word of the comma list)", "tier": 1,
                 "what": "the token transformer layer's main-chain elementwise glue as three NVRTC CUDA kernels with ATen's per-element op order and roundings — AdaLN affine sc*x+sb (mul then add), gated residual a+g*o (mul then add), SwiGLU (silu(gates)*x)*ab with silu(g) = g/(1+expf(-g)) — six graph nodes per layer fewer; bitwise; each kernel BIT-COMPARED AT RUN TIME per shape class at first eager use, declining by name for a class that does not compare equal; proven compute capabilities only (refused by name at install elsewhere)",
                 "kit_gate": "ditexact_report: glue_fused (= 120 x calls) / glue_bitcmp / glue_declined_by / cc_refused / nvrtc_compile_s and the fail-closed gate"},
    # --- the triangle multiplication: installed by the engine adapter boltz2_opt/trimul.py on the core's TriMul adapter (opt_core.trimul) over the core's ONE
    #     triangle-multiplication provider (opt_core.kernels.trimul) BY TIER WORD; attached by worker_launch --attach trimul (strategy id F2.trimul) ---
    "fpf_trimul": {"kit": ADAPTER, "file": f"{ADAPTER}/trimul.py", "lines": "-", "switch": "BOLTZ_FPF_TRIMUL", "value": "1 (+ BOLTZ_FPF_TRIMUL_PROVIDER=fast|big = the core provider's tolerance-class TIER word — fast on the fast row, big on the big row —, or one of its tolerance-class rows by name (v4|tmk3_fast|tx_sm90a|native|esm_v5_fwd|esm_shapes|esm_k1ptr: an ablation entry; a row this card cannot serve is refused at install by name); BOLTZ_FPF_TRIMUL_MAX_TOKENS=<n> = a ceiling, above_max_tokens by name)", "tier": 2,
                   "what": "the TriMul by the core provider's tolerance-class tier word: per call (card, stack, precision, c_z, N bucket, direction) the provider's measured winner of the cell serves through its face — its Triton / native kernel rows (bf16 tensor-core projections, a different reduction tree: not part of an exact row) or, where its table names them, the library op —; on the fast / big rows the PAIRFUSE driver's own TriMul site takes the C=128 stacks by the same word (this lever prints superseded_by=pairfuse@c128 and serves the stacks the driver hands back: the template Pairformer's C=64 TriMul, inputs below the driver's floor); no kernel, cell table or token gate of this tree's",
                   "kit_gate": "the core ladder's census and fail-closed gate (opt_core.trimul Lever: served / fallback_by / errors per direction; no declared fallback: the tier word names a row for every cell; a ceiling's above_max_tokens when the row names one) written as trimul_report; report()['tier'] names the rows served through the face"},
    "fpf_trimul_exact": {"kit": ADAPTER, "file": f"{ADAPTER}/trimul.py", "lines": "-", "switch": "BOLTZ_FPF_TRIMUL", "value": "exact (+ BOLTZ_FPF_TRIMUL_PROVIDER=exact = the core provider's exact TIER word (the row's word; unset = exact), or one of its exact-class kernel rows by name (tmk3_exact|native_exact|tx_sm90a_exact: an ablation entry); BOLTZ_FPF_TRIMUL_MAX_TOKENS=<n> = a ceiling)", "tier": 1,
                         "what": "the TriMul by the core provider's `exact` TIER word at every N and c_z: per call an exact-class KERNEL row the provider vouches byte-identical to upstream's fused TriMul on this process's stack (native_exact, tmk3_exact ...) serves through its face; where the provider names the library op itself as the cell's exact row (its stock rows cueq / torch_math) the engine's OWN call of upstream's kernel serves that call, BY NAME (fallback_by=library_op:<row>) — the output bytes are the stock arm's either way; no kernel, cell table or token gate of this tree's",
                         "kit_gate": "the core ladder's census and fail-closed gate (trimul_report: served / fallback_by / errors; the declared path to the engine's TriMul is library_op:<row> — a run whose every cell names the library op idles the lever, installed, gate ok; any other fallback or a kernel error refuses the gate) + report()['tier'] (word / rows served through the face / library-op cells / last row and cell)"},
    # (the fused TriMul SITE levers trimul_site / trimul_fp8 — kernels bz2_trimul, adapter trimul_site.py, words BOLTZ_TRIMUL_SITE / BOLTZ_TRIMUL_FP8 — retired:
    #  the kernels are the core's triangle-multiplication provider row `bz2` (opt_core.kernels.trimul), reachable from a row as BOLTZ_PAIRFUSE_TRIMUL=core.bz2)
    # --- the core's fused pair-track cells (opt_core.attn.pair_fused), installed by the engine adapters boltz2_opt/transition.py and boltz2_opt/pairblock.py; attached by worker_launch --attach transition / pairblock ---
    "fused_transition": {"kit": ADAPTER, "file": f"{ADAPTER}/transition.py", "lines": "-", "switch": "BOLTZ_TRANSITION", "value": "exact | fast | big", "tier": 1,
                         "what": "the fused SwiGLU transition (LayerNorm output -> W_a|W_b -> silu(a)*b -> W_out in one kernel, the 4C hidden on chip) in place of Transition.forward on the bf16-autocast calls (pair transitions of every Pairformer stack, the MSA module's transitions); exact: the unchunked calls, byte-identical to stock; fast: the hidden-chunked calls too (Tier 2 there)",
                         "kit_gate": "transition_report: served / fallback by reason (autocast_off = the fp32 sequence transition, chunked = the MSA module's chunked calls under exact, no-cell:<shape> = a shape the core's table does not serve) and the fail-closed gate"},
    "pairblock": {"kit": ADAPTER, "file": f"{ADAPTER}/pairblock.py", "lines": "-", "switch": "BOLTZ_PAIRBLOCK", "value": "cueq (exact) | default (fast, big: the block's own keyed attention core, 0.3.23; + BOLTZ_PAIRBLOCK_MIN_TOKENS=300) | k2b | flash | core.<word> (the attention core through the core's triangle-attention provider by word: k2b | k2 | flash | cuda_sm90a | exact_headsplit | cueq | fast | exact; exact-class words = this lever alone; a row this card cannot serve refused by name)", "tier": 1,
                  "what": "the fused triangle-attention block in place of TriangleAttention.forward under kernels on: the module's LayerNorm, then one prologue kernel (q|k|v|g projections + the bf16-rounded pair bias), the attention core (cueq: cuEquivariance's triangle_attention, the stock kernel — byte-identical to stock; flash: the core's flash triangle attention at N ≥ the gate, Tier 2 — the registry lever flash_triattn names that core), one epilogue kernel (sigmoid gate * o @ W_o)",
                  "kit_gate": "pairblock_report: served per core / fallback by reason (kernels_off, autocast_off, the core's refusal words) and the fail-closed gate"},
    "triattn_exact": {"kit": ADAPTER, "file": f"{ADAPTER}/triattn_exact.py", "lines": "-", "switch": "BOLTZ_TRIATTN_EXACT", "value": "1", "tier": 1,
                      "what": "the fused block's attention core (pairblock, cueq) served through the core's triangle-attention provider by its `exact` tier word: the exact-class kernel row triattn_exact on a (card, torch, library) stack the core's cell table vouches for — bit-identical to the library op there — and the library call itself (the provider's cueq row, its stock= op) everywhere else, per cell and by name",
                      "kit_gate": "triattn_exact_report: applied / census (calls, served, fallback by refusal kind, errors, rows served by name, the kernel row's own tally kernel=<served>/<calls>) and the fail-closed gate; the LEVER line names the provider's row for this card and stack (row= class= cell= stack=)"},
    "templ_skip": {"kit": ADAPTER, "file": f"{ADAPTER}/templskip.py", "lines": "-", "switch": "BOLTZ_TEMPL_SKIP", "value": "1", "tier": 1,
                   "what": "dummy-template elision: Boltz-2 runs its template module (input projections + 2 C=64 Pairformer blocks over the N x N pair rows, every recycling pass) on "
                           "every input and aggregates it under the template mask; an input that declares no template (or whose declared templates all became dummy slots) has an "
                           "all-zero mask, so the aggregation (v*mask).sum/n is the zero tensor whatever the Pairformer computed and the update is the module's output projection of "
                           "it, u_proj(relu(0)) (its bias per channel) — served here by running only that projection (the module's own relu / u_proj on the same zero tensor: the "
                           "same kernels on the same values) without the input projections, the Pairformer and v_norm; a pass with any template slot set runs the module as stock; bitwise",
                   "kit_gate": "templskip_report: templ_skip among applied; census skipped + live + capturing + no_mask == calls, errors == 0"},
    "pairblock_c64": {"kit": ADAPTER, "file": f"{ADAPTER}/pairblock.py", "lines": "-", "switch": "BOLTZ_PAIRBLOCK_C64", "value": "1", "tier": 2,
                      "what": "the template Pairformer's C=64 triangle-attention stack (template_dim 64, 4 heads x 32; 2 blocks x start/end x every recycling pass) through the same fused "
                              "block in the Tier-2 variants: opt_core's qualified (64,4,32) prologue / epilogue cells (r11/r21 on 9.0, r91/r92 on 8.0; opt_core >= 0.5.28.0; tolerance class: "
                              "fp64-error ratio 1.05, max |d| <= 0.0078 bf16) around cuEquivariance's core below pairblock.C64_CORE_MIN_TOKENS (800) and the K2B core at and above it; `cueq` "
                              "(exact) hands that stack back by name (kept_out:64x4x32). Acts on TEMPLATED inputs; on an untemplated input the template module's update is masked to zero "
                              "(lever templ_skip elides the module there)",
                      "kit_gate": "pairblock_report: pairblock_c64 among applied, the x64 shapes among served; kept_out:64x4x32 among fallback where the variant does not serve it"},
    # --- the PAIRFUSE layer driver: forward/pairfuse/bz_pairfuse.py, installed by the engine adapter boltz2_opt/pairfuse.py (PairformerModule / PairformerNoSeqModule / MSALayer forwards); attached by
    #     worker_launch --attach pairfuse (trigger boltz.model.modules.trunkv2). While it serves the C=128 stacks of a row the class-level block adapters (trimul / transition / pairblock) print
    #     superseded_by=pairfuse@c128 and serve the stacks it hands back; its own line prints providers=. The fast row's word (bf16) [PAIRFUSE track] ---
    "pairfuse": {"kit": "forward/pairfuse", "file": "forward/pairfuse/bz_pairfuse.py", "lines": "-", "switch": "BOLTZ_PAIRFUSE", "value": "bf16 (the fp32-resident word is refused by name until released); optional per-site picks `,triatt=default|k2b|flash|core.<word>` (bare bf16 = `triatt=default`: the fused block's own keyed attention core, 0.3.23) `,trimul=core.<word>|v4` (the fast / big rows name `trimul=core.fast`: the core triangle-multiplication provider by its fast tier word; bare = the driver's own v4 binding); `triatt=`: the bf16 word's own default is `core.fast` (the core triangle-attention provider by its fast tier word: row k2b on 8.0, 0.3.18), the 9.0 rows' `BOLTZ_PAIRFUSE_TRIATT=core.triattn_native` from 512 tokens over it, the K2B block below that floor and in the fp32 word) (core.<word>: the core's triangle-attention / triangle-multiplication provider by row name or tier word; a row this card / stack cannot serve is refused by name before the stack starts)", "tier": 2,
                 "what": "PRECISION lever: the PAIRFUSE layer driver — every C=128 pair stack (trunk PairformerModule, confidence, the MSA module's pair layers) on ONE resident bf16 z per stack call where stock keeps the residual stream fp32: each sub-layer reads z once (LayerNorm inside the core's prologue) and writes it once (residual inside the core's epilogue, in place), the ending node by strides, the sequence-attention pair bias in one pass (adapter boltz2_opt/pairfuse.py; provider cores fpf_trimul_v4 / bz2_trimul, opt_core.attn.pair_fused, K2B — unchanged)",
                 "kit_gate": "stacks below 128 tokens, C != 128 (templates) and kernels-off runs take the module's original forward by name (pairfuse_report.census.fallback); a core refusal or kernel error refuses the gate; BOLTZ_PAIRFUSE=fp32 refused by name at launch"},
    # --- the memory levers: installed by the engine adapter boltz2_opt/big.py on the core's memory-mode library (opt_core.mem: registry / record / chunk / allocator); attached by worker_launch --attach xl ---
    "xl_trans": {"kit": ADAPTER, "file": f"{ADAPTER}/big.py", "lines": "-", "switch": "BOLTZ_XL_LEVERS", "value": "trans", "tier": 1,
                 "what": "the pair Transition evaluated BOLTZ_XL_TRANS_ROWS rows at a time into one preallocated output (opt_core.mem.chunk.pair_transition_chunked over the stock forward per row block: the LayerNorm copy and the [rows, N, 4C] intermediates exist for 256 rows, not N); stock call sites without chunk_size, eval mode, N ≥ BOLTZ_XL_MIN_TOKENS; label bitwise",
                 "kit_gate": "the adapter's report (xl_report: applied / stats.trans_rowchunked_calls / the record's per-unit census and exit gate) read by stack.evidence: a lever not applied, absent on a unit or refused is a named problem; no silent stock path (D13)"},
    "xl_cond": {"kit": ADAPTER, "file": f"{ADAPTER}/big.py", "lines": "-", "switch": "BOLTZ_XL_LEVERS", "value": "cond", "tier": 1,
                "what": "the diffusion pairwise conditioner evaluated per row block (opt_core.mem.chunk.chunk_rows) into one buffer; the 24 per-layer token pair-biases written into ONE fp32 [B, N, N, 24·16] tensor (BOLTZ_XL_COND_FP32=1: the denoiser's per-step .float() then aliases instead of copying); label bitwise",
                "kit_gate": "as xl_trans (stats.cond_rowchunked_calls)"},
    "xl_free": {"kit": ADAPTER, "file": f"{ADAPTER}/big.py", "lines": "-", "switch": "BOLTZ_XL_LEVERS", "value": "free", "tier": 1,
                "what": "the CUDA storages of the conditioning outputs dead after sampling (q, c, to_keys, the atom / token pair biases; tensors aliasing the trunk's s / z / feats excluded by storage pointer) released at the confidence module's entry; lifetime only, no value changes",
                "kit_gate": "as xl_trans (stats.free_events; a unit whose conditioner did not run is `skipped` with the reason, not partial)"},
    "relpos_lazy": {"kit": ADAPTER, "file": f"{ADAPTER}/big.py", "lines": "-", "switch": "BOLTZ_XL_LEVERS", "value": "relpos", "tier": 1,
                    "what": "the fp32 [B, N, N, c_z] relative-position encoding of the trunk and of the confidence module released right after its one consumer (the token_bonds add) and recomputed by the same RelativePositionEncoder call from feats where the diffusion conditioner reads it (a deterministic one_hot + Linear: the same values); 4·N²·c_z bytes across sampling and confidence",
                    "kit_gate": "as xl_trans (stats.relpos_lazy_released)"},
    "expandable_segments": {"kit": ADAPTER, "file": f"{ADAPTER}/big.py", "lines": "-", "switch": "PYTORCH_CUDA_ALLOC_CONF", "value": "expandable_segments:True", "tier": 1,
                            "what": "torch's caching allocator maps physical memory into expandable virtual segments (fragmentation only; no arithmetic), set for the worker process before CUDA init (the core's process-scope lever opt_core.mem.allocator, confirmed by the allocator read-back once CUDA is up)",
                            "kit_gate": "the adapter's report names it (env.PYTORCH_CUDA_ALLOC_CONF, env.alloc_effective = the record's read-back) in the worker log"},
    "rowpair_tp": {"kit": ADAPTER, "file": f"{ADAPTER}/rowpair.py", "lines": "-", "switch": "BOLTZ_TP", "value": "<P>", "tier": 2, "sync_switch": "ROWPAIR_DIFF_NOISE_SYNC", "sync_default": "bcast",   # the core word for the replicated-tensor sync policy: bcast (rank 0 authoritative; this route is det 0) | guard (strict bitwise, the debugging opt-in; a det-1 route would set it)
                   "what": "the row-sharded pair stack at --n_gpu P > 1 (big only): the trunk / confidence / template Pairformer stacks run with z row-sharded over P GPUs on the core's "
                           "tensor-parallel primitives (opt_core.mem.rowpair: ring / all-to-all TriMul contractions, triangle-bias all-gather, row-local schedules); every rank runs the "
                           "whole worker, the MSA pair layers and everything outside the pair stacks replicated; installed in each rank's worker by worker_launch --attach tp; nothing at n_gpu = 1",
                   "kit_gate": "tp_report.installed with sharded-module calls > 0 and the rows census (rows_tiled) in every rank's worker log; refusals by name before launch (tp.check)"},
    # --- the fused MSA-module Triton kernels carried at forward/fpf_msa/: installed by the engine adapter boltz2_opt/msa_kernels.py through the bundle's own Boltz-2 entry points (fpf_msa.boltz2); attached by worker_launch --attach msa ---
    # --- atom-attention add-on: forward/atom/src/boltz_atom.py + boltz_atom_kernels.py (instance-level on structure_module; adapter boltz2_opt/atom.py; --attach atom, armed before the model is built) [ATOM track] ---
    "atom_keys_gather": {"kit": "forward/atom", "file": "forward/atom/src/boltz_atom.py", "lines": "GatherToKeys,_make_sample", "switch": "BOLTZ_ATOM", "value": "keys (a unit of the comma list)", "tier": 1,
                         "what": "the atom windowing `single_to_keys` (einsum of x with the [2K,8K] one-hot indexing matrix, 6x per denoiser step, O(M^2*D)) served by a gather kernel (out[b,k,s,:]=x[b,32k-48+s,:], +0.0 outside / for zeros) — bitwise: one-hot-or-empty by construction, fp32 'highest' IEEE products accumulated from +0.0, finite operand (documented precondition); handed to the sampler as the conditioning dict's to_keys",
                         "kit_gate": "fallback words keys_shape / keys_window_<W>x<H> (a window layout other than 32x128: the stock partial is served, counted)"},
    "atom_glue_hoist": {"kit": "forward/atom", "file": "forward/atom/src/boltz_atom.py", "lines": "_encoder_glue,_decoder_glue,_refresh", "switch": "BOLTZ_ATOM", "value": "glue (a unit of the comma list)", "tier": 1,
                        "what": "AtomAttentionEncoder/Decoder bodies verbatim with the step-invariant statements hoisted to each sample()'s eager first step (atom_to_token .float() / repeat_interleave / mean normalisation; the mean-weighted encoder bmm stays THE cuBLAS call on the same strided operand) and the decoder's one-hot broadcast bmm(atom_to_token, a_to_q) served by a row gather by token index (+0.0 canonical) — bitwise; cooperates with dit_hoist's c_m identity",
                        "kit_gate": "fallback word a2t_not_onehot (an atom_to_token matrix that is not one-hot-or-empty takes the stock bmm, counted; never by construction)"},
    "atom_fused": {"kit": "forward/atom", "file": "forward/atom/src/boltz_atom_kernels.py", "lines": "_k_adaln_qkvg,_k_win_attn,_k_out_transition,_k_segmean", "switch": "BOLTZ_ATOM", "value": "fused (a unit of the comma list)", "tier": 2,
                   "words": ("BOLTZ_ATOM_RELEASE",),                     # the lever's own placement word (graph | sample: the static buffers' lifetime); leaves the row with the lever (modes.take_off)
                   "what": "the diffusion module's atom encoder + decoder as 8 + 8 Triton launches per denoiser step: AdaLN+[q|k|v|g] projection, windowed attention per (32-query window, head) with the pair bias read in place from the [B,K,32,128,12] conditioning tensor and the pad mask by window arithmetic, out-projection+gated residual+AdaLN+SwiGLU transition+gated residual fused with the next layer's AdaLN+projection (or the encoder's relu-Linear tail / the decoder's LayerNorm-Linear tail), a deterministic segmented mean for atom->token and a gather-add for token->atom; per-sample() AdaLN/gate conditioning hoisted into static buffers (CUDA-graph safe); Tier 2 (another reduction order; supersedes the glue unit)",
                   "kit_gate": "refuses by name without triton; composes inside the roll-out / dit_hoist (instance forwards + a sample() epoch wrapper on the structure module)"},
    "atom_gemm": {"kit": "forward/atom", "file": "forward/atom/src/boltz_atom_kernels.py", "lines": "_mm", "switch": "BOLTZ_ATOM_GEMM", "value": "bf16 (ieee|tf32|tf32x3|bf16; absent = ieee)", "tier": 2,
                  "what": "PRECISION lever: the fused atom kernels' dot operand precision: bf16 operands and bf16 inter-kernel activations with fp32 accumulate / LayerNorm / softmax / residual stream where stock runs fp32 (tf32: fp32 storage, tf32 products; tf32x3 / ieee: fp32-class but slow in these kernels — documented, not a row word)",
                  "kit_gate": "only with the fused unit (the adapter refuses a precision word without it, by name)"},
    # --- the WASTE exact hoists of the MSA module's stock CHUNKED paths (> 384 tokens): forward/waste/boltz_waste_levers.py (verbatim boltz 2.2.1 bodies + the hoists; refuses on another boltz version or changed stock file sha256), installed by the engine adapter boltz2_opt/waste.py; attached by worker_launch --attach waste. WASTE owns the exact-tier MSA-module hoists [WASTE track] ---
    "waste_chunkcast": {"kit": "forward/waste", "file": "forward/waste/boltz_waste_levers.py", "lines": "_make_transition_forward,_make_pwa_forward,_make_opm_forward", "switch": "BOLTZ_WASTE", "value": "chunkcast (a unit of the comma list)", "tier": 1,
                        "what": "the bf16 cast autocast applies to the fp32 LayerNorm output ahead of EACH chunk matmul of the MSA module's chunked paths (at::autocast::cached_cast = Tensor.to(bf16), activations never cached) applied ONCE per call: the chunked pair / MSA Transition 16 -> 1 casts, PairWeightedAveraging 16 -> 1 (m) + 8 -> 1 (z), OuterProductMean proj 2 -> 1 — identical operands to the identical cuBLAS calls: bitwise; unchunked calls and the modules another adapter's forward owns are delegated / left alone BY NAME (over= / skipped= on the LEVER line: the fused transition's chunk-delegating dispatcher is wrapped, a foreign forward is not)",
                        "kit_gate": "waste_report: state per lever (on | skipped:<reason>), the calls / hoists counters and the fail-closed verdict (a lever switched on whose chunked calls ran must have hoisted)"},
    "waste_opmmask": {"kit": "forward/waste", "file": "forward/waste/boltz_waste_levers.py", "lines": "_make_opm_forward,_nummask_lookup", "switch": "BOLTZ_WASTE", "value": "opmmask (a unit of the comma list)", "tier": 1,
                      "what": "OuterProductMean's chunked-path `num_mask` (the [B,N,N,1] fp32 pair count of unmasked MSA rows: 128 chunk products of [64,N,N] summed; a function of feats['msa_mask'] and the MSA tensor's dtype only) computed by the identical statements ONCE per (mask tensor object, dtype) instead of on each of the 16 calls per prediction; the cache holds a weak reference to the mask tensor + its version counter (only the same live unmodified tensor hits; a new prediction's feats are new objects: no cross-item reuse), 8 MB at 1,400 tokens — bitwise",
                      "kit_gate": "waste_report: opm_nummask_computed / opm_nummask_reused and the fail-closed verdict (on but never reused over > 1 chunked call refuses)"},
    "waste_opmdiv": {"kit": "forward/waste", "file": "forward/waste/boltz_waste_levers.py", "lines": "_make_opm_forward", "switch": "BOLTZ_WASTE", "value": "opmdiv (a unit of the comma list)", "tier": 1,
                     "what": "OuterProductMean's chunk loop divides the einsum's PERMUTED 5-D view by num_mask straight into a contiguous fp32 buffer (torch.div(..., out=): the same element pairs, the same bf16->fp32 promotion, the same correctly-rounded division) so stock's `z.reshape(b, i, j, -1)` full copy of the bf16 chunk becomes a view: one copy kernel less per chunk (8 per call, 16 calls per prediction) — bitwise",
                     "kit_gate": "waste_report: opm_div_out counter and the fail-closed verdict (on but never used over a chunked call refuses)"},
    "waste_ctorskip": {"kit": "forward/waste", "file": "forward/waste/boltz_waste_levers.py", "lines": "_ctorskip_check,_trunc_normal_init_rng_only", "switch": "BOLTZ_WASTE", "value": "ctorskip (a unit of the comma list)", "tier": 1,
                       "what": "FIRST-OF-PROCESS: the model constructor's `initialize.trunc_normal_init_` (scipy truncnorm inverse-cdf over ~250 M Transition weights, ~18 s per Boltz2.__init__, every value then overwritten by load_state_dict(strict=True)) replaced by the one numpy draw it consumes (`uniform(size=size)` on numpy's global RandomState: the post-construction RNG state of torch CPU / numpy / python / CUDA and every parameter and buffer identical to the stock build); applied at the attachment, before the worker builds the model, and again in the fast worker's per-seed constructor replay; pinned by name (scipy series, rv_generic._rvs source, truncnorm not overriding _rvs, trunc_normal_init_ source) — a pin that does not hold leaves the stock init in place, named",
                       "kit_gate": "waste_report: ctorskip calls / elements and the fail-closed verdict (on but no constructor ran after apply refuses); state=skipped reason=<pin word> when the pinned facts do not hold"},
    # --- the second-generation MSA-module levers: forward/msa2 (trans2.py), installed by the engine adapter boltz2_opt/msa2.py (Transition.forward for the dim-64 / hidden-256 instances: the MSA transition and the template Pairformer's, every other Transition call handed to the forward installed before it); attached by worker_launch --attach msa2 after transition / waste / msa [MSA track] ---
    "msa_trans2": {"kit": ADAPTER, "file": f"{ADAPTER}/msa2.py", "lines": "_apply_trans2", "switch": "BOLTZ_MSA2", "value": "trans2 (a unit of the comma list)", "tier": 2,
                   "what": "the dim-64 / hidden-256 Transition (MSA transition + template pairformer transition) as ONE fused Triton kernel per call (forward/msa2/trans2.py MODE=0: LN -> fc1|fc2 -> SiLU*mul -> fc3 on-chip, hidden processed in register chunks, fp32 accumulation of the fc3 partials; stock: ~40 HBM passes per call, the hidden-chunked statements above 384 tokens); served for bf16 CUDA inputs in eval under autocast-bf16, else the previous forward BY NAME, counted; Tier 2 (rounding placement)",
                   "kit_gate": "msa2_report: units.trans2 state / trans2_census (served / calls / fallback_by) and the LEVER line; refuses by name beside trans2x (mutually exclusive)"},
    "msa_trans2_exact": {"kit": ADAPTER, "file": f"{ADAPTER}/msa2.py", "lines": "_apply_trans2", "switch": "BOLTZ_MSA2", "value": "trans2x (a unit of the comma list)", "tier": 1,
                         "what": "the same kernel in stock-rounding mode (forward/msa2/trans2.py MODE=1): the stock nn.LayerNorm statement, then ONE kernel = autocast's bf16 cast + fc1/fc2 slice GEMMs (tl.dot, bit-identical to cuBLAS's bf16 GEMM for K=64/32/256 at every M on sm_90 — the MSA-module levers' dot-band probe) + ATen's silu (x/(1+expf(-x)), div.rn, libdevice expf: exhaustively bit-identical over all bf16) + bf16 product + fc3 slice GEMMs + the bf16 partial-sum chain, in the caller's hidden chunking (32) or unchunked (K=256); RUN-TIME bit comparison: the first eager call of every (M rows, dtype, chunking) class runs the stock statements and the kernel on the same operand and torch.equal's them — equal serves the class for the process, unequal refuses it by name (the stock statements serve it, counted by class), a class first met under capture is served by stock (capture_unverified); pin refusal at apply (torch / cc); per-box test tests/test_msa2_trans2.py",
                         "kit_gate": "msa2_report: units.trans2x state / trans2_census (served / calls / fallback_by) and the LEVER line; the previous forward BY NAME outside eval / CUDA autocast-bf16; under the lock discipline in force since 0.3.2: a size floor by name (small_class), every call bit-compared and the stock output returned until >= 1e6 output elements compared equal per class (a selecting compare locks only a uniquely matching candidate), first mismatch refuses the class by name"},
    "msa_pwa_exact": {"kit": ADAPTER, "file": f"{ADAPTER}/msa2.py", "lines": "_apply_pwa2x", "switch": "BOLTZ_MSA2", "value": "pwa2x (a unit of the comma list)", "tier": 1,
                      "what": "PairWeightedAveraging as two fused Triton kernels in stock-rounding mode (opt_core.ops.msa_pwa2: the v|g projections + the softmax-weighted sum per head with ATen's roundings), RUN-TIME bit comparison per (S, N, chunking) class at the first eager call (equal serves the class, unequal refuses it by name: the stock forward serves, counted bitcmp_failed:<class>); pin-scoped like trans2x — an AVAILABLE word, in no mode row",
                      "kit_gate": "msa2_report: units.pwa2x state and the LEVER line; the previous forward BY NAME outside eval / CUDA autocast-bf16; under the lock discipline in force since 0.3.2: a size floor by name (small_class), every call bit-compared and the stock output returned until >= 1e6 output elements compared equal per class (a selecting compare locks only a uniquely matching candidate), first mismatch refuses the class by name"},
    # --- CONF track: the modules after the trunk / outside the sampler / at the front (opt/forward/conf; adapter boltz2_opt/conf.py, attached by worker_launch --attach conf; switch BOLTZ_CONF = comma list, one word per lever). condproj is the fast row's; tfeat / tdummy are PARKED available words in no row (tdummy is input-conditional, which keeps it out of every row) ---
    "condproj": {"kit": ADAPTER, "file": "forward/conf/cond_levers.py", "lines": "-", "switch": "BOLTZ_CONF", "value": "condproj (a unit of the comma list)", "tier": 2,
                 "what": "DiffusionConditioning's pair-bias projections (diffusion_conditioning.py:101-114: 24 token-transformer-layer and 3+3 atom-layer Sequential(LayerNorm, Linear bias-free) over the conditioned pair tensor z [N²,128] and the atom pair tensor p, then torch.cat) computed per list as ONE affine-free LayerNorm pass (the lists' LayerNorms share their statistics: same input) and ONE GEMM against the folded weight cat_l(W_l·diag γ_l) with bias cat_l(W_l β_l) — exact in real arithmetic, bf16 rounding differs (Tier 2)",
                 "kit_gate": "conf_report + LEVER line (calls / token_lists_fused / atom_lists_fused / layers_folded); a DiffusionConditioning that is not the pinned structure refuses by name at its first call"},
    "tfeat": {"kit": ADAPTER, "file": "forward/conf/template_levers.py", "lines": "-", "switch": "BOLTZ_CONF", "value": "tfeat (a unit of the comma list) — NOT in any row (parked: exact, ≈ −4/−13/−20 ms/item)", "tier": 1,
              "what": "TemplateV2Module.forward's recycle-invariant featurization (trunkv2.py:415-478: cdist distogram one_hot, frame unit vectors, pair masks, res_type expands, the fp32 a_proj GEMM, the expanded pair mask) computed at the first of the recycling loop's template calls and reused by the later ones of the same Boltz2.forward (same feats, same pair_mask); the reused tensors are the first call's own — bitwise",
              "kit_gate": "conf_report in the worker log + the lever's LEVER line (calls / featurize_computed / featurize_reused / forwards); an unknown BOLTZ_CONF word refuses by name at attach"},
    "tdummy": {"kit": ADAPTER, "file": "forward/conf/template_levers.py", "lines": "-", "switch": "BOLTZ_CONF", "value": "tdummy (a unit of the comma list) — NOT in any row: input-conditional", "tier": 1,
               "what": "when no template slot of the batch is live (feats['template_mask'] all zero: the featurizer's dummy slot), TemplateV2Module's update u is +0.0 in every element (v*0 -> sum -> /1 -> relu -> bias-free u_proj: MMA of signed zeros onto +0.0), so the call is replaced by its 2-layer pairformer's eight get_dropout_mask torch.rand draws (same shapes/dtype/order: the Philox stream advances as in stock) and a zeros tensor of u's dtype (the caller's z + u stays the same z + 0.0 pass)",
               "kit_gate": "conf_report + LEVER line (calls / elided / live / rng_draws_replayed); one host sync per prediction reads the predicate"},
    "fpf_opm": {"kit": ADAPTER, "file": f"{ADAPTER}/msa_kernels.py", "lines": "-", "switch": "BOLTZ_FPF_MSA", "value": "opm (a unit of the comma list; + BOLTZ_FPF_MSA_OPM_CFG=<fpf_msa.opm.CFG_VARIANTS name>, default the bundle's f1: TMA + fused prologue, Triton >= 3.4, else its p8 pointer layout)", "tier": 2,
                "what": "the MSA module's outer-product-mean (OuterProductMean.forward) as ONE fused Triton kernel (the shared core's opt_core.ops.msa_opm, form mask_norm): LayerNorm + proj_a/proj_b + mask in a prologue kernel, then the outer-product GEMM over the MSA depth with the c_hidden² -> c_z output projection, the bias and / num_mask applied in the GEMM's epilogue — the [N, N, c_hidden²] outer product (stock above 384 tokens: eight [N, N, 128] fp32 slabs written, divided, cast to bf16 and projected, the projections accumulated in bf16) never reaches HBM; bf16 tensor-core operands rounded at stock's autocast points, fp32 accumulation in another tile order: not bitwise, run-to-run reproducible",
                "kit_gate": "the core ledger's census and fail-closed gate per unit (opt_core.counters Ledger: served / fallback_by / errors / shapes; no expected stock path — Boltz-2 builds one OuterProductMean of the kernel's pinned widths, every call is served) written as msa_report (with the tile configuration that served: cfg / tma / triton) into the worker log and printed as the lever's LEVER line; a declined call (the bundle's FPFFallback words rank_or_device / dims_not_pinned) or a kernel error refuses the exit verdict; a GPU out-of-memory error propagates; refused by name at apply beside BOLTZ_OPM_ROWS=1 or BOLTZ_FPF_STACK, or when a carried fpf_msa file is missing"},
    # --- the persistent featurizer of the pipelined worker: boltz2_opt/prefetch.py, attached by worker_launch --attach prefetch (LAST in the attach list) ---
    # --- boltz2_opt/writer.py: the output writer off the critical path (attached by worker_launch --attach writer; bz_worker_lev*.py begin_item / finish_item / wait_item / collect / join) ---
    "writer_overlap": {"kit": ADAPTER, "file": f"{ADAPTER}/writer.py", "lines": "-", "switch": "BOLTZ_WRITER", "value": "overlap (+ ,thread: the diagnostic in-process backend)", "tier": 1,
                       "what": "boltz's BoltzWriter.write_on_batch_end and the worker's per-seed file move run off the predicting thread: every tensor the writer reads (coords, masks, plddt, pae, pde, "
                               "the confidence scalars, pair_chains_iptm; s / z with embeddings) is copied device-to-host into pinned buffers non_blocking on a side stream behind one event where stock "
                               "calls the writer, and ONE writer process (a grandchild of the pre-CUDA parsing zygote, one unix-socket connection) runs the SAME writer function on the host copies "
                               "(np.savez_compressed pae / pde / plddt, to_mmcif, the confidence json: same calls, dtypes, order) and the move while the next item predicts; byte-identical outputs "
                               "by construction (only where the host reads happen moves; a tied / NaN ranking score at diffusion_samples > 1 and a prediction boltz skipped take the stock call inline, by name)",
                       "kit_gate": "pipeline=1 only (pipeline 0: Lightning's own loop, named); no zygote or a failed spawn leaves the stock call by name; join before EXIT is mandatory: a background write "
                                   "or move that raised fails its (input, seed) unit by name and the worker exits non-zero; a writer process that dies fails the units it held and every later item is "
                                   "written inline (fallback_by=helper_died, gate refused); off by name at n_gpu > 1 (TP_DROPS)"},
    "prefetch": {"kit": ADAPTER, "file": f"{ADAPTER}/prefetch.py", "lines": "-", "switch": "BOLTZ_PREFETCH", "value": "persistent (+ ,nopin: leave the batch pageable)", "tier": 1,
                 "what": "the next input is featurized in ONE helper process spawned once through the input-preparation zygote (forked before CUDA exists; stock PredictionDataset + collate, torch's worker-0 seeding replayed per input, base_seed drawn where the stock iterator draws it) instead of a DataLoader worker forked from the CUDA process before every input; featurized bytes and outputs identical, the copy-on-write tax on the predicting process gone",
                 "kit_gate": "pipeline=1 only (pipeline 0: Lightning's own loader, named); no zygote or a failed spawn refuses by name; the first served input is bit-compared with the stock loader's batch (differing bytes refuse the lever by name for the rest of the process); a helper that dies or raises hands that input to the stock DataLoader, counted (prefetch_report: served / fallback_by / forks_avoided / ref_forks / bit_compare; fail-closed gate)"},
    "fpf_pwa": {"kit": ADAPTER, "file": f"{ADAPTER}/msa_kernels.py", "lines": "-", "switch": "BOLTZ_FPF_MSA", "value": "pwa (a unit of the comma list; + BOLTZ_FPF_MSA_PWA_CFG=<fpf_msa.pwa.CFG_VARIANTS name>, default the bundle's)", "tier": 2,
                "what": "the MSA module's pair-weighted averaging (PairWeightedAveraging.forward) fused (the shared core's opt_core.ops.msa_pwa, form masked): the LayerNorm / proj_m / proj_g / sigmoid prologue, the pair-bias softmax per head, the weighted average over token columns and the gated proj_o epilogue in Triton kernels — the eight per-head [N, N] weight maps and the [S, N, c_h·heads] average are the only intermediates (stock materializes proj_z(LN(z)) [N, N, heads], the bf16/fp32 casts and the per-head-chunk einsum outputs); bf16 operands, fp32 accumulation: not bitwise, run-to-run reproducible; its prologue workspace raises the worker's allocator peak by ~5 % at 400-1000 tokens",
                "kit_gate": "as fpf_opm (msa_report.units.pwa; Boltz-2 builds its PairWeightedAveraging modules of the kernel's pinned widths in the MSA module only)"},
    # --- PRECISION track: the fast tier's precision units (opt/forward/precision/boltz2_precision.py; adapter boltz2_opt/precision.py, attached by worker_launch --attach precision; switch
    # BOLTZ_PRECISION = comma list, one word per unit, `off:<unit>` = the row's ablation entry: LEVER state=off reason=ablation, the stock statement untouched). Tier 2 every one:
    # declared reduced precision where upstream runs IEEE fp32 ('highest'). dit_tf32 is the fast row's word; dit_bf16 / dit_attn_bf16 / seq_bf16 are AVAILABLE
    # words in no row (bank-clean, gated; dit_bf16 = the reference implementation of the bf16-with-pins policy SAMPLER/ATOM's kernels are held to; dit_attn_bf16 loses time at >= 1000
    # tokens beside the hoist; seq_bf16 is speed-neutral with an SDPA core at head_dim 24). [PRECISION]
    "dit_tf32": {"kit": ADAPTER, "file": f"{ADAPTER}/precision.py", "lines": "-", "switch": "BOLTZ_PRECISION", "value": "dit_tf32 (a unit of the comma list) — the fast row's word", "tier": 2,
                 "what": "PRECISION lever: TF32 tensor-core products for the diffusion score model's remaining IEEE-fp32 cuBLAS GEMMs (torch.backends.cuda.matmul.allow_tf32 set on entry to the DiffusionModule call and restored in `finally`, asserted back to stock's (False, 'highest') after every call; the process policy elsewhere stays 'highest'): beside dit_fused / atom_fused it covers what those kernels do not replace (single/pairwise conditioner GEMMs, s_to_a / a_norm projections, atom<->token pooling, whatever runs on the stock statements); alone it is every score-model GEMM (kit-route sampler wall -47/-50/-42 %% at 400/1000/1400 tokens; yardstick bank v1 PASS 10/10, lDDT 1.000 vs stock seed on 9 of 10 core targets)",
                 "kit_gate": "precision_report + LEVER line (calls / flag_restored — the gate refuses unless flag_restored == calls and the process matmul policy reads stock's at exit); never in an exact row"},
    "dit_bf16": {"kit": ADAPTER, "file": f"{ADAPTER}/precision.py", "lines": "-", "switch": "BOLTZ_PRECISION", "value": "dit_bf16 (a unit of the comma list) — available, in no row", "tier": 2,
                 "what": "PRECISION lever (reference implementation of the bf16 policy): the diffusion score model under bf16 autocast instead of stock's fp32 island (boltz2.py:532): GEMM operands bf16 with fp32 accumulation, LayerNorm/softmax statistics and residual streams fp32, the inner fp32 islands kept; pinned fp32 by the unit: the coordinate read r_to_q_trans, the noise-level FourierEmbedding, the position-update head; SingleConditioning's two Transition(768,1536) on the stock statements at instance level so the fused-transition adapter never sees the unpinned cell (it engaged opt_core's process-wide safe settings: CR5)",
                 "kit_gate": "precision_report + LEVER line (calls / pin_r_to_q / pin_pos_update / pin_fourier / sc_transition_stock / out_upcast); superseded in the row by dit_fused + atom_fused"},
    "dit_attn_bf16": {"kit": ADAPTER, "file": f"{ADAPTER}/precision.py", "lines": "-", "switch": "BOLTZ_PRECISION", "value": "dit_attn_bf16 (a unit of the comma list) — available, in no row", "tier": 2,
                      "what": "PRECISION lever: the token transformer's 24 pair-biased attention cores as one fused bf16 scaled-dot-product attention (bias + key-padding term materialised once per call in bf16, softmax statistics and P.V accumulation fp32 in the kernel) instead of the fp32 einsum/softmax/einsum over materialised [16,N,N] logits (attentionv2.py:99-107); bank-clean, but +0.8/+2.3 s sampler at 1000/1400 tokens beside the hoist's cached-bias path (head_dim 24) — off",
                      "kit_gate": "precision_report + LEVER line (calls); inert where dit_fused replaces the token transformer"},
    "seq_bf16": {"kit": ADAPTER, "file": f"{ADAPTER}/precision.py", "lines": "-", "switch": "BOLTZ_PRECISION", "value": "seq_bf16 (a unit of the comma list) — available, in no row", "tier": 2,
                 "what": "PRECISION lever: the Pairformer sequence attention (pairformer.py:105-109: AttentionPairBias with its LayerNorm + 128->16 pair-bias projection of z, trunk 64x4 + confidence 8 calls) under bf16 autocast with a bf16 SDPA core instead of the fp32 island; logits/softmax statistics fp32, the s residual handed back fp32; bank-clean (median d pLDDT -0.1), trunk -1.6..+3.3 %% (speed-neutral: the lever there is a pair-bias flash kernel) — off",
                 "kit_gate": "precision_report + LEVER line (attn_calls)"},
}


# The per-lever ids the LEVER grammar prints (opt_core.report.lever_line, report.lever_lines): ``strategy`` = the canonical id of
# opt_core/STRATEGIES.json this lever implements, or ``LOCAL.boltz2.<name>`` for a lever no other kit shares; ``origin`` = where the
# implementation lives (``kit``: a carried file of this tree; ``core``: an opt_core primitive or kernel this kit's adapter composes);
# ``impl`` = the file (opt/-relative) or module a reader opens.
LEVER_IDS: Dict[str, dict] = {
    "resid": {"strategy": "LOCAL.boltz2.eval_residual_fold", "origin": "kit"},
    "mask2": {"strategy": "LOCAL.boltz2.trivial_mask_elision", "origin": "kit"},
    "flash_triattn": {"strategy": "F1.flash_triatt", "origin": "core", "impl": "opt_core.attn.pair_fused:core(default|k2b|flash_triattn)"},   # fast: the fused block's own keyed attention core (k2b / flash by word) (opt_core.attn.pair_fused core=k2b); big: opt_core.kernels flash_triattn through the trunk kit's patch; both the core's carried copies, routed by name
    "graph_sampler": {"strategy": "F3.cuda_graph_sampler", "origin": "kit"},
    "dit_hoist": {"strategy": "LOCAL.step_invariant_hoist", "origin": "kit"},
    "fpf_trimul": {"strategy": "F2.fpf_trimul_fast", "origin": "core", "impl": "opt_core.trimul:by_word(fast|big)"},
    "fpf_trimul_exact": {"strategy": "F2.fpf_trimul_exact", "origin": "core", "impl": "opt_core.trimul:by_word(exact)"},
    "fused_transition": {"strategy": "LOCAL.fused_transition", "origin": "core", "impl": "opt_core.kernels.transition"},
    "pairblock": {"strategy": "F1.triatt_lean_exact", "origin": "core", "impl": "opt_core.attn.pair_fused:tri_attn_block"},
    "triattn_exact": {"strategy": "LOCAL.boltz2.triattn_exact", "origin": "core", "impl": "opt_core.kernels.triattn:triangle_attention(word=exact)"},   # the exact tier word over the block's library core: the vouched exact-class row or the library op, per cell
    "templ_skip": {"strategy": "LOCAL.boltz2.templ_skip", "origin": "kit", "impl": "boltz2_opt/templskip.py"},   # the all-dummy template pass elided (its update is the zero tensor by construction)
    "pairblock_c64": {"strategy": "LOCAL.boltz2.pairblock_c64", "origin": "core", "impl": "opt_core.attn.pair_fused:tri_attn_block"},   # the template C=64 stack on the qualified (64,4,32) cells inside the F1 lean block, Tier-2 variants only
    "xl_trans": {"strategy": "F7.chunked_eval", "origin": "core", "impl": "opt_core.mem.chunk:pair_transition_chunked"},
    "xl_cond": {"strategy": "F7.chunked_eval", "origin": "core", "impl": "opt_core.mem.chunk:chunk_rows"},
    "xl_free": {"strategy": "F7.chunked_eval", "origin": "kit", "impl": f"{ADAPTER}.big:xl_free"},
    "relpos_lazy": {"strategy": "F7.chunked_eval", "origin": "kit", "impl": f"{ADAPTER}.big:relpos_lazy"},
    "expandable_segments": {"strategy": "F7.expandable_segments", "origin": "core", "impl": "opt_core.mem.allocator"},
    "rowpair_tp": {"strategy": "F7.tensor_parallel", "origin": "core", "impl": "opt_core.mem.rowpair"},
    "fpf_opm": {"strategy": "LOCAL.boltz2.fused_outer_product_mean", "origin": "core", "impl": "opt_core.ops.msa_opm:forward_mask_norm"},
    "fpf_pwa": {"strategy": "LOCAL.boltz2.fused_pair_weighted_averaging", "origin": "core", "impl": "opt_core.ops.msa_pwa:forward_masked"},
    "exactln": {"strategy": "LOCAL.boltz2.exact_layer_norm_replica", "origin": "core", "impl": "opt_core.kernels.ln:exactln/exactln_fwd.cu"},              # the core's row serves every mode
    "exactln_resid": {"strategy": "LOCAL.boltz2.exact_residual_layer_norm_fusion", "origin": "core", "impl": "opt_core.kernels.ln:exactln/exactln_fwd.cu"},
    "graph_trunk": {"strategy": "LOCAL.boltz2.cuda_graph_trunk", "origin": "kit"},
    "rollout": {"strategy": "LOCAL.boltz2.rollout_boundary_graph", "origin": "kit", "impl": f"{ADAPTER}.sampler:rollout"},
    "align_jacobi64": {"strategy": "LOCAL.boltz2.align_jacobi64", "origin": "kit", "impl": f"{ADAPTER}.sampler:align_jacobi64"},
    "align_aligncap": {"strategy": "LOCAL.boltz2.align_aligncap", "origin": "kit", "impl": f"{ADAPTER}.sampler:align_aligncap"},
    "dit_fused": {"strategy": "LOCAL.boltz2.dit_fused_bf16", "origin": "kit", "impl": f"{ADAPTER}.sampler:dit_fused"},
    "dit_par": {"strategy": "LOCAL.boltz2.dit_parallel_branches", "origin": "kit", "impl": "forward/ditexact/src/dx_token.py:Schedule"},
    "dit_mask": {"strategy": "LOCAL.boltz2.dit_token_mask_elision", "origin": "kit", "impl": "forward/ditexact/src/dx_token.py:Schedule"},
    "dit_sba": {"strategy": "LOCAL.boltz2.dit_fused_scale_bias_mask", "origin": "kit", "impl": "forward/ditexact/src/dx_token.py:scale_bias_mask"},
    "dit_smx": {"strategy": "LOCAL.boltz2.dit_fused_softmax_replica", "origin": "kit", "impl": "forward/ditexact/src/dx_token.py:softmax_scale_bias_mask"},
    "dit_glue": {"strategy": "LOCAL.boltz2.dit_fused_glue_replicas", "origin": "kit", "impl": "forward/ditexact/src/dx_token.py:glue_affine"},   # [DITEXACT]
    "pairfuse": {"strategy": "LOCAL.boltz2.pairfuse", "origin": "kit", "impl": "forward/pairfuse/bz_pairfuse.py"},
    "atom_keys_gather": {"strategy": "LOCAL.boltz2.onehot_gather", "origin": "kit", "impl": "forward/atom/src/boltz_atom.py:GatherToKeys"},
    "atom_glue_hoist": {"strategy": "LOCAL.step_invariant_hoist", "origin": "kit", "impl": "forward/atom/src/boltz_atom.py:_encoder_glue"},
    "atom_fused": {"strategy": "LOCAL.dit_fused_kernels", "origin": "kit", "impl": "forward/atom/src/boltz_atom_kernels.py"},
    "atom_gemm": {"strategy": "F4.bf16_weight_precast", "origin": "kit", "impl": "forward/atom/src/boltz_atom_kernels.py:_mm"},
    "waste_chunkcast": {"strategy": "LOCAL.boltz2.msa_chunk_cast_hoist", "origin": "kit", "impl": "forward/waste/boltz_waste_levers.py:_make_pwa_forward"},
    "waste_opmmask": {"strategy": "LOCAL.boltz2.opm_num_mask_hoist", "origin": "kit", "impl": "forward/waste/boltz_waste_levers.py:_make_opm_forward"},
    "waste_opmdiv": {"strategy": "LOCAL.boltz2.opm_div_into_contiguous", "origin": "kit", "impl": "forward/waste/boltz_waste_levers.py:_make_opm_forward"},
    "waste_ctorskip": {"strategy": "LOCAL.boltz2.constructor_init_draws_only", "origin": "kit", "impl": "forward/waste/boltz_waste_levers.py:_trunc_normal_init_rng_only"},
    "msa_trans2": {"strategy": "LOCAL.boltz2.fused_transition64", "origin": "kit", "impl": "forward/msa2/trans2.py:transition64"},
    "msa_trans2_exact": {"strategy": "LOCAL.boltz2.fused_transition64_exact", "origin": "kit", "impl": "forward/msa2/trans2.py:transition64"},
    "msa_pwa_exact": {"strategy": "LOCAL.boltz2.fused_pair_weighted_averaging_exact", "origin": "core", "impl": "opt_core.ops.msa_pwa2:pwa_forward"},
    "condproj": {"strategy": "LOCAL.boltz2.cond_shared_ln_folded_projection", "origin": "kit", "impl": "forward/conf/cond_levers.py:forward_condproj"},
    "tfeat": {"strategy": "LOCAL.boltz2.template_featurize_hoist", "origin": "kit", "impl": "forward/conf/template_levers.py:forward_conf"},
    "tdummy": {"strategy": "LOCAL.boltz2.template_all_dummy_elision", "origin": "kit", "impl": "forward/conf/template_levers.py:forward_conf"},
    "writer_overlap": {"strategy": "LOCAL.boltz2.writer_overlap", "origin": "kit", "impl": f"{ADAPTER}.writer"},
    "prefetch": {"strategy": "LOCAL.boltz2.persistent_featurizer", "origin": "kit", "impl": f"{ADAPTER}.prefetch"},
    "dit_tf32": {"strategy": "LOCAL.boltz2.precision_dit_tf32", "origin": "kit", "impl": "forward/precision/boltz2_precision.py:_dm_call"},          # [PRECISION]
    "dit_bf16": {"strategy": "LOCAL.boltz2.precision_dit_bf16", "origin": "kit", "impl": "forward/precision/boltz2_precision.py:_dm_call"},
    "dit_attn_bf16": {"strategy": "LOCAL.boltz2.precision_dit_attn_bf16", "origin": "kit", "impl": "forward/precision/boltz2_precision.py:_apb_token_bf16"},
    "seq_bf16": {"strategy": "LOCAL.boltz2.precision_seq_bf16", "origin": "kit", "impl": "forward/precision/boltz2_precision.py:_apb_call"},
}
for _name, _row in LEVERS.items():
    _ident = LEVER_IDS[_name]
    _row["strategy"], _row["origin"] = _ident["strategy"], _ident["origin"]
    _row["impl"] = _ident.get("impl", _row["file"])
MEMORY_LEVERS = tuple(n for n, r in LEVERS.items() if r["file"] == f"{ADAPTER}/big.py")   # the memory modes' levers (the engine adapter boltz2_opt.big): xl_report is their evidence


def tier_of(levers) -> int:
    """The tier of a lever list: 2 when any lever is Tier 2, else 1 (an empty list is stock: 0)."""
    if not levers:
        return 0
    return max(LEVERS[n]["tier"] for n in levers)
