"""Lever registry: metadata for every optimization the modes compose, keyed by the switches the kit's own files set.

No values live here. The trunk switches are exported by the kit's `opt/forward/flashpairformer/env.sh` (modes.resolve() sources it);
the per-(cc | triton) row switches of the kit README (E*/T*: pad8, glue v2, MK-PF, the tri-attention tier word) and lazy init are exported by
modes.resolve() around env.sh (modes.README_ROWS). Every lever is a switch of the CLI route (`protenix pred` with the kit's
sitecustomize active); each entry names the env.sh line or kit document it was read from (code comments).
`tests/test_modes_match_env_sh.py` sources env.sh and fails when the set of variables the registry claims for a mode drifts from what
env.sh exports, and locks every README row against modes.resolve().
"""
from dataclasses import dataclass
from typing import Dict, Tuple

FORWARD = "forward"                       # opt/forward/: the kit class every lever belongs to
EXACT, TOLERANCE = "exact", "tolerance"


@dataclass(frozen=True)
class Lever:
    name: str
    cls: str                              # forward
    tier: str                             # exact | tolerance
    env_keys: Tuple[str, ...]             # the switches this lever reads (names only; values come from env.sh / modes.EXTRAS)
    description: str
    cells: str                            # the dispatch envelope the kit documents for this lever (its own cells / gates)
    probe: str = "env"                    # activation evidence: "env" (the kit reads the switch lazily) or "marker" (see stack.MARKERS)
    conditional: Tuple[str, ...] = ()     # switches env.sh exports only after a runtime probe (compute capability, installed torch)
    extra: bool = False                   # exported by modes.resolve() around env.sh (README row switches, lazy init), not by env.sh itself
    row_dependent: bool = False           # part of the arm only on the kit README rows that list one of its switches (modes.README_ROWS)
    source: str = ""                      # where the switch was read
    replaced_by: Tuple[str, ...] = ()       # levers that take this lever's slot on the rows that list them (k2b_flash_triattention -> triattn_cuda on cc 9.0): there this lever is not part of the arm (stack._classify), never a fallback
    requires: Tuple[str, ...] = ()          # levers this one modifies and cannot run without (a precision lever on a kernel lever): switched on only with them, ablated only with them (refused by name otherwise)
    words: Tuple[Tuple[str, str], ...] = ()          # (switch, word) pairs for a lever selected by the VALUE of a switch (PTX_T_ATT=native read BY env.sh; PTX_TRIMUL=exact|tier / PTX_TEMPL_TRIMUL exported by it): in_row() then requires the row / env.sh to export one of these words, not merely the switch
    subsumes: Tuple[Tuple[str, str, str], ...] = ()   # census interactions: (lever whose call site this lever takes over, that lever's counter, its expected value while this lever is on) — report.lever_lines re-bases the subsumed lever's line, never reads it as a fallback


def _lever(*a, **k) -> Lever:
    return Lever(*a, **k)


LEVERS: Dict[str, Lever] = {lv.name: lv for lv in [
    # ---- both arms (env.sh lines outside the ARM conditional) ---------------------------------------------------------------------
    _lever("layernorm_fast", FORWARD, EXACT, ("LAYERNORM_TYPE",),
           "Protenix fast LayerNorm CUDA extension (the stock CLI default).", "stock default", source="env.sh L5"),
    _lever("cueq_tuned_tiles", FORWARD, EXACT, ("CUEQ_TRITON_CACHE_DIR",),
           "Levers add-on L1: cuEquivariance TriMul Triton tile choices served from the kit's autotune cache (cueq_cache/*.json, generated by running "
           "the library's own autotuner on our cards over this model's shapes; kit-generated data, no NVIDIA SDK data) as a pure lookup — same kernel, "
           "same per-element arithmetic (CUEQ_TRITON_TUNING must stay unset). The LEVER line's tiles= pair states whether a table for the running "
           "card is present (report.cueq_tiles_evidence); a card without one reads the library's packaged table.",
           "sm90 (cueq_cache/*.9.0.json), sm100 and sm103 (cueq_cache/*.10.0.json) — kit-generated tables; other cards: packaged defaults", source="env.sh L7"),
    _lever("template_dedupe", FORWARD, EXACT, ("PTX_TEMPL_DEDUPE",),
           "Levers add-on L2: template distinct-evaluation (duplicate templates embedded once).", "exact",
           probe="marker", source="env.sh L7; sitecustomize L103-107"),
    _lever("t1_fused_transition", FORWARD, EXACT, ("PTX_T1_TRANS",),
           "Transition silu*mul as one Triton kernel with the stock rounding points inside the stock two-GEMM body: the forward the transition_core levers find at "
           "install — it serves, by name, the calls the provider hands back (stock cells, refusals, shapes without a cell word). The one-kernel transition is the shared "
           "core's row (opt_core.kernels.transition v1 / flash_sm90a / v2 ... by tier word); this kit carries no transition kernel cell.",
           "exact (elementwise, stock rounding points)", probe="marker", source="env.sh L8"),
    _lever("nomask", FORWARD, EXACT, ("PTX_NOMASK",),
           "Mask removal on the unmasked tri-attention call (pair_mask=None).", "exact; PTX_SM100F_GUARD auto on cc 10.x",
           probe="marker", source="env.sh L8, L42"),
    _lever("blk2_block_path", FORWARD, EXACT, ("PTX_BLK",),
           "Block-level Pairformer path: fusion prologue v3 + cuEq core + epilogue v4 + the in-block pair transition through opt_core.kernels.transition by the mode's tier word (transition_core levers).",
           "CELLS.json blk2_arch; stock sub-path for any op without a cell; the stock tri-attention statement below CELLS.json blk2_triatt_min_tokens on an arch with a row (sm80: 400 tokens), by name", probe="marker", source="env.sh L8"),
    _lever("pwa_zcache", FORWARD, EXACT, ("PTX_PWA_ZCACHE",),
           "Zero-template pair-weighted-average cache (ptx_msa_adapt).", "exact", probe="marker", source="env.sh L8"),
    _lever("blk2_chunked_exact", FORWARD, EXACT, ("PTX_BLK_CHUNKED",),
           "Chunked block core (exact chunking).", "exact", probe="marker", source="env.sh L8 (ARM=E default 1)"),
    _lever("deadskip", FORWARD, EXACT, ("PTX_DEADSKIP",),
           "Skip the 41 checkpoint modules whose weights are ~1e-37 (outputs exactly 0).",
           "exact by construction (the skipped modules' outputs are exactly 0)", probe="marker", source="env.sh L23 (DEADSKIP=0 disables)"),
    _lever("lever_report", FORWARD, EXACT, ("PTX_LEVER_REPORT",),
           "JSON line of applied levers + call counters per process (evidence that the levers ran).", "n/a", source="env.sh L24"),
    _lever("trimul_core_exact", FORWARD, EXACT, ("PTX_TRIMUL", "FPF_OPS"),
           "The pair-stack triangle multiplication (c_z 256: the 48 pairformer blocks, the MSA module's pair stack, the confidence head's pairformer; both "
           "directions) through the shared core's ONE TriMul provider by the TIER word exact — opt_core.kernels.trimul by_word(weights_of, 'exact'): the "
           "cell's exact tier row on this card and stack (native_exact where its bytes are vouched on this stack; tx_sm90a_exact / tmk3_exact / the library "
           "op BY NAME where the table says so — beyond the vouched size envelope the word IS the library op, named on the census line). FPF_OPS "
           "trimul_out / trimul_in = src/ptx_trimul_routes.py (PTX_TRIMUL=exact, exported by env.sh under ARM E); one opt_core.trimul.Lever, min_tokens 101 "
           "(the library's torch branch below keeps the stock forward, counted); LEVER line impl=trimul:<row>@exact/<cell> bind=tier:exact. The kit carries "
           "no TriMul kernel for these sites (protenix_opt 0.3.51: fpf_trimul_exact, protenix_fpf_trimul_tx, fpf_trimul, fpf_trimul_v4 retired to the core's rows).",
           "EXACT class: the provider serves a row under the word exact only where the core's cell table records its bitwise vouch against the library op on "
           "this stack (class bitwise≡cueq); a call outside every vouched cell is the library op by name (NAMED on the FIRST / LEVER lines, counted fallback_by)",
           probe="marker", words=(("PTX_TRIMUL", "exact"),), replaced_by=("trimul_core",),
           source="env.sh (ARM=E: PTX_TRIMUL=exact, FPF_OPS=ptx_trimul_routes); opt/forward/flashpairformer/src/ptx_trimul_routes.py; opt_core/kernels/trimul (TRIMUL_CELLS.json)"),
    _lever("stackgraph", FORWARD, EXACT, ("PTX_BLK_GRAPH", "PTX_BLK_GRAPH_MAX"),
           "CUDA graph of the 48-block Pairformer stack (<= 448 tokens, PTX_BLK_GRAPH_MAX=auto).", "<= 448 tok",
           probe="marker", source="env.sh L53-55"),
    _lever("sampler_graph", FORWARD, EXACT, ("PTX_SAMPLER_GRAPH", "PTX_SAMPLER_HOIST", "PTX_SAMPLER_GRAPH_MAXTOK"),
           "CLI-path graphed diffusion sampler + DiT step-invariant hoist (exact/fast: <= modes.SAMPLER_GRAPH_MAXTOK = 1536 tokens on a device with >= 64 GiB of memory, <= the kit's own default 995 on a smaller one: modes.sampler_graph_maxtok; above the cap and in big the route is chosen per item by `sampler_admit`).",
           "exact by construction (RNG drawn outside the graph in stock order)", probe="marker", source="env.sh L58-59"),
    _lever("sampler_prep", FORWARD, EXACT, ("PTX_SAMPLER_PREP",),
           "Host path of the graphed diffusion sampler: pinned non-blocking upload of the per-step rotation, shape-keyed graph cache with on-device "
           "comparison of integer/mask feature values, one warm-up pass, poison self-test once per process, the previous entry's static buffers released "
           "before a new capture and its pool re-used when the new signature is no larger (else returned to the device first), vectorised per-step scalars "
           "(infopt_graphs.protenix.sampler_prep PARTS: all six or none — the end-of-run record's prep= word must name every part or the lever is a fallback by name).",
           "exact by construction (no kernel, RNG draw or graph changes; byte-identical outputs under the deterministic recipe)",
           probe="env", source="env.sh L66; opt/forward/flashpairformer/src/infopt_graphs/protenix/sampler_prep.py, graphed.py (lever sampler_prep[...] sites), src/fpf_clisampler/clisampler.py (record prep / prep_poison / prep_stats)"),
    _lever("sampler_reach", FORWARD, EXACT, ("PTX_SAMPLER_REACH",),
           "Reach of the graphed diffusion sampler above its static token cap: above REACH_FLOOR_TOKENS = 1536 the graphed loop asks the kit's per-item sampler "
           "admission policy (fpf_clisampler.policy: lever sampler_admit) which route to run — graph (only inside the graph cap: the cap STAYS 1536 tokens on a "
           "card with >= 64 GiB, the kit default below; the graphed step is never taken outside its exercised envelope), hoist_eager (the step-invariant hoist "
           "bound around the stock eager sampler) or stock — releases what the item admitted after its sampler and prints the policy's ADMIT / SAMPLER-MEM audit "
           "lines; at or below the floor nothing changes (infopt_graphs.protenix.sampler_prep, switch read with PTX_SAMPLER_PREP; requires the sampler graph, "
           "sampler_prep and sampler_admit — without fpf_clisampler.policy it raises by name).",
           "exact by construction (every route is the stock sampler's arithmetic: graph replay / step-invariant hoist / stock; --det 1 byte identity at 2000 tokens on the graph and eager routes)",
           probe="env", requires=("sampler_graph", "sampler_prep", "sampler_admit"),
           source="env.sh L74 (beside PTX_SAMPLER_PREP, unset with the sampler graph); opt/forward/flashpairformer/src/infopt_graphs/protenix/sampler_prep.py ([sampler_reach] sites), src/fpf_clisampler/clisampler.py (record reach=), src/fpf_clisampler/policy.py"),
    _lever("sampler_graph_cache_policy", FORWARD, EXACT, ("INFOPT_GRAPHS_MAX_ENTRIES", "INFOPT_GRAPHS_EMPTY_CACHE_GUARD"),
           "Graph cache: one entry (hazard #44-safe with the hoist) and the EmptyCacheGuard (defers empty_cache while >= 2 graphs live).",
           "n/a (policy)", source="env.sh L64, L67; src/infopt_graphs/protenix/graphed.py (HAZARD44 guard)"),
    _lever("sampler_fuse", FORWARD, EXACT, ("PTX_SAMPLER_FUSE",),
           "The diffusion transformer's elementwise chains (AdaLN tail, attention output gate, gated residual, SwiGLU) as one fused Triton kernel each (the DIT_FUSE add-on's F kernels, installed on the built model after InferenceRunner.__init__ in every kit mode; the hoist's AdaLN sites keep the hoist).",
           "bitwise vs the stock chains by construction (fp32, libdevice expf, IEEE division, no FMA contraction: opt/forward/DIT_FUSE/tools/dit_fuse_patch.py); every token count (the diffusion sampler is fp32 at every size a kit mode runs: stock's own setting for every size protenix-v2 accepts, kept above the size guard by big's guard_lift; a call that did arrive under autocast would run the module's own stock method, counted regime_stock_calls) (elementwise launches; the atom blocks' local-attention gate stays stock, HAZARDS #7)",
           probe="marker", extra=True, source="opt/protenix_opt/sampler_fuse.py (wraps runner.inference.InferenceRunner.__init__); opt/forward/DIT_FUSE/tools/dit_fuse_patch.py, dit_fuse.py"),
    _lever("fastln_prebuilt", FORWARD, EXACT, (), "Prebuilt stream-correct fast-LayerNorm .so matching the installed torch (the loader re-checks it bitwise at load).",
           "bitwise check at load (21 cases)", conditional=("INFOPT_FASTLN_PREBUILT",),
           source="env.sh L75-86: auto-selected from $FPF_HOME/third_party/fastln_prebuilt*/manifest.json by the installed torch version; a pre-set value is honoured"),
    _lever("ln_core", FORWARD, TOLERANCE, ("PTX_LN_TIER",),
           "The model's standalone LayerNorm calls (protenix FusedLayerNorm, the stock fast_layernorm module) bound to the shared core's LayerNorm provider "
           "opt_core.kernels.ln by TIER WORD (PTX_LN_TIER = fast under --mode fast, big under --mode big; modes.PACKAGE_POST): for a call in the provider's bf16o form "
           "(bf16 x, fp32 parameters: the trunk under autocast) the word's row for the call's cell (width x rows, LN_CELLS.json) is asked once per call class; a CARRIED row "
           "(fastln:lp today at the pair widths from the cells' measured crossover up, and everywhere under big) is executed by the provider, the STOCK row fast_layernorm "
           "(the cells' measured stock arm: the provider names it, never executes it), a width no cell family lists, a refusal, and every non-bf16o call (the fp32 sampler and "
           "heads) run the module's own statement BY NAME = the kit's stream-correct build of the library op (fastln_prebuilt). --mode exact does not install it: no provider "
           "row is byte-identical to fast_layernorm (exactln is bitwise to ATen's kernel), so the exact word is the library op by name (unchanged bytes). LEVER line: word, calls, "
           "core (provider-executed) with rows=<arm:calls>, byname split (form / stock / uncovered / refused), uncovered cell classes.",
           "tolerance class inside the provider's LN band (fastln:lp relrms 1.7e-3 vs fp64 = the bf16 output quantum; fast_layernorm's own is 2.5e-3); any width / row count "
           "(uncovered widths by name); capture=False by design (the by-name arm is the stream-correct build, the carried Triton rows launch on the current stream); steps "
           "aside by name (LNCORE:unavailable -> the mode refuses by name) without CUDA, with LAYERNORM_TYPE != fast_layernorm, or on an opt_core without kernels.ln's select surface",
           probe="marker", extra=True,
           source="opt/protenix_opt/modes.py PACKAGE_POST (PTX_LN_TIER per mode); opt/forward/flashpairformer/src/protenix_ptx_ln_core.py (hook: src/ptx_trunk2_levers.apply_from_env); opt_core/kernels/ln (LN_CELLS.json)"),
    _lever("xl_policy", FORWARD, EXACT, ("PTX_FPF_XL", "PTX_FPF_CHUNK_TOK", "PTX_XL_PAD8_MAX_TOK", "PTX_BLK_GRAPH_MEM_GB", "PTX_FPF_CHUNK_MODE",
                                         "PTX_BLOCKFUSE_XL", "PYTORCH_CUDA_ALLOC_CONF"),
           "XL token policy + BlockFuse + expandable-segments allocator (memory policy; no numeric effect).", "kit README XL row",
           source="env.sh L93-97"),
    # ---- kit README row switches (E*/T* per (cc | triton); exported by modes.resolve() around env.sh; part of the arm only on the
    # ---- rows that list them — modes.README_ROWS, kit README 'Compositions per (cc | triton)' and 'Order of env operations') --------------------------------------------------------
    _lever("pad8", FORWARD, EXACT, ("PTX_E_PAD8", "PTX_E_PAD8_MIN_TOKENS"),
           "PAD8-EXACT: stock cuEq triangle attention on ceil8-padded zero-initialised buffers above PTX_E_PAD8_MIN_TOKENS (E* on cc 9.0; off on cc >= 10).",
           "cc 8.x/9.x, N%8!=0, N >= PTX_E_PAD8_MIN_TOKENS; provider refuses kv_len < 104 and probes torch.equal on first call (kit README 'Switches around env.sh')",
           extra=True, row_dependent=True, source="kit README 'Switches around env.sh', compositions table (E* rows)"),
    _lever("glue_v2", FORWARD, EXACT, ("PTX_GLUE_V2",),
           "Glue-track prologue_v4 / epilogue_v3 kernels around the block core (E* and T*).",
           "cells keyed cc|triton: 9.0|3.3, 9.0|3.7, 10.0|3.6, 10.0|3.7 (the core package's table) and 8.0|3.7 (entry sm80_t37 of the same core table, lifted from this unit's A100 pass with provenance); any other key refuses loudly and runs the shipped kernels (kit README 'Switches around env.sh')",
           extra=True, row_dependent=True, source="kit README 'Switches around env.sh', compositions table"),
    _lever("mk_pf", FORWARD, EXACT, ("PTX_MK_PF",),
           "Pairformer MK-PF kernel set: F1 on 9.0|3.7 and 8.0|3.7 (the 8.0 cell is entry sm80_t37 of the core package's own table), F1,F3 on 10.0|3.7 (E* and T*); not part of the 9.0|3.3 arm (F1 is Tier-2 there, hazard #41).",
           "kit README compositions table, MK-PF column", extra=True, row_dependent=True,
           source="kit README compositions table"),
    _lever("trimul_core", FORWARD, TOLERANCE, ("PTX_TRIMUL", "FPF_SMALLN_TRIMUL_FAST_FN", "FPF_SMALLN_TRIMUL_EXACT_FN"),
           "The pair-stack triangle multiplication (c_z 256, both directions) through the shared core's ONE TriMul provider by TIER word — "
           "opt_core.kernels.trimul by_word(weights_of, <the kit mode's tier word>): big under --mode big (PROTENIX_OPT), else fast: the fastest measured "
           "row of the call's cell on this card (cc 9.0: tx_sm90a / native per N bucket; cc 8.0: esm_v5_fwd / native; whatever the core's cells return IS the "
           "binding — no row is pinned by the kit). PTX_TRIMUL=tier (exported by env.sh under ARM T); fpf_smalln names src/ptx_trimul_routes.py:trimul_c256 as "
           "BOTH its below- and above-crossover TriMul callee (FPF_SMALLN_TRIMUL_EXACT_FN / _FAST_FN: one callee, the provider's N buckets decide; the kit keeps no "
           "TriMul crossover). LEVER line impl=trimul:<row>@<fast|big>/<cell> bind=tier:<word>; a row that refuses a call by name steps aside to the tier's next row inside the provider, named.",
           "TOLERANCE class (the core's per-cell record: tol(maxabs;relrms) vs the library op); N > 100 (min_tokens 101); every card the core's table covers",
           probe="marker", words=(("PTX_TRIMUL", "tier"),),
           source="env.sh (ARM=T: PTX_TRIMUL=tier, FPF_SMALLN_TRIMUL_*_FN=ptx_trimul_routes:trimul_c256); opt/forward/flashpairformer/src/ptx_trimul_routes.py; opt_core/kernels/trimul (TRIMUL_CELLS.json)"),
    _lever("dit_attn", FORWARD, TOLERANCE, ("PTX_DIT_ATTN",),
           "DiT token attention with pair bias (the 24 DiffusionTransformer blocks, 16 heads x 48, the 5 samples batched) on one fused Triton flash-attention launch per call: q/k/v/g as strided views of the stock projections, the pair bias shared by the samples in-kernel, fp32 online softmax and accumulation, the output gate fused in the epilogue; tf32x3 operands (3xTF32: fp32-faithful, the class of the cutlass fp32 kernel stock dispatches to) — TOLERANCE only because the reduction order differs (fpf_apb; T* rows of cc 9.0).",
           "protenix_opt 0.3.51: the shared core's provider opt_core.kernels.apb by the mode's TIER WORD (fast | big) per call class (card, dtype, samples, token bucket, eager | graph capture) on every card -- the provider's measured table names and serves the row (its stock-family rows included where they are the measured winner); a class no admitted row serves takes the statement BY NAME (aside=<kind>:<n>); refuses by name at install on any topology it does not know",
           probe="marker", extra=True, row_dependent=True, subsumes=(("sampler_fuse", "calls_gate", "0"),),
           source="opt/protenix_opt/apb_levers.py (runner seam, after sampler_fuse) + opt/protenix_opt/apb_core.py; modes.README_ROWS T* rows of cc 9.0 and 8.0; common/opt_core opt_core.kernels.apb"),
    _lever("dit_attn_fp16", FORWARD, TOLERANCE, ("PTX_DIT_ATTN_FP16",),
           "PRECISION lever on top of dit_attn: the same kernel with fp16 tensor-core operands (q, k, v, P cast in-kernel); bias, logits, softmax statistics and accumulation stay fp32 (the TF32-floor error class of the cuBLAS GEMMs around the site) — the lever that buys the DiT attention speed (5x stock per call vs 1.7x at tf32x3). Requires dit_attn: no install of its own (fpf_apb.install_dit_attn(model, fp16=True) is the one install point of both); ablated alone the kernel stays on at tf32x3; dit_attn ablated while this one stays is refused by name (T* rows of cc 9.0).",
           "protenix_opt 0.3.51: ON = the provider's fp16-operand arms (<row>:fp16) are admissible to the tier word and serve where they are the measured winner of the call class; ablated = such a class is re-decided by the provider's prefer rule on the same row (fp16_calls counts the calls an fp16 arm served); the yardstick verdict (YARDSTICK_ptx2 v1.1) is on dit_attn + dit_attn_fp16 + atom_attn together and on each alone",
           probe="marker", extra=True, row_dependent=True, requires=("dit_attn",),
           source="opt/protenix_opt/apb_levers.py (rides dit_attn's install) + opt/protenix_opt/apb_core.py; modes.README_ROWS T* rows of cc 9.0 and 8.0; common/opt_core opt_core.kernels.apb"),
    _lever("atom_attn", FORWARD, TOLERANCE, ("PTX_ATOM_ATTN",),
           "Atom encoder / decoder local attention with pair bias (6 AtomTransformer attention modules of the diffusion module, 4 heads x 32, 32-query x 128-key windows) on one Triton launch per call: windows and the key-range rule in-kernel, TF32-rounded operands, fp32 softmax and accumulation, the gate fused (fpf_apb; T* rows of cc 9.0).",
           "protenix_opt 0.3.51: the shared core's windowed face opt_core.kernels.apb.atom_attention by the mode's TIER WORD per call class on every card (the provider's measured table names and serves the row); a class no admitted row serves takes the statement BY NAME (aside=<kind>:<n>); refuses by name at install on a local-attention method / geometry it does not know",
           probe="marker", extra=True, row_dependent=True, subsumes=(("sampler_graph", "glue_padbias_builds", "0"), ("sampler_graph", "glue_padbias_hits", "0")),
           source="opt/protenix_opt/apb_levers.py (runner seam, after sampler_fuse) + opt/protenix_opt/apb_core.py; modes.README_ROWS T* rows of cc 9.0 and 8.0; common/opt_core opt_core.kernels.apb"),
    _lever("keep_pool", FORWARD, EXACT, ("PTX_KEEP_POOL",),
           "Caching-allocator policy: the stock empty_cache() calls inside the model forward (confidence head) are skipped so the blocks the diffusion sampler freed serve the confidence head without a synchronous release and re-growth; every kit release and the per-item runner release run unchanged.",
           "all cards; caller identified by source file (stock protenix package); sites pinned to Protenix 2.0.0 (tests/test_keep_pool.py census)",
           probe="marker", source="env.sh L23; opt/forward/flashpairformer/src/protenix_ptx_keep_pool.py (hook: src/ptx_trunk2_levers.apply_from_env, after the FPF levers)"),
    _lever("summary_hostidx", FORWARD, EXACT, ("PTX_SUMMARY_HOST",),
           "Summary confidence (pTM / ipTM / chain and chain-pair pTM, gPDE, pLDDT, clash) computed with host-side chain bookkeeping from one device-to-host copy of the token and atom id rows per item and integer-index gathers of the same elements in the same order; the value-producing GPU operations are the stock ones.",
           "all cards; inference call shape (interested_atom_mask / mol_id / elements_one_hot None) — other call shapes run the stock function (counted as delegated); a drifted stock signature refuses by name at install",
           probe="marker", source="env.sh L24; opt/forward/flashpairformer/src/protenix_ptx_summary_host.py (hook: src/ptx_trunk2_levers.apply_from_env, after the FPF levers)"),
    _lever("triatt_prologue_cuda", FORWARD, EXACT, ("PTX_TRIATT_PROCUDA",),
           "the fused tri-attention prologue (LayerNorm, q/k/v/g projections and pair bias of every c_z=256 triangle-attention node on the block "
           "path) as one hand-written sm_90a kernel (TMA + wgmma, warp-specialized) whose arithmetic is the MK-PF F1 cell's, operation for operation; "
           "outputs written straight into the statement's row-major, head-major (triatt_headsplit_exact) or padded (pad8) layouts. cc-9.0 rows only "
           "(row_dependent: the kit README rows of cc 9.0 export the switch in the exact and fast compositions; another card's row keeps the F1 "
           "Triton prologue — not a refusal there); c_z=64 template-stack nodes and write_x requests stay on the F1 cell by declared, counted reason.",
           "EXACT-BY-CONSTRUCTION (torch.equal vs the F1 cell on every size / layout / node / padding; --det 1 byte identity on both routes); requires "
           "mk_pf=F1 with the welford cell; the first call of every new shape is compared bitwise with the F1 cell and the lever refuses by name on a "
           "mismatch (never caught); a shape first met under graph capture is checked at its next eager call (chk_defer / chk_pending, 0 at exit); "
           "refuses by name at install (PROCUDA:unavailable -> NOT ACTIVE) without PTX_BLK=2, CUDA, cc 9, MK-PF F1 on the prologue, or on a "
           "binary / source sha256 differing from the manifest",
           probe="marker", extra=True, row_dependent=True,
           source="the kit README rows of cc 9.0, exact + fast compositions (modes.README_ROWS post export); opt/forward/flashpairformer/third_party/protenix_fpf_triatt_procuda (hook: src/ptx_trunk2_levers._apply_blk2, after MK-PF and triatt_headsplit_exact)"),
    _lever("pf_attn", FORWARD, TOLERANCE, ("PTX_PF_ATTN",),
           "AttentionPairBias of the 48-block Pairformer stack and the confidence-head Pairformer (has_s=False): the pair-bias PRODUCER (LayerNorm(z) + "
           "the 16-head bias projection, head-major fp32 planes) and the attention CORE (gate fused) on the stock projections, both served by the shared "
           "core's provider opt_core.kernels.apb by the mode's TIER WORD (protenix_opt 0.3.51: pair_bias_planes + pair_bias_attention per call class; "
           "the provider's measured table names the rows, its stock-family rows included), instead of stock's LayerNorm kernel + Linear + permute + "
           "q/k/bias .float() copies + SDPA + transposes. FAST rows of cc 9.0 only: the big line keeps apb_bias_chunk's chunked producer above 1023 "
           "tokens (modes.BIG_DROPPED; not in mode there, never refused); layernorm_fast's kernel is no longer called for these modules' layernorm_z "
           "(a declared census interaction).",
           "TOLERANCE (the provider's tolerance-class rows: fp32 statistics / logits / softmax / accumulation in the rows' own order); bf16 autocast "
           "only (dtype_gate: aside BY NAME under --dtype fp32 / fp16); a class no admitted row serves takes the statement BY NAME (aside=<kind>:<n>); "
           "refuses by name (PF_ATTN:unavailable, the error propagates) on cross-attention / efficient-fusion configs or an unknown topology",
           probe="marker", extra=True, row_dependent=True,
           source="the kit README rows of cc 9.0, fast composition (modes.README_ROWS post export; big: modes.BIG_POST switches it off); opt/protenix_opt/apb_levers.py + apb_core.py; common/opt_core opt_core.kernels.apb"),
    _lever("opm_fused", FORWARD, TOLERANCE, ("PTX_OPM_FUSED",),
           "OuterProductMean of the MSA module (4 modules): fused LayerNorm(m) + [linear_1 | linear_2] in one pass over m, stock's own einsum GEMM "
           "per row chunk, and linear_out on the einsum's native layout with the bias and the /norm in the epilogue (protenix_fpf_msa) — the permute "
           "copy of the [chunk, N, 32, 32] result, the mask multiplies and the division pass are gone; fast + big rows of cc 9.0 (row_dependent); "
           "layernorm_fast's kernel is no longer called on these modules (declared census interaction); a module another lever already owns is left "
           "alone and NAMED.",
           "TOLERANCE, bf16 class: error vs fp64 at or below stock's own on real tensors (reduction orders differ from cuBLAS); refuses by name in "
           "training mode, with an explicit mask, batched m, fp16 autocast, non-power-of-two c_m / c_hidden or a model without exactly one MSAModule",
           probe="marker", extra=True, row_dependent=True,
           source="the kit README rows of cc 9.0, fast composition (modes.README_ROWS post export; big through its base); opt/protenix_opt/apb_levers.py + third_party/protenix_fpf_msa"),
    _lever("pwa_fused", FORWARD, TOLERANCE, ("PTX_PWA_FUSED",),
           "MSAPairWeightedAveraging of the MSA module (3 modules): fused LayerNorm(m) + [linear_mv | linear_mg] with v stored head-major, the "
           "pair-weighted average as one cuBLAS bmm with contiguous operands (fp32 accumulation), a fused LN(z) + linear_z producer + softmax — or "
           "pwa_zcache's cached stock weights when that EXACT lever set them (counted: zcache_hits) —, and a fused sigmoid-gate x out-projection in "
           "stock's rounding chain (protenix_fpf_msa; the z-path producer is protenix_fpf_apb's pf_bias); fast + big rows of cc 9.0; layernorm_fast's "
           "kernel is no longer called on these modules (declared census interaction).",
           "TOLERANCE, bf16 class: identical to stock to 3 digits vs fp64 on real tensors; refuses by name in training mode, on batched m / z, "
           "non-power-of-two sizes, protenix_fpf_apb not importable, or a model without exactly one MSAModule",
           probe="marker", extra=True, row_dependent=True,
           source="the kit README rows of cc 9.0, fast composition (modes.README_ROWS post export; big through its base); opt/protenix_opt/apb_levers.py + third_party/protenix_fpf_msa"),
    _lever("cond_dedupe", FORWARD, TOLERANCE, ("PTX_COND_DEDUPE",),
           "DiffusionConditioning evaluated once per step on the sample-invariant noise level (a stride-0 guard decided from strides, no device read) and broadcast over the samples (hoisting of provably identical rows; the conditioning GEMMs see 1 row-set instead of 5); a non-expanded t_hat takes the stock rows (counted, never refused).",
           "any N; sm_90 rows (the T* rows of cc 9.0 export the switch)", probe="marker", extra=True, row_dependent=True,
           source="opt/protenix_opt/sampler_levers.py (runner seam, after the attention levers); modes.README_ROWS T* rows of cc 9.0; opt/forward/flashpairformer/third_party/protenix_fpf_ditfast/cond_dedupe.py"),
    _lever("dit_fused", FORWARD, TOLERANCE, ("PTX_DIT_FAST",),
           "The sampler's 24 token DiffusionTransformer blocks as one fused forward: merged q/k/v/g and a1/a2 GEMMs, the 24 blocks' conditioning Linears as 2 fp32 GEMMs (AdaLN affine folded), AdaLN / SwiGLU / gate+residual+AdaLN Triton row kernels, hoisted fp32 pair bias, attention = dit_attn's fused kernel called directly (ENGINEERING; TOLERANCE because GEMM shapes change).",
           "sm_90; Protenix-v2 token blocks (c_a 768, c_s 384, 16x48, n=2, q bias, gating); requires dit_attn (refused by name without it)", probe="marker", extra=True, row_dependent=True, requires=("dit_attn",),
           subsumes=(("dit_attn", "calls", "0"),),
           source="opt/protenix_opt/sampler_levers.py (runner seam, after the attention levers); modes.README_ROWS T* rows of cc 9.0; opt/forward/flashpairformer/third_party/protenix_fpf_ditfast/dit_fast.py, kernels.py"),
    _lever("dit_lowp", FORWARD, TOLERANCE, ("PTX_DIT_LOWP",),
           "PRECISION lever on dit_fused: the token-block a-path GEMM operands (q/k/v/g, o, a1/a2, b) and dit_attn's operands in fp16 (the measured cell word; bf16 = the documented alternative) with fp32 accumulation (allow_fp16_reduced_precision_reduction off); the residual stream, LayerNorm / softmax statistics, conditioning GEMMs and the pair bias stay fp32. Ablating it alone leaves dit_fused on fp32 storage / TF32 GEMMs / tf32x3 attention.",
           "word fp16 on sm_90 (measured envelope: worst cast operand 696 vs 65504); requires dit_fused", probe="marker", extra=True, row_dependent=True, requires=("dit_fused",),
           source="opt/protenix_opt/sampler_levers.py (runner seam, after the attention levers); modes.README_ROWS T* rows of cc 9.0; opt/forward/flashpairformer/third_party/protenix_fpf_ditfast/dit_fast.py"),
    _lever("atom_fused", FORWARD, TOLERANCE, ("PTX_ATOM_FAST",),
           "The sampler's atom transformers (encoder + decoder, 3 blocks each) as fused stacks: merged q/g, k/v, a1/a2 GEMMs, AdaLN / SwiGLU / gate+residual kernels, per-item hoisted conditioning + local pair bias, attention = atom_attn's kernel called directly; fp32 activations (no precision switch).",
           "sm_90; c_atom 128, 4x32, 32x128 windows; requires atom_attn (refused by name without it)", probe="marker", extra=True, row_dependent=True, requires=("atom_attn",),
           subsumes=(("atom_attn", "calls", "0"),),
           source="opt/protenix_opt/sampler_levers.py (runner seam, after the attention levers); modes.README_ROWS T* rows of cc 9.0; opt/forward/flashpairformer/third_party/protenix_fpf_ditfast/atom_fast.py, atom_kernels.py"),
    _lever("atom_attn_exact", FORWARD, EXACT, ("PTX_ATOM_ATTN_EXACT",),
           "The atom transformers' 32-query x 128-key local attention (dense-trunk rearrangement + chunked SDPA math path) as ONE bit-exact Triton launch per call reproducing the stock statement's cuBLAS TF32 / softmax / accumulation order (EXACT-BITWISE: per-process route table + a 4-case load check against recorded stock output digests; a mismatch refuses by name).",
           "sm_90; fp32 q/k/v [..,4,N_atom,32], n_queries 32, n_keys 128 (the bf16 input-embedder call takes the original statement, counted); the exact composition's rows of cc 9.0 (fast / big: the site belongs to atom_attn / atom_fused)", probe="marker", extra=True, row_dependent=True, replaced_by=("atom_attn", "atom_fused"),
           subsumes=(("sampler_graph", "glue_padbias_builds", "0"), ("sampler_graph", "glue_padbias_hits", "0")),
           source="opt/protenix_opt/sampler_levers.py (runner seam); modes.README_ROWS E* rows of cc 9.0; opt/protenix_opt/apb_atom_exact.py: opt_core.kernels.apb by the tier word exact (row atom_exact = this kit's former protenix_fpf_atom_attn_exact kernel lifted verbatim into the core, vouched per stack / card by the provider's cells; the statement BY NAME where the word names it)"),
    _lever("transition_core_exact", FORWARD, EXACT, ("PTX_TRANSITION",),
           "Every eval Transition call (the pair transitions of the Pairformer / MSA-module / confidence-head / template pair stacks, the single transition, the MSA "
           "transition) and the block statement's in-block pair transition through the shared core's ONE transition provider, opt_core.kernels.transition, by the TIER "
           "WORD exact (bind=tier:exact; src/ptx_transition_core.py; no row name, no kit cell table): the provider's select() serves only rows its table records BITWISE "
           "against the statement on this stack from the call's size up, handed the module's own LayerNorm output (cc 9.0: flash_sm90a on the pair c 256 cells from 400 "
           "tokens, v1 on c 128; cc 8.0: v1 above the stack's vouch floor) and otherwise names the stock row — such calls, calls it refuses by name and shapes its table has "
           "no cell word for (the diffusion conditioning's n=2 transitions) run the forward found at install by name (T1's), counted per reason on the LEVER line.",
           "bf16 autocast eval calls; the cells of opt_core TRANSITION_CELLS.json (cc | stack | dtype | shape | size | timing); word exact", probe="marker", source="env.sh L9"),
    _lever("transition_core", FORWARD, TOLERANCE, ("PTX_TRANSITION",),
           "The same binding under the TIER WORDS fast | big (bind=tier:fast under fast, tier:big under big — modes.BIG_PRE): the provider serves each cell's measured "
           "winner inside the engine band (cc 9.0 pair c 256: v2 / flash_sm90a:kernel_ln / esm_t16 by size, single c 384: v2, c 64 rows: v2 / af3_fused; cc 8.0: v1:lnfused / "
           "pf / v2 launch words), the row's own fused LayerNorm where it carries one; stock cells, refusals by name and shapes without a cell word run T1's forward by name.",
           "bf16 autocast eval calls; the cells of opt_core TRANSITION_CELLS.json; words fast | big", probe="marker", source="env.sh L9"),
    _lever("dit_attn_exact", FORWARD, EXACT, ("PTX_DIT_ATTN_EXACT",),
           "the DiffusionTransformer pair-bias attention statement (protenix.model.modules.primitives._attention: fp32 memory-efficient scaled-dot-product attention, head dim 48, the bias shared by the batched diffusion samples) routed per call class through the shared core's provider opt_core.kernels.apb by the tier word `exact` (protenix_opt 0.3.51): the provider's dit_exact row -- its carried prebuilt sm_90 CUDA kernel producing the same bits as the kernel it replaces -- serves the classes the provider's table vouches on THIS stack (torch / CUDA / triton / cuequivariance key); a class the exact word resolves to a stock-family arm keeps the statement itself BY NAME (counted exact_word:<arm>); other callers of that statement (atom transformer head dim 32, bf16 sites, no bias) take it by declared, counted route.",
           "cc 9.0 only (the exact composition of the cc-9.0 rows exports the switch; another card's row does not list it); the row's manifest (sha256 of the binary AND of its csrc, torch / CUDA / module version) and a per-process 3-case load-time bit check against F.scaled_dot_product_attention (mandatory, never cached) -- any failed check raises by name (DITATTN:unavailable -> NOT ACTIVE); a stack the table does not vouch loads nothing and serves the statement by name (stated on the marker)",
           probe="marker", extra=True, row_dependent=True, replaced_by=("dit_attn",),
           source="kit README rows of cc 9.0, exact composition (modes.README_ROWS post export); opt/protenix_opt/apb_core.py (hook: src/ptx_trunk2_levers.apply_from_env, after the FPF levers); common/opt_core opt_core.kernels.apb (row dit_exact)"),
    _lever("triatt_exact", FORWARD, EXACT, ("PTX_TRIATT_EXACT",),
           "the pair stacks' triangle attention (the library call protenix.model.triangular.layers.cuequivariance_triangular_attn: the stock Attention module of the Pairformer / MSA-module / confidence-head / template pair stacks, the block statement's cores, the padded-buffer provider's own library handle) bound per call to the shared core's provider opt_core.kernels.triattn by the tier word `exact` alone, the site's own callable handed along as the stock op (src/fpf/triatt_exact.py): the provider's exact-class row triattn_exact -- its carried CUDA member, bit-identical to the library op on the cells its table proves, compiled at first use -- serves on a (cc | torch | library) stack the core's cell table vouches, the library op BY NAME everywhere else; a per-call refusal by name takes the library op for that call (counted: the member's served n/m next to the LEVER line). Bitwise the mode without it by construction",
           "the cc-9.0 and cc-8.0 rows (their exact composition exports the switch; a cc-10.x row does not list it); no kit floor, no kit cell table: opt_core.kernels.triattn TRIATTN_CELLS.json decides the row per (cc, dtype, head dim, heads, size) and its exact-stack vouch keys decide where triattn_exact serves; opt_core below the lever's floor, a missing engine module or an unknown switch value raises by name (TRIATT_EXACT:unavailable -> NOT ACTIVE)",
           probe="marker", extra=True, row_dependent=True,
           source="kit README rows of cc 9.0 and cc 8.0, exact composition (modes.README_ROWS post export); opt/forward/flashpairformer/src/fpf/triatt_exact.py (hook: src/ptx_trunk2_levers.apply_from_env, after dit_attn_exact); common/opt_core opt_core.kernels.triattn (rows triattn_exact, cueq)"),
    _lever("sampler_admit", FORWARD, EXACT, ("PTX_SAMPLER_ADMIT", "PTX_SAMPLER_RELEASE", "PTX_SAMPLER_HOIST_EAGER"),
           "The sampler admission policy: per item, from N_token, N_atom and the memory allocated at the sampler's entry, the projected sampler-phase peak of the graphed sampler + hoist (GRAPH: statics + pool + copies + record transient) and of the hoist driven eagerly on the stock loop (HOIST_EAGER: statics + record transient) is compared with a limit — big (admit=item): the item's own peak without the extras (max of the measured trunk-phase peak, the confidence head's and the stock sampler's projected phase peaks) + 1 GiB, so the memory row never raises the item peak by more than the 1.0 GiB slack (+0.5 GiB audit tolerance: SAMPLER-MEM admit_ok, else ADMIT_MISS is printed and counted); exact/fast (admit=memory): 0.90 x the device - 1 GiB — and the first route that fits runs, else the stock eager sampler (STOCK); one ADMIT line per item prints the projection, the limit and every model term; big (release=item) also releases every graph entry, the private pool and the hoist's slots at the sampler's exit (SAMPLER-MEM line).",
           "exact by construction: every route is the stock sampler's arithmetic (graph replay / step-invariant hoist / stock); model fitted on H100 80 GB at 1400/2000 tokens, tiers exercised at 3000/4000",
           probe="marker", extra=True, source="opt/protenix_opt/modes.py BIG_POST; opt/forward/flashpairformer/src/fpf_clisampler/policy.py"),
    _lever("pred_release", FORWARD, EXACT, ("PTX_PRED_RELEASE",),
           "The previous item's prediction (coordinates + full-data confidence tensors: two [N_sample,N,N,64] fp32 PAE/PDE logits = 2.4e-6*N^2 GiB) leaves the device at the next item's InferenceRunner.predict entry — the stock loop keeps `prediction` bound through the next forward (runner/inference.py L486-505); the dump precedes the release. Every mode; -4.7 GiB steady-state peak per process at 1400 tokens, -9.5 @2000, -21 @3000.",
           "bitwise: outputs are written before the release", probe="marker", extra=True, source="opt/protenix_opt/pred_release.py (wraps runner.inference.InferenceRunner.predict; cli.py installs it after phase_timing)"),
    _lever("guard_lift", FORWARD, EXACT, ("PTX_GUARD_LIFT",),
           "The stock runner's n_token > 2560 refusal lifted (big only): the item runs with protenix-v2's own precision settings at every size — confidence head under autocast, diffusion sampler fp32 (the runner's generic > 3840 bf16-sampler policy, written for the other checkpoints, is set back after its call); an OOM above the guard is a named failure, never a lower-precision retry.",
           "no arithmetic change at any size (the assertion only; skip_amp.sample_diffusion stays True above 3840 as below — under the runner's bf16 sampler the atom encoder would read noisy positions through a bf16 Linear and the denoised coordinates would round to bf16 each step, whose quantum is 0.06-0.5 Å at 16-128 Å magnitudes: covalent bond lengths off by that class with the fold intact); the size ceiling becomes the card's memory — an out-of-memory item is named in the outputs census",
           probe="marker", extra=True, source="opt/protenix_opt/runner_hooks.py; stock runner/inference.py update_inference_configs (the assertion)"),
    # ---- big: the memory levers of opt/protenix_opt/big.py on the shared core's registry (opt_core.mem); the line is one lever set (no switches; settings = big.SETTINGS)
    _lever("drop_bond_mask", FORWARD, EXACT, (),
           "The featurizer's INT64 [N_atom, N_atom] bond_mask (unread at inference) replaced by an empty tensor (big.py).",
           "bitwise-claimed: nobody reads the key at inference (readers in the pinned tree: protenix/model/loss.py only; tests/test_big.py greps the pin)",
           probe="marker", extra=True, source="opt/protenix_opt/big.py; stock protenix/data/core/featurizer.py get_mask_features"),
    _lever("cond_chunk", FORWARD, TOLERANCE, (),
           "DiffusionConditioning.prepare_cache row-blocked (256 token rows of the fp32 pair cache at a time above 1023 tokens; big.py).",
           "band: fp32 GEMMs at another M may differ by 1 ulp (the diffusion conditioning runs under skip_amp at every size: stock's own setting, kept above the size guard by guard_lift)",
           probe="marker", extra=True, source="opt/protenix_opt/big.py; stock protenix/model/modules/diffusion.py prepare_cache"),
    _lever("apb_bias_chunk", FORWARD, TOLERANCE, (),
           "AttentionPairBias pair bias linear_nobias_z(layernorm_z(z)) on 256 token rows at a time above 1023 tokens (big.py).",
           "band: the fp32 pair-bias linear at another M may differ by 1 ulp; the LayerNorm is per vector",
           probe="marker", extra=True, source="opt/protenix_opt/big.py; stock protenix/model/modules/transformer.py standard_multihead_attention"),
    _lever("relp_lazy", FORWARD, TOLERANCE, (),
           "The relative-position one-hot plane never materialised: input_feature_dict['relp'] is a LazyRelp (five [N] index vectors); RelativePositionEncoding.forward runs the stock relpe linear per block of 128 token rows into one [N, N, c_z] output and the row-blocked conditioning takes row slices (big.py); the fp32 [N, N, 139] plane (4.9 GB at 2,956 tokens, 9.2 GB at 4,076) is never resident.",
           "the one-hot rows are the stock integer statements (exact); the relpe GEMM at another M is 1-ulp class by construction",
           probe="marker", extra=True, source="opt/protenix_opt/big.py; stock protenix/model/modules/embedders.py RelativePositionEncoding"),
    _lever("msa_zfree", FORWARD, EXACT, (),
           "MSABlock.forward re-stated with the block-input pair tensor's storage released after the outer-product-mean residual add (big.py): one [N, N, c_z] pair tensor less through each MSA block's pair stack; refused by name when another lever owns MSABlock.forward.",
           "the stock statements in the stock order; a storage release after the tensor's last read — bitwise by construction",
           probe="marker", extra=True, source="opt/protenix_opt/big.py; stock protenix/model/modules/pairformer.py MSABlock.forward"),
    _lever("diffcache_free", FORWARD, EXACT, (),
           "The diffusion conditioning pair cache (prepare_cache's output, held by the inference loop's cache dict) has its storage released when ConfidenceHead.forward starts (big.py): 8.9 GB at 2,956 tokens off the confidence phase; refused by name when another lever owns ConfidenceHead.forward.",
           "a storage release after the cache's last reader (sampling) — bitwise by construction",
           probe="marker", extra=True, source="opt/protenix_opt/big.py; stock protenix/model/protenix.py _main_inference_loop, protenix/model/modules/confidence.py ConfidenceHead.forward"),
    _lever("cache_release", FORWARD, EXACT, (),
           "torch.cuda.empty_cache() at the kit's phase seams (after the trunk, after the diffusion conditioning cache, after sampling): the core's allocator lever, policy per_stage.",
           "bitwise-claimed: allocator policy only", probe="marker", extra=True, source="opt/protenix_opt/big.py; common/opt_core/opt_core/mem/allocator.py cache_release/release"),
    _lever("lazy_init", FORWARD, EXACT, ("PTX_LAZY_INIT",),
           "Skip the dead random init at model construction (start-up only).", "start-up only; no forward statement changes",
           probe="marker", extra=True, source="env.sh L31-33 (switch table); kit README 'Switches around env.sh'"),
    # ---- ARM=T only (env.sh L10-22) -------------------------------------------------------------------------------------------------
    _lever("blk2_chunked_k2b", FORWARD, TOLERANCE, ("PTX_BLK_CHUNKED",), "Chunked block core routed to the K2B kernel.", "K2B_CELLS.json",
           probe="marker", source="env.sh L11"),
    _lever("k2b_flash_triattention", FORWARD, TOLERANCE, ("PTX_BLK_ATT",), "K2B flash triangle attention (raw kernel in the block core).",
           "K2B_CELLS.json by_cc", probe="marker", replaced_by=("triattn_native",), source="env.sh L12"),
    _lever("triattn_native", FORWARD, TOLERANCE, ("PTX_T_ATT",),
           "The block core's Tier-2 triangle attention (48-block stack, MSA-module and confidence-head pair stacks) bound to the shared core's triangle-attention provider opt_core.kernels.triattn BY THE TIER WORD ALONE (word = the mode's own tier word, fast | big, handed to the face literally; opt_core >= 0.5.114.0): no row preference, no kit floor, no kit cell table — the provider's measured cell decides the row per (cc, heads, size, call form) and the LEVER line names the rows that served (rows=<row>:<calls>; at opt_core 0.5.114, D32 H8 bias_only: cc 9.0 triattn_native — the sealed package's Gluon member below 401 tokens, cuda_sm90a at 401..511, its sm_90a extensions from 512 — and cc 8.0 triattn_native's sm_80 member at every size); a row that refuses a call by name is served by the row the provider names instead through the same face (fallback_rows=<row>:<calls>, the refusal kind named once); the fast tier's small-N gate (library attention + exact TriMul below PTX_T_MIN_TOKENS=300, fpf_smalln) composes around it unchanged. PTX_T_ATT=<fast|big> — the mode's own tier word, no alias — is read BY env.sh (the kit README rows of cc 9.0 and cc 8.0 pre-export PTX_T_ATT=fast; big exports PTX_T_ATT=big, modes.extras) and selects the PTX_BLK_ATT provider word ptx_native_core:attn with PTX_BLK_ATT_PROVIDER_MIN_TOKENS=0 (k2b_flash_triattention is not part of the arm there; MODEL_OPT_LEVERS_OFF=triattn_native restores PTX_T_ATT=k2b).",
           "every card the provider's table has cells for (cc 9.0, cc 8.0 at opt_core 0.5.114; the rows' prebuilt binaries per torch/CPython ABI live under opt_core/kernels/triattn, digests and byte gates checked by the provider at first resolve, a failing package passed over BY NAME to the cell's next row); bf16, D = 32, masks [B,N,1,1,S] (form mask_bias) or none (form bias_only); no CUDA / no usable opt_core.kernels.triattn / a tier word every candidate refuses at install raise CoreAttnUnavailable by name out of the provider import (BLK_ATT:provider ptx_native_core:attn unavailable(...): the mode refuses by name)",
           probe="marker", extra=True, row_dependent=True, conditional=("PTX_BLK_ATT", "PTX_BLK_ATT_PROVIDER_MIN_TOKENS"), words=(("PTX_T_ATT", "fast"), ("PTX_T_ATT", "big")),
           source="kit README 'Switches around env.sh' + compositions table (T* rows of cc 9.0 and cc 8.0); env.sh L13 case; opt/forward/flashpairformer/src/ptx_native_core.py; opt_core/kernels/triattn (TRIATTN_CELLS.json)"),
    _lever("smalln_size_gate", FORWARD, TOLERANCE, ("FPF_SMALLN", "FPF_SMALLN_K2B_MIN_TOKENS", "FPF_SMALLN_TRIMUL_EXACT_BELOW",
                                                    "FPF_SMALLN_TRIMUL_EXACT_FN", "PTX_T_MIN_TOKENS", "FPF_OPS"),
           "ARM T size gate BY NUMBER (fpf_smalln as the FPF_OPS provider): below 300 tokens the block core's Tier-2 attention (K2B / the provider slot) steps "
           "down to the exact statement and the pair-stack TriMul is the core's EXACT tier (ptx_trimul_routes:trimul_exact_c256); at / above it the kit mode's tier "
           "word (lever trimul_core; protenix_opt 0.3.51: both callees are the shared core's one provider — no kit TriMul kernel below or above the gate).",
           "PTX_T_MIN_TOKENS (300); CELLS.json smalln_trimul_exact_below (per-arch crossover, sm100 576)", probe="marker", source="env.sh L12-13, L19-21"),
    # ---- the template embedder's c = 64 pair stack through the shared core's providers (env.sh PTX_TEMPL_* switches; src/ptx_c64_routes.py) -----------------
    _lever("templ_trimul_tmk3", FORWARD, EXACT, ("PTX_TEMPL_TRIMUL",),
           "The template embedder's c = 64 TriMul (c_z = c_hidden = 64, outgoing and incoming, 2 blocks per distinct template per recycle) through the shared core's `exact` TIER ROW "
           "for the call's cell — opt_core.trimul.by_word(weights_of, 'exact') over kernels.trimul, keyed (cc, bf16, 64, 64, N bucket, direction) on this process's stack: `native_exact` "
           "(the sealed native TriMul payload's exact variant) where the core's cells record it bitwise on this stack (cc 9.0, the kit's H100 image), `tmk3_exact` (the TM-K3 exact "
           "construction: the stock op's floating-point operations in the stock order) on cc 8.0 and on stacks without that record — both bitwise == the stock op, the residual fused as the "
           "library branch returns it; the row moves with the core's cells and the LEVER line names the row served (impl=trimul:<row>@exact/<cell>, bind=tier:exact). src/ptx_c64_routes.py "
           "is the composite FPF_OPS trimul provider: it follows the arm's own entry and hands every c = 256 call to it unchanged. ARM E (PTX_TEMPL_TRIMUL=tmk3); on ARM T the slot is "
           "templ_trimul_esm's (replaced_by).",
           "c_z == c_hidden == 64 on the library branch (triangle_multiplicative cuequivariance), N >= 101, a cell of opt_core kernels.trimul TRIMUL_CELLS.json with an exact row (9.0 and 8.0 | "
           "bf16 | C64 | H64 by N bucket); N <= 100 (the library's own torch branch), a cell without an exact row and a refusal of the row take the arm's forward by name (counted fallback_by); "
           "opt_core older than the module's floor (0.5.47): the lever steps aside by name at import",
           words=(("PTX_TEMPL_TRIMUL", "tmk3"),), replaced_by=("templ_trimul_esm",),
           source="env.sh L104-L113 (PTX_TEMPL_TRIMUL: ARM E word tmk3; the module's FPF_OPS trimul entries follow the arm's own); opt/forward/flashpairformer/src/ptx_c64_routes.py"),
    _lever("templ_trimul_esm", FORWARD, TOLERANCE, ("PTX_TEMPL_TRIMUL",),
           "The template embedder's c = 64 TriMul through the shared core's `fast` | `big` TIER ROW for the call's cell (protenix_opt 0.3.44; was: the kernels.trimul_esm_shapes package "
           "directly) — opt_core.trimul.by_word(weights_of, <tier>) over kernels.trimul, the tier word after the kit mode (`big` under big, `fast` under fast), keyed (cc, precision, 64, "
           "64, N bucket, direction) on this process's stack: `native` (the sealed native TriMul payload) / `esm_v5_fwd` / `esm_shapes` (the ESM-family lines: LN_in + gated dual projection -> "
           "bf16 planes, bmm, LN_out + out projection + gate, the residual fused as the library branch returns it) as the core's cells say — at opt_core 0.5.88 on the kit's H100 image big = "
           "`native` and fast = `esm_v5_fwd` at every template bucket, on cc 8.0 `esm_shapes` under both; the row moves with the core's cells and the LEVER line names the row served "
           "(impl=trimul:<row>@<tier>/<cell>, bind=tier:<word>). Same composite provider and sites as templ_trimul_tmk3; a row that refuses a call by name steps aside to the tier's next row "
           "inside the core, a call no row takes keeps the arm's forward (fallback_by). opt_core older than 0.5.86 (the first core whose (64, 64) tier rows carry the native payload) keeps the "
           "earlier route BY NAME: the kernels.trimul_esm_shapes package directly (bind=package:trimul_esm_shapes; a call outside its envelope re-routed to tmk3_exact, counted esm_rerouted). "
           "ARM T (PTX_TEMPL_TRIMUL=esm; the word tmk3 under a T mode runs the exact row there instead).",
           "c_z == c_hidden == 64 on the library branch, N >= 101 (the lever's gate), B = 1, forward only; cells of opt_core kernels.trimul TRIMUL_CELLS.json (9.0 and 8.0 | bf16 / f32z | C64 | "
           "H64 by N bucket and direction); opt_core older than the module's floor (0.5.47): aside by name at import",
           words=(("PTX_TEMPL_TRIMUL", "esm"),),
           source="env.sh L104-L113 (PTX_TEMPL_TRIMUL: ARM T word esm); opt/forward/flashpairformer/src/ptx_c64_routes.py"),
    _lever("templ_triatt_core", FORWARD, TOLERANCE, ("PTX_TEMPL_TRIATT",),
           "The template embedder's c = 64 triangle attention (2 heads x 32) resolved through the provider, opt_core.kernels.triattn, by its TIER WORD 'fast' (bind=tier:fast; the provider's "
           "select() names the row per cell, no row preference — word core, prefer=none, 0.3.50; a big mode binds fast, the provider's tier words being fast | exact): on the core's cells "
           "cc 9.0 serves calls below 512 tokens with the small-N rows cuda_sm90a / k2b and 512+ with the sealed triangle-attention package (triattn_native), cc 8.0 serves triattn_native per cell; "
           "the words native | sm90a | k2b pin one row; src/ptx_c64_routes.py wraps the library attention entry "
           "as found (above triatt_headsplit_exact's per-head entry) and routes only H == 2, D == 32 calls at N_token >= PTX_T_MIN_TOKENS (ARM T's size gate: below it these calls keep the "
           "library op, as the block core keeps the exact path) — the trunk / MSA / confidence pair stacks (8 heads, the block core's provider) and per-head calls pass through; a row that "
           "refuses is re-routed by name to its fallback row, at the end to the found entry (counted). ARM T only (PTX_TEMPL_TRIATT=core); ARM E keeps triattn_exact on these calls.",
           "H == 2 and D == 32 at N_token >= PTX_T_MIN_TOKENS (300), bf16 operands with the fp32 pair bias and the template pair mask; the cells of opt_core TRIATTN_CELLS.json (9.0 | bf16 | "
           "D32 | H2: cuda_sm90a / k2b below 512 tokens, triattn_native from 512; 8.0: triattn_native); a card or stack without an admitted row serves the found entry by name; opt_core older than "
           "the module's floor: the lever steps "
           "aside by name at import",
           source="env.sh L104-L112 (PTX_TEMPL_TRIATT, ARM T); opt/forward/flashpairformer/src/ptx_c64_routes.py"),
]}

BLK2_LEVERS = ("blk2_block_path", "blk2_chunked_exact", "blk2_chunked_k2b")   # the block path and its chunked cores: engage only on an arch listed in CELLS.json blk2_arch
NO_BLK2_CELLS = "no BLK2 cells"             # the reason prefix when a BLK2 lever cannot engage on the arch (stack._classify)
TRIATT_STATEMENT_LEVERS = ("nomask", "blk2_chunked_exact", "blk2_chunked_k2b", "k2b_flash_triattention", "triattn_native")   # levers that live inside the block core's fused tri-attention statement (prologue -> attention core -> epilogue): on an arch listed in CELLS.json blk2_triatt_stock_arch the core runs the stock tri-attention statement and these are not part of the arm on that card
STOCK_TRIATT = "the block core runs the stock tri-attention statement on gpu_arch="   # the reason prefix for TRIATT_STATEMENT_LEVERS on such an arch (stack._classify; report.card_lever_set_line keys on it)
NOT_IN_ROW = "not in the kit README row for kernel key "   # the reason prefix when the kernel key's compositions row does not list a row-dependent lever (stack._classify; report.card_lever_set_line keys on it)


def in_row(lever: Lever, row) -> bool:
    """Whether a kit README row (modes.readme_row(): {"pre": {...}, "post": {...}}) lists one of this lever's switches."""
    vals = dict((row or {}).get("pre", {})); vals.update((row or {}).get("post", {}))
    if lever.words:
        return any(vals.get(k) == w for k, w in lever.words)
    return any(k in vals for k in lever.env_keys)
