model:
  _yaml_: _model.yaml
  trunk:
    blocks_per_ckpt: null
  template_module:
    blocks_per_ckpt: null
  diffusion_head:
    blocks_per_ckpt: null

train:
  _yaml_: _train_base.yaml
  name: stage2-640

  data:
    max_length: 640
    max_seq_length: 1280
    max_templates: 2
    max_contiguous_chains: 6

    batch_size: 1
    global_batch_size: 256

    data_root: /data/atlasfold_data/
    train_datasets:
      - name: rcsb_multimer
        type: rcsb
        is_multimer: true
        is_distillation: false
        use_templates: true
        weight: 0.490
        template_prob: 0.4
      - name: disordered_pdb_afm
        type: rcsb
        is_multimer: true
        is_distillation: true
        use_templates: false
        weight: 0.010
      - name: mgnify_long
        type: monomer_distillation
        is_multimer: false
        is_distillation: true
        use_templates: false
        weight: 0.495
      - name: mgnify_short
        type: monomer_distillation
        is_multimer: false
        is_distillation: true
        use_templates: false
        weight: 0.005
    val_dataset:
      name: rcsb_multimer_val
      type: rcsb
      use_templates: false
