"""The cueq_tuned_tiles lever serves cuequivariance_ops' TriMul tile choices from the kit's own autotune cache (the levers add-on's cueq_cache/*.json,
generated by running the library's autotuner on our cards; no NVIDIA SDK data); its LEVER line states from the files actually present whether a table
for the running card exists (report.cueq_tiles_evidence) — never a claim."""
import json
import os
import tempfile

from protenix_opt import report as R, stack

DIR = os.path.join(stack.kit_home(), "levers_addon", "PTXV2_LEVERS_ADDON_v1", "cueq_cache")


def _packaged(cc: str):
    """NVIDIA's packaged table for this kernel and cc from the installed cuequivariance_ops wheel, or None when it is not importable here."""
    try:
        import importlib.util
        spec = importlib.util.find_spec("cuequivariance_ops")
    except Exception:
        spec = None
    if not spec or not spec.origin:
        return None
    p = os.path.join(os.path.dirname(spec.origin), "triton", "cache", f"{R.CUEQ_TILE_TABLE}.{cc}.json")
    if not os.path.isfile(p):
        return None
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


def _kit_table(cc: str) -> dict:
    with open(os.path.join(DIR, f"{R.CUEQ_TILE_TABLE}.{cc}.json"), encoding="utf-8") as fh:
        return json.load(fh)


def _assert_kit_generated(cc: str):
    """A shipped table is the autotuner's output on our own cards: well-formed entries, and not one entry of the packaged table (same key with the
    same measured time) when the wheel is importable to compare against."""
    d = _kit_table(cc)
    assert d and all(isinstance(g, dict) for g in d.values())
    for g in d.values():
        gi = g.get("gpu_information")
        assert gi is None or str(gi.get("major")) == cc.split(".")[0]                              # a gpu_information block, when present, is this card class's
        entries = {k: e for k, e in g.items() if k != "gpu_information"}
        assert entries and all("config" in e and {"TILE_M", "TILE_N", "TILE_K"} <= set(e["config"]) for e in entries.values())
    P = _packaged(cc)
    if P is not None:
        dup = [(gk, k) for gk, g in d.items() for k, e in g.items()
               if k != "gpu_information" and gk in P and k in P[gk] and e.get("time") == P[gk][k].get("time")]
        assert not dup, f"{len(dup)} entries of {R.CUEQ_TILE_TABLE}.{cc}.json carry the packaged table's own timing values (first: {dup[0]})"


def test_pair_follows_the_files(monkeypatch):
    monkeypatch.delenv("CUEQ_TRITON_CACHE_DIR", raising=False)
    assert R.cueq_tiles_dir() == DIR
    assert R.cueq_tiles_evidence({"gpu": {"cc": "10.0"}}) == [("tiles", "table_sm100")]
    assert R.cueq_tiles_evidence({"gpu": {"cc": "10.3"}}) == [("tiles", "table_sm100")]           # cuequivariance_ops reads the cc 10.0 table on a cc 10.3 card
    assert R.cueq_tiles_evidence({"gpu": {"cc": "8.0"}}) == [("tiles", "packaged_defaults(no_table_sm80)")]
    assert R.cueq_tiles_evidence({"gpu": {}}) == [("tiles", "unknown(no_cc)")] == R.cueq_tiles_evidence(None)
    with tempfile.TemporaryDirectory() as t:                                                     # a user's own cache dir: the pair follows ITS files
        env = {"CUEQ_TRITON_CACHE_DIR": t}
        assert R.cueq_tiles_dir(env) == t
        assert R.cueq_tiles_evidence({"gpu": {"cc": "9.0"}}, env) == [("tiles", "packaged_defaults(no_table_sm90)")]
        with open(os.path.join(t, R.CUEQ_TILE_TABLE + ".9.0.json"), "w", encoding="utf-8") as fh:
            fh.write("{}")
        assert R.cueq_tiles_evidence({"gpu": {"cc": "9.0"}}, env) == [("tiles", "table_sm90")]


def _cueq_line(mode="exact", cc="9.0"):
    rep = {"active": True, "mode": mode, "gpu": {"name": "NVIDIA H100 80GB HBM3", "cc": cc}, "levers_applied": ["cueq_tuned_tiles"],
           "levers_fallback": [], "levers_not_in_arm": [], "fallback_reasons": {}}
    return [l for l in R.lever_lines(rep) if l.endswith(" lever=cueq_tuned_tiles")][0]


def test_directory_ships_kit_generated_tables():
    assert os.path.isdir(DIR) and os.path.isfile(os.path.join(DIR, "README.md"))
    assert sorted(f for f in os.listdir(DIR) if f.endswith(".json")) == [f"{R.CUEQ_TILE_TABLE}.{cc}.json" for cc in ("10.0", "9.0")]   # the cc 9.0 and cc 10.0 tables, nothing else
    shipped = sorted(f[len(R.CUEQ_TILE_TABLE) + 1:-len(".json")] for f in os.listdir(DIR) if f.startswith(R.CUEQ_TILE_TABLE + ".") and f.endswith(".json"))
    assert shipped == ["10.0", "9.0"]
    for cc in shipped:                                                                             # provenance, EVERY shipped table: nothing of the packaged table of the same name (against the installed wheel when importable)
        _assert_kit_generated(cc)


def test_lever_line_states_the_table_on_sm90(monkeypatch):
    monkeypatch.delenv("CUEQ_TRITON_CACHE_DIR", raising=False)
    assert R.cueq_tiles_evidence({"gpu": {"cc": "9.0"}}) == [("tiles", "table_sm90")]
    line = _cueq_line()
    assert " state=on " in line and " strategy=F2.cueq_tuned_tiles tiles=table_sm90 mode=exact " in line
