"""Lazy autoload, installed at interpreter start by `pxdesign_opt_autoload.pth` (`import pxdesign_opt._autoload`).

With PXDESIGN_OPT=<mode> in the environment (`exact`, `fast` or `big`), the core's meta-path finder
(`opt_core.autoload`) is installed from this kit's AutoloadSpec: it waits for the first import of the trigger package `pxdesign` and, right
after that package's own body has executed, calls `pxdesign_opt.enable(mode, strict=True, trigger="pxdesign")`; when the mode cannot be
activated (core pin, no GPU, kit files, the installed upstream not the pinned stock, a model instance already built) the kit prints its NOT ACTIVE
line and the process exits 3 — stock never runs silently under PXDESIGN_OPT. An unmeasured GPU class or torch build is named on the ACTIVE line
(`notes=`), never refused. A value outside the mode table is a refusal, not a note: the trigger prints
`[pxdesign-opt] NOT ACTIVE: unknown PXDESIGN_OPT=...` and exits 3. With a mode set, the core pin gate (`pxdesign_opt.core_gate`) runs
here first, at interpreter start, before anything of the core is imported: an absent, older, newer or edited `opt_core` is one
`[pxdesign-opt] NOT ACTIVE: reason=core_missing:opt_core | core_mismatch: … | core_pin_unreadable: …` line and the interpreter ends with
status 3 (`os._exit`: a SystemExit raised while site.py executes a .pth line would be a status-1 fatal init error, and site.py swallows any
other exception a .pth line raises). The .pth text itself is generated by `opt/_build_backend.py` (`python _build_backend.py pxdesign_opt
PXDESIGN_OPT pxdesign-opt`): a guard that prints the same tag's NOT ACTIVE line and ends the process with status 3 when this module cannot be
imported at all under a set mode. Until the trigger nothing else is imported (no torch, no upstream); with PXDESIGN_OPT unset or "off"
nothing is installed at all, the gate does not run and nothing of the core is imported — the .pth line runs in every interpreter on the
box, the stock arm's processes included.

enable() arms the application on `pxdesign.runner.inference.InferenceRunner` (stack.py): the kit's own
`pxd_xattempt.hoist.install(runner.model)` runs when `load_checkpoint` returns — after the checkpoint is loaded, the activation point the
kit's unapplied source patch uses. So `PXDESIGN_OPT=exact pxdesign infer ...` is the stock command line with the lever attached.
The finder fires once and removes itself.
"""
import os
import sys

from . import TAG, core_gate                              # the package __init__ is import-free: nothing of the core, no torch

ENV = "PXDESIGN_OPT"
TRIGGERS = ("pxdesign",)
EXIT_NOT_ACTIVE = 3                                      # the kit's own copy of report.EXIT_NOT_ACTIVE: this module imports nothing of the core at start


def spec():
    """This kit's AutoloadSpec (the core imported here, only when a mode is selected)."""
    from opt_core.autoload import AutoloadSpec
    from .modes import MODES
    return AutoloadSpec(env=ENV, package="pxdesign_opt", tag=TAG, triggers=TRIGGERS, modes=MODES, exit_not_active=EXIT_NOT_ACTIVE)   # the names the variable accepts: exactly the mode table's


def _refuse(reason):
    """The .pth-time refusal: the line, then `os._exit(3)` — site.py wraps a .pth line in `except Exception`, and a SystemExit raised
    while the interpreter initialises site is a fatal init error (status 1), not the kit's exit code."""
    sys.stderr.write(f"[{TAG}] NOT ACTIVE: {reason}\n")
    sys.stderr.flush()
    os._exit(EXIT_NOT_ACTIVE)


def install(environ=None):
    """Install the finder for PXDESIGN_OPT (idempotent). Returns the finder, or None when the variable is unset or `off` (nothing of the
    core touched). Under a set mode the core pin gate runs first: its NOT ACTIVE line, then `os._exit(3)`."""
    environ = os.environ if environ is None else environ
    if (environ.get(ENV) or "").strip().lower() in ("", "off"):
        return None
    try:
        core_gate()                                      # [pxdesign-opt] NOT ACTIVE: reason=core_missing:opt_core | core_mismatch: … | core_pin_unreadable: …
    except SystemExit as x:                              # the gate has written and flushed its line; .pth time: end the interpreter with the kit's code
        sys.stderr.flush()
        os._exit(x.code if isinstance(x.code, int) else EXIT_NOT_ACTIVE)
    try:
        from opt_core.autoload import install as _install
    except ImportError as e:                             # a pinned core whose autoload module does not import: named, never a silent stock run
        _refuse(f"opt_core.autoload not importable ({type(e).__name__}: {e}); the kit runs on the core: pip install -e common/opt_core -e pxdesign/opt")
    return _install(spec(), environ)


def disarm() -> bool:
    """Remove this kit's finder (an explicit enable() wins over the PXDESIGN_OPT route). True when one was armed."""
    if (os.environ.get(ENV) or "").strip().lower() in ("", "off") and not any(type(f).__module__ == "opt_core.autoload" for f in sys.meta_path):
        return False
    from opt_core.autoload import disarm as _disarm
    return _disarm(spec())


FINDER = install()
